// Рядки v1.3 потоку W3 (онбординг 3.0 і секція «Розробка») і онбордингу 4.0
// (правки власника 5.10.2026: блок «Онбординг 4.0» у кінці кожної мови).
// Власник — онбординг; інші потоки цей файл лише читають.
//
// Правила тексту — у шапці src/i18n.js: однаковий набір ключів у чотирьох
// мовах, множини {n|…}, «» / “” / „“, ʼ в українській, без емодзі й капсу.
// Ключ, який уже є в іншому фрагменті, не дублюємо. Наявний ключ із
// src/i18n.js перекриваємо, лише назвавши його в OVERRIDES (стереже
// __tests__/i18nFragments.test.js). Кожна мова — окремий блок у цьому ж
// форматі (`  en: {` … `  },`): тест шукає в ньому ключі-дублікати.
//
// Тексти серії (жаринка, «так тримати», «тиждень») — спільні, з
// src/strings/shared.js. Тексти секції «Розробка» — лише українською в
// коді: вона існує тільки в dev-збірці.
//
// Перекриваємо: obPushTitle — крок сповіщень питає, коли надсилати слово дня;
// replayOnb — повтор із Параметрів тепер справжнє знайомство.
export const OVERRIDES = ['obPushTitle', 'replayOnb'];

export default {
  en: {
    // ── W3 ──
    // вітання
    ob3Hello: 'Hi! I’m Lingo.',
    ob3HookTitle: 'I’ll be your guide to the world of languages',
    // яку мову вчиш
    obLangTitle: 'Which language are you learning?',
    obLangSearch: 'Search languages',
    obLangSearchClear: 'Clear search',
    obLangPopular: 'Popular',
    obLangAll: 'All languages',
    obLangNone: 'We don’t have this language yet',
    obLangIsNative: 'your native language',
    obLangIsTarget: 'the language you’re learning',
    obLangCheer: '{lang}? Great choice!',
    obNativeLabel: 'My native language',
    obNativeChange: 'Change',
    obNativeTitle: 'Your native language',
    obNativeText: 'Translations and examples will be in this language.',
    obNativePhone: 'from your phone',
    obNativeA11y: 'Native language: {lang}. Change',
    langName_en: 'English',
    langName_uk: 'Ukrainian',
    langName_de: 'German',
    langName_es: 'Spanish',
    langName_fr: 'French',
    langName_it: 'Italian',
    langName_pl: 'Polish',
    langName_pt: 'Portuguese',
    langName_nl: 'Dutch',
    langName_cs: 'Czech',
    langName_sk: 'Slovak',
    langName_ro: 'Romanian',
    langName_hu: 'Hungarian',
    langName_el: 'Greek',
    langName_sv: 'Swedish',
    langName_da: 'Danish',
    langName_no: 'Norwegian',
    langName_fi: 'Finnish',
    langName_tr: 'Turkish',
    langName_ru: 'Russian',
    langName_ja: 'Japanese',
    langName_ko: 'Korean',
    langName_zh: 'Chinese',
    langName_ar: 'Arabic',
    langName_he: 'Hebrew',
    langName_hi: 'Hindi',
    langName_th: 'Thai',
    langName_vi: 'Vietnamese',
    langName_id: 'Indonesian',
    // варіанти мов (src/langVariants.js): регіон у дужках після назви мови
    langRegion_us: 'US',
    langRegion_gb: 'UK',
    langRegion_es: 'Spain',
    langRegion_latam: 'Latin America',
    // цілі з мовою
    pfGoalsTitleLang: 'Why are you learning {lang}?',
    pfGoalsTitleLangName: '{name}, why are you learning {lang}?',
    // план
    obBuildTitle: 'Putting your plan together…',
    obBuildLang: '{lang} · level {cefr}',
    obBuildTopics: 'Topics: {topics}',
    obBuildWod: 'Picking your word of the day…',
    obBuildWodDone: 'Your word of the day is ready',
    obPlanToday: 'Your word for today',
    // серія
    obStreakTitle: 'Learn every day and grow your flame',
    obStreakText: 'Learn every day and your flame grows. On day 7 it really catches fire.',
    obStreakHint: 'Slide across the days',
    obStreakA11y: 'Streak: {n} {n|day|days}. Adjust to watch the flame grow',
    // сповіщення
    obPushTitle: 'Choose when to send you the word of the day',
    obPushText: 'You can change it any time in Settings.',
    obPushMorning: 'Morning',
    obPushDay: 'Afternoon',
    obPushEvening: 'Evening',
    // віджети
    onbWidgetTitle: 'A word every time you pick up your phone',
    onbWidgetText: 'Add a widget: the word of the day, your words and your streak, right on your Home Screen.',
    onbWidgetTry: 'Try it: tap “Show translation”',
    onbWidgetAgain: 'Show me again how to add it',
    // демо
    obDemoTitle: 'Scan things around you and get them translated in 10 seconds',
    obDemoBeat1: 'Point your camera at an object',
    obDemoBeat2: 'LinguaLens cuts it out and names it',
    obDemoBeat3: 'The word lands in your word list',
    obDemoFinal: 'Your turn. It takes 10 seconds',
    obDemoWords: 'My words',
    obDemoReplay: 'Replay',
    obDemoTry: 'Try it',
    obDemoUsed: 'The free scan on this iPhone has been used. With Pro, scan as much as you like.',
    obDemoSkipHint: 'Tap to skip to the end',
    obDemoA11y: 'Demo: the camera sees a mug on a desk. LinguaLens cuts it out as a sticker with the word {word} ({tr}), and the word lands in My words. Then the whole scene: words appear over the laptop, the plant and the notebook.',
    // свято першого слова
    obCelebrateTitle: 'Your first word!',
    obCelebrateStreak: 'Your streak has started: day 1',
    // обіцянка
    obCommitGoal: 'First goal: 7 days in a row',
    obCommitKeep: 'Keep holding…',
    obCommitAgain: 'Hold until the ring is full',
    obCommitDoneSub: 'See you tomorrow for a new word',
    // пейвол онбордингу з наліпкою людини
    opwFirstWordText: 'Your free scan is already in your word list. With Pro, scan as much as you like.',
    // Параметри
    replayOnb: 'Go through the intro again',
    // ── Онбординг 4.0 ──
    obLangLearnLabel: 'The language I’m learning',
    obNameNice: 'Nice to meet you, {name}!',
    levelName1: 'Beginner',
    levelName2: 'Elementary',
    levelName3: 'Intermediate',
    levelName4: 'Confident',
    levelName5: 'Advanced',
    obPlanLevel: 'Level: {cefr} · {name}',
    obWodTitle: 'What’s the word of the day?',
    obWodText: 'Every day Lingo picks one useful word for you, with a translation, pronunciation and an example. Matched to your goals and level.',
    obDemoBeat4: 'Or a whole scene, every word at once',
  },

  uk: {
    // ── W3 ──
    ob3Hello: 'Привіт! Я Лінго.',
    ob3HookTitle: 'Я стану твоїм провідником у світ мов',
    obLangTitle: 'Яку мову вчиш?',
    obLangSearch: 'Пошук мови',
    obLangSearchClear: 'Очистити пошук',
    obLangPopular: 'Популярні',
    obLangAll: 'Усі мови',
    obLangNone: 'Такої мови поки немає',
    obLangIsNative: 'твоя рідна мова',
    obLangIsTarget: 'мова, яку вчиш',
    obLangCheer: '{lang}? Чудовий вибір!',
    obNativeLabel: 'Моя рідна мова',
    obNativeChange: 'Змінити',
    obNativeTitle: 'Твоя рідна мова',
    obNativeText: 'Цією мовою будуть переклади й приклади.',
    obNativePhone: 'з телефона',
    obNativeA11y: 'Рідна мова: {lang}. Змінити',
    langName_en: 'Англійська',
    langName_uk: 'Українська',
    langName_de: 'Німецька',
    langName_es: 'Іспанська',
    langName_fr: 'Французька',
    langName_it: 'Італійська',
    langName_pl: 'Польська',
    langName_pt: 'Португальська',
    langName_nl: 'Нідерландська',
    langName_cs: 'Чеська',
    langName_sk: 'Словацька',
    langName_ro: 'Румунська',
    langName_hu: 'Угорська',
    langName_el: 'Грецька',
    langName_sv: 'Шведська',
    langName_da: 'Данська',
    langName_no: 'Норвезька',
    langName_fi: 'Фінська',
    langName_tr: 'Турецька',
    langName_ru: 'Російська',
    langName_ja: 'Японська',
    langName_ko: 'Корейська',
    langName_zh: 'Китайська',
    langName_ar: 'Арабська',
    langName_he: 'Іврит',
    langName_hi: 'Гінді',
    langName_th: 'Тайська',
    langName_vi: 'Вʼєтнамська',
    langName_id: 'Індонезійська',
    // варіанти мов (src/langVariants.js): регіон у дужках після назви мови
    langRegion_us: 'США',
    langRegion_gb: 'Британія',
    langRegion_es: 'Іспанія',
    langRegion_latam: 'Латинська Америка',
    pfGoalsTitleLang: 'Для чого ти вчиш {lang}?',
    pfGoalsTitleLangName: '{name}, для чого ти вчиш {lang}?',
    obBuildTitle: 'Складаємо твій план…',
    obBuildLang: '{lang} · рівень {cefr}',
    obBuildTopics: 'Теми: {topics}',
    obBuildWod: 'Підбираємо слово дня…',
    obBuildWodDone: 'Слово дня готове',
    obPlanToday: 'Твоє слово на сьогодні',
    obStreakTitle: 'Вчи мову кожного дня та рости свій вогник',
    obStreakText: 'Вчись щодня, і вогник ставатиме більшим. На 7-й день він розгориться по-справжньому.',
    obStreakHint: 'Проведи пальцем по днях',
    obStreakA11y: 'Серія: {n} {n|день|дні|днів}. Гортай, щоб побачити, як росте вогник',
    obPushTitle: 'Обери, коли надсилати тобі слово дня',
    obPushText: 'Змінити можна будь-коли в Параметрах.',
    obPushMorning: 'Зранку',
    obPushDay: 'Удень',
    obPushEvening: 'Увечері',
    onbWidgetTitle: 'Слово щоразу, як береш телефон',
    onbWidgetText: 'Додай віджет, і слово дня, твої слова й серія будуть просто на головному екрані.',
    onbWidgetTry: 'Спробуй: торкнись «Показати переклад»',
    onbWidgetAgain: 'Покажи ще раз, як додати',
    obDemoTitle: 'Скануй предмети навколо й отримай їх переклад за 10 секунд',
    obDemoBeat1: 'Наведи камеру на предмет',
    obDemoBeat2: 'LinguaLens вирізає його й називає',
    obDemoBeat3: 'Слово летить у твій словник',
    obDemoFinal: 'Твоя черга. Це займе 10 секунд',
    obDemoWords: 'Мої слова',
    obDemoReplay: 'Ще раз',
    obDemoTry: 'Спробувати',
    obDemoUsed: 'Безкоштовний скан на цьому iPhone уже використано. З Pro скануй скільки хочеш.',
    obDemoSkipHint: 'Торкнись, щоб одразу побачити фінал',
    obDemoA11y: 'Демонстрація: камера бачить чашку на столі. LinguaLens вирізає її як наліпку зі словом {word} ({tr}), і слово потрапляє в «Мої слова». Потім уся сцена: над ноутбуком, рослиною й блокнотом зʼявляються їхні слова.',
    obCelebrateTitle: 'Перше слово вже твоє!',
    obCelebrateStreak: 'Серія почалась: 1 день',
    obCommitGoal: 'Перша ціль: 7 днів поспіль',
    obCommitKeep: 'Ще трохи…',
    obCommitAgain: 'Тримай до кінця кола',
    obCommitDoneSub: 'Побачимось завтра з новим словом',
    opwFirstWordText: 'Твій безкоштовний скан уже в словнику. З Pro скануй скільки хочеш.',
    replayOnb: 'Пройти знайомство ще раз',
    // ── Онбординг 4.0 ──
    obLangLearnLabel: 'Мова, яку я вчу',
    obNameNice: 'Приємно познайомитися, {name}!',
    levelName1: 'Новачок',
    levelName2: 'Початківець',
    levelName3: 'Середній',
    levelName4: 'Впевнений',
    levelName5: 'Досвідчений',
    obPlanLevel: 'Рівень: {cefr} · {name}',
    obWodTitle: 'Що таке слово дня?',
    obWodText: 'Щодня Лінго підбиратиме тобі одне корисне слово з перекладом, вимовою й прикладом. Під твої цілі й рівень.',
    obDemoBeat4: 'Або цілу сцену з усіма словами одразу',
  },

  de: {
    // ── W3 ──
    ob3Hello: 'Hallo! Ich bin Lingo.',
    ob3HookTitle: 'Ich begleite dich in die Welt der Sprachen',
    obLangTitle: 'Welche Sprache lernst du?',
    obLangSearch: 'Sprache suchen',
    obLangSearchClear: 'Suche löschen',
    obLangPopular: 'Beliebt',
    obLangAll: 'Alle Sprachen',
    obLangNone: 'Diese Sprache gibt es noch nicht',
    obLangIsNative: 'deine Muttersprache',
    obLangIsTarget: 'die Sprache, die du lernst',
    obLangCheer: '{lang}? Gute Wahl!',
    obNativeLabel: 'Meine Muttersprache',
    obNativeChange: 'Ändern',
    obNativeTitle: 'Deine Muttersprache',
    obNativeText: 'In dieser Sprache bekommst du Übersetzungen und Beispiele.',
    obNativePhone: 'vom Telefon',
    obNativeA11y: 'Muttersprache: {lang}. Ändern',
    langName_en: 'Englisch',
    langName_uk: 'Ukrainisch',
    langName_de: 'Deutsch',
    langName_es: 'Spanisch',
    langName_fr: 'Französisch',
    langName_it: 'Italienisch',
    langName_pl: 'Polnisch',
    langName_pt: 'Portugiesisch',
    langName_nl: 'Niederländisch',
    langName_cs: 'Tschechisch',
    langName_sk: 'Slowakisch',
    langName_ro: 'Rumänisch',
    langName_hu: 'Ungarisch',
    langName_el: 'Griechisch',
    langName_sv: 'Schwedisch',
    langName_da: 'Dänisch',
    langName_no: 'Norwegisch',
    langName_fi: 'Finnisch',
    langName_tr: 'Türkisch',
    langName_ru: 'Russisch',
    langName_ja: 'Japanisch',
    langName_ko: 'Koreanisch',
    langName_zh: 'Chinesisch',
    langName_ar: 'Arabisch',
    langName_he: 'Hebräisch',
    langName_hi: 'Hindi',
    langName_th: 'Thailändisch',
    langName_vi: 'Vietnamesisch',
    langName_id: 'Indonesisch',
    // варіанти мов (src/langVariants.js): регіон у дужках після назви мови
    langRegion_us: 'USA',
    langRegion_gb: 'Großbritannien',
    langRegion_es: 'Spanien',
    langRegion_latam: 'Lateinamerika',
    pfGoalsTitleLang: 'Warum lernst du {lang}?',
    pfGoalsTitleLangName: '{name}, warum lernst du {lang}?',
    obBuildTitle: 'Wir stellen deinen Plan zusammen…',
    obBuildLang: '{lang} · Niveau {cefr}',
    obBuildTopics: 'Themen: {topics}',
    obBuildWod: 'Wir suchen dein Wort des Tages aus…',
    obBuildWodDone: 'Dein Wort des Tages ist bereit',
    obPlanToday: 'Dein Wort für heute',
    obStreakTitle: 'Lerne jeden Tag und lass deine Flamme wachsen',
    obStreakText: 'Lerne jeden Tag, und deine Flamme wird größer. An Tag 7 lodert sie richtig auf.',
    obStreakHint: 'Wisch über die Tage',
    obStreakA11y: 'Serie: {n} {n|Tag|Tage}. Ändere den Wert, um die Flamme wachsen zu sehen',
    obPushTitle: 'Wähle, wann wir dir das Wort des Tages schicken',
    obPushText: 'Du kannst das jederzeit in den Einstellungen ändern.',
    obPushMorning: 'Morgens',
    obPushDay: 'Mittags',
    obPushEvening: 'Abends',
    onbWidgetTitle: 'Ein Wort bei jedem Blick aufs Handy',
    onbWidgetText: 'Füge ein Widget hinzu: das Wort des Tages, deine Wörter und deine Serie, direkt auf dem Home-Bildschirm.',
    onbWidgetTry: 'Probier’s aus: Tippe auf „Übersetzung zeigen“',
    onbWidgetAgain: 'Zeig mir nochmal, wie es geht',
    obDemoTitle: 'Scanne Dinge um dich herum: in 10 Sekunden übersetzt',
    obDemoBeat1: 'Richte die Kamera auf einen Gegenstand',
    obDemoBeat2: 'LinguaLens schneidet ihn aus und benennt ihn',
    obDemoBeat3: 'Das Wort landet in deiner Wortliste',
    obDemoFinal: 'Jetzt du. Es dauert 10 Sekunden',
    obDemoWords: 'Meine Wörter',
    obDemoReplay: 'Nochmal',
    obDemoTry: 'Ausprobieren',
    obDemoUsed: 'Der kostenlose Scan auf diesem iPhone ist schon verbraucht. Mit Pro scannst du, so viel du willst.',
    obDemoSkipHint: 'Tippe, um zum Ende zu springen',
    obDemoA11y: 'Demo: Die Kamera sieht eine Tasse auf dem Tisch. LinguaLens schneidet sie als Sticker mit dem Wort {word} ({tr}) aus, und das Wort landet in „Meine Wörter“. Dann die ganze Szene: Über Laptop, Pflanze und Notizbuch erscheinen ihre Wörter.',
    obCelebrateTitle: 'Dein erstes Wort!',
    obCelebrateStreak: 'Deine Serie hat begonnen: Tag 1',
    obCommitGoal: 'Erstes Ziel: 7 Tage in Folge',
    obCommitKeep: 'Weiter halten…',
    obCommitAgain: 'Halte, bis der Ring voll ist',
    obCommitDoneSub: 'Bis morgen, dann mit einem neuen Wort',
    opwFirstWordText: 'Dein kostenloser Scan ist schon in deiner Wortliste. Mit Pro scannst du, so viel du willst.',
    replayOnb: 'Einführung noch einmal durchgehen',
    // ── Onboarding 4.0 ──
    obLangLearnLabel: 'Die Sprache, die ich lerne',
    obNameNice: 'Schön, dich kennenzulernen, {name}!',
    levelName1: 'Anfänger',
    levelName2: 'Grundkenntnisse',
    levelName3: 'Mittelstufe',
    levelName4: 'Sicher unterwegs',
    levelName5: 'Fortgeschritten',
    obPlanLevel: 'Niveau: {cefr} · {name}',
    obWodTitle: 'Was ist das Wort des Tages?',
    obWodText: 'Jeden Tag sucht Lingo ein nützliches Wort für dich aus, mit Übersetzung, Aussprache und Beispiel. Passend zu deinen Zielen und deinem Niveau.',
    obDemoBeat4: 'Oder eine ganze Szene mit allen Wörtern auf einmal',
  },

  es: {
    // ── W3 ──
    ob3Hello: '¡Hola! Soy Lingo.',
    ob3HookTitle: 'Seré tu guía en el mundo de los idiomas',
    obLangTitle: '¿Qué idioma estás aprendiendo?',
    obLangSearch: 'Buscar idioma',
    obLangSearchClear: 'Borrar búsqueda',
    obLangPopular: 'Populares',
    obLangAll: 'Todos los idiomas',
    obLangNone: 'Todavía no tenemos este idioma',
    obLangIsNative: 'tu lengua materna',
    obLangIsTarget: 'el idioma que aprendes',
    obLangCheer: '{lang}: ¡muy buena elección!',
    obNativeLabel: 'Mi lengua materna',
    obNativeChange: 'Cambiar',
    obNativeTitle: 'Tu lengua materna',
    obNativeText: 'Las traducciones y los ejemplos estarán en este idioma.',
    obNativePhone: 'del teléfono',
    obNativeA11y: 'Lengua materna: {lang}. Cambiar',
    langName_en: 'Inglés',
    langName_uk: 'Ucraniano',
    langName_de: 'Alemán',
    langName_es: 'Español',
    langName_fr: 'Francés',
    langName_it: 'Italiano',
    langName_pl: 'Polaco',
    langName_pt: 'Portugués',
    langName_nl: 'Neerlandés',
    langName_cs: 'Checo',
    langName_sk: 'Eslovaco',
    langName_ro: 'Rumano',
    langName_hu: 'Húngaro',
    langName_el: 'Griego',
    langName_sv: 'Sueco',
    langName_da: 'Danés',
    langName_no: 'Noruego',
    langName_fi: 'Finés',
    langName_tr: 'Turco',
    langName_ru: 'Ruso',
    langName_ja: 'Japonés',
    langName_ko: 'Coreano',
    langName_zh: 'Chino',
    langName_ar: 'Árabe',
    langName_he: 'Hebreo',
    langName_hi: 'Hindi',
    langName_th: 'Tailandés',
    langName_vi: 'Vietnamita',
    langName_id: 'Indonesio',
    // варіанти мов (src/langVariants.js): регіон у дужках після назви мови
    langRegion_us: 'EE. UU.',
    langRegion_gb: 'Reino Unido',
    langRegion_es: 'España',
    langRegion_latam: 'Latinoamérica',
    pfGoalsTitleLang: '¿Para qué aprendes {lang}?',
    pfGoalsTitleLangName: '{name}, ¿para qué aprendes {lang}?',
    obBuildTitle: 'Preparando tu plan…',
    obBuildLang: '{lang} · nivel {cefr}',
    obBuildTopics: 'Temas: {topics}',
    obBuildWod: 'Eligiendo tu palabra del día…',
    obBuildWodDone: 'Tu palabra del día está lista',
    obPlanToday: 'Tu palabra de hoy',
    obStreakTitle: 'Aprende cada día y haz crecer tu llama',
    obStreakText: 'Aprende cada día y tu llama crecerá. El día 7 se enciende de verdad.',
    obStreakHint: 'Desliza por los días',
    obStreakA11y: 'Racha: {n} {n|día|días}. Ajusta para ver crecer la llama',
    obPushTitle: 'Elige cuándo te enviamos la palabra del día',
    obPushText: 'Puedes cambiarlo cuando quieras en Ajustes.',
    obPushMorning: 'Mañana',
    obPushDay: 'Tarde',
    obPushEvening: 'Noche',
    onbWidgetTitle: 'Una palabra cada vez que miras el móvil',
    onbWidgetText: 'Añade un widget: la palabra del día, tus palabras y tu racha, directamente en la pantalla de inicio.',
    onbWidgetTry: 'Pruébalo: toca «Ver traducción»',
    onbWidgetAgain: 'Enséñame otra vez cómo añadirlo',
    obDemoTitle: 'Escanea lo que te rodea y obtén la traducción en 10 segundos',
    obDemoBeat1: 'Apunta la cámara a un objeto',
    obDemoBeat2: 'LinguaLens lo recorta y le pone nombre',
    obDemoBeat3: 'La palabra llega a tu lista',
    obDemoFinal: 'Ahora tú: son 10 segundos',
    obDemoWords: 'Mis palabras',
    obDemoReplay: 'Repetir',
    obDemoTry: 'Probar',
    obDemoUsed: 'El escaneo gratis de este iPhone ya se ha usado; con Pro, escanea todo lo que quieras.',
    obDemoSkipHint: 'Toca para saltar al final',
    obDemoA11y: 'Demostración: la cámara ve una taza sobre la mesa. LinguaLens la recorta como pegatina con la palabra {word} ({tr}), y la palabra llega a «Mis palabras». Después, toda la escena: sobre el portátil, la planta y el cuaderno aparecen sus palabras.',
    obCelebrateTitle: '¡Tu primera palabra!',
    obCelebrateStreak: 'Tu racha ha empezado: día 1',
    obCommitGoal: 'Primer objetivo: 7 días seguidos',
    obCommitKeep: 'Sigue pulsando…',
    obCommitAgain: 'Mantén hasta completar el círculo',
    obCommitDoneSub: 'Hasta mañana, con una palabra nueva',
    opwFirstWordText: 'Tu escaneo gratis ya está en tu lista de palabras. Con Pro, escanea todo lo que quieras.',
    replayOnb: 'Repetir la introducción',
    // ── Onboarding 4.0 ──
    obLangLearnLabel: 'El idioma que aprendo',
    obNameNice: '¡Un placer conocerte, {name}!',
    levelName1: 'Principiante',
    levelName2: 'Básico',
    levelName3: 'Intermedio',
    levelName4: 'Con soltura',
    levelName5: 'Avanzado',
    obPlanLevel: 'Nivel: {cefr} · {name}',
    obWodTitle: '¿Qué es la palabra del día?',
    obWodText: 'Cada día Lingo elige para ti una palabra útil, con traducción, pronunciación y un ejemplo. A la medida de tus objetivos y tu nivel.',
    obDemoBeat4: 'O una escena entera, con todas las palabras a la vez',
  },
};
