// Рядки v1.3 потоку W3 (онбординг 3.0 і секція «Розробка»). Власник — W3; інші потоки
// цей файл лише читають.
//
// Правила тексту — у шапці src/i18n.js: однаковий набір ключів у чотирьох
// мовах, множини {n|…}, «» / “” / „“, ʼ в українській, без емодзі й капсу.
// Ключ, який уже є в іншому фрагменті, не дублюємо. Наявний ключ із
// src/i18n.js перекриваємо, лише назвавши його в OVERRIDES (стереже
// __tests__/i18nFragments.test.js). Кожна мова — окремий блок у цьому ж
// форматі (`  en: {` … `  },`): тест шукає в ньому ключі-дублікати.
//
// Тексти серії (жаринка, «так тримати», «тиждень») — спільні, з
// src/strings/shared.js. Тексти секції «Розробка» — лише українською в
// коді: вона існує тільки в dev-збірці.
//
// Перекриваємо: obPushTitle — крок сповіщень тепер питає годину;
// replayOnb — повтор із Параметрів тепер справжнє знайомство.
export const OVERRIDES = ['obPushTitle', 'replayOnb'];

export default {
  en: {
    // ── W3 ──
    // вітання
    ob3Hello: 'Hi! I’m Lingo.',
    ob3HookTitle: 'Learn a language from the things around you',
    ob3HookText: 'Point your camera at anything and get the word with a translation, pronunciation and an example. I’ll help you keep going.',
    // яку мову вчиш
    obLangTitle: 'Which language are you learning?',
    obLangText: 'You can change it any time in Settings.',
    obLangSearch: 'Search languages',
    obLangSearchClear: 'Clear search',
    obLangPopular: 'Popular',
    obLangAll: 'All languages',
    obLangNone: 'We don’t have this language yet',
    obLangIsNative: 'your translation language',
    obLangIsTarget: 'the language you’re learning',
    obLangCheer: '{lang} — great choice!',
    obNativeLabel: 'Translate into',
    obNativeChange: 'Change',
    obNativeTitle: 'Which language should we translate into?',
    obNativeText: 'Translations and examples will be in this language. The app itself follows your phone’s language.',
    obNativePhone: 'from your phone',
    obNativeA11y: 'Translate into: {lang}. Change',
    langName_en: 'English',
    langName_uk: 'Ukrainian',
    langName_de: 'German',
    langName_es: 'Spanish',
    langName_fr: 'French',
    langName_it: 'Italian',
    langName_pl: 'Polish',
    langName_pt: 'Portuguese',
    langName_nl: 'Dutch',
    langName_cs: 'Czech',
    langName_sk: 'Slovak',
    langName_ro: 'Romanian',
    langName_hu: 'Hungarian',
    langName_el: 'Greek',
    langName_sv: 'Swedish',
    langName_da: 'Danish',
    langName_no: 'Norwegian',
    langName_fi: 'Finnish',
    langName_tr: 'Turkish',
    langName_ru: 'Russian',
    langName_ja: 'Japanese',
    langName_ko: 'Korean',
    langName_zh: 'Chinese',
    langName_ar: 'Arabic',
    langName_he: 'Hebrew',
    langName_hi: 'Hindi',
    langName_th: 'Thai',
    langName_vi: 'Vietnamese',
    langName_id: 'Indonesian',
    // цілі з мовою
    pfGoalsTitleLang: 'Why are you learning {lang}?',
    pfGoalsTitleLangName: '{name}, why are you learning {lang}?',
    // план
    obBuildTitle: 'Putting your plan together…',
    obBuildLang: '{lang} · level {cefr}',
    obBuildTopics: 'Topics: {topics}',
    obBuildWod: 'Picking your word of the day…',
    obBuildWodDone: 'Your word of the day is ready',
    obPlanToday: 'Your word for today',
    // серія
    obStreakTitle: 'One word a day keeps your streak growing',
    obStreakText: 'Learn every day and your flame grows. On day 7 it really catches fire.',
    obStreakHint: 'Slide across the days',
    obStreakA11y: 'Streak: {n} {n|day|days}. Adjust to watch the flame grow',
    // сповіщення
    obPushTitle: 'When suits you best?',
    obPushText: 'One notification a day — a new word with a translation. It keeps your streak alive too.',
    obPushMorning: 'Morning',
    obPushDay: 'Afternoon',
    obPushEvening: 'Evening',
    // віджети
    onbWidgetTitle: 'A word every time you pick up your phone',
    onbWidgetText: 'Add a widget: the word of the day, your words and your streak — right on your Home Screen.',
    onbWidgetTry: 'Try it: tap “Show translation”',
    onbWidgetAgain: 'Show me again how to add it',
    // демо
    obDemoTitle: 'Here’s how it works',
    obDemoBeat1: 'Point your camera at anything',
    obDemoBeat2: 'LinguaLens cuts it out and names it',
    obDemoBeat3: 'The word lands in your list, and your streak lights up',
    obDemoFinal: 'Your turn — it takes 10 seconds',
    obDemoWords: 'My words',
    obDemoStreak: 'Streak: 1 day',
    obDemoReplay: 'Replay',
    obDemoTry: 'Try it',
    obDemoUsed: 'The free scan on this iPhone has been used — with Pro, scan as much as you like.',
    obDemoSkipHint: 'Tap to skip to the end',
    obDemoA11y: 'Demo: the camera sees a mug on a desk. LinguaLens cuts it out as a sticker with the word {word} — {tr}. The word lands in My words, and the streak flame lights up.',
    // свято першого слова
    obCelebrateTitle: 'Your first word!',
    obCelebrateStreak: 'Your streak has started: day 1',
    // обіцянка
    obCommitGoal: 'First goal: 7 days in a row',
    obCommitKeep: 'Keep holding…',
    obCommitAgain: 'Hold until the ring is full',
    obCommitDoneSub: 'See you tomorrow for a new word',
    // пейвол онбордингу з наліпкою людини
    opwFirstWordText: 'Your free scan is already in your word list. With Pro, scan as much as you like.',
    // Параметри
    replayOnb: 'Go through the intro again',
  },

  uk: {
    // ── W3 ──
    ob3Hello: 'Привіт! Я Lingo.',
    ob3HookTitle: 'Вчи мову з речей навколо',
    ob3HookText: 'Наведи камеру на будь-що — і отримай слово з перекладом, вимовою й прикладом. А я допоможу не закинути.',
    obLangTitle: 'Яку мову вчиш?',
    obLangText: 'Змінити можна будь-коли в Параметрах.',
    obLangSearch: 'Пошук мови',
    obLangSearchClear: 'Очистити пошук',
    obLangPopular: 'Популярні',
    obLangAll: 'Усі мови',
    obLangNone: 'Такої мови поки немає',
    obLangIsNative: 'твоя мова перекладу',
    obLangIsTarget: 'мова, яку вчиш',
    obLangCheer: '{lang} — чудовий вибір!',
    obNativeLabel: 'Перекладати на',
    obNativeChange: 'Змінити',
    obNativeTitle: 'Якою мовою перекладати?',
    obNativeText: 'Цією мовою будуть переклади й приклади. Інтерфейс — мовою телефона.',
    obNativePhone: 'з телефона',
    obNativeA11y: 'Перекладати на: {lang}. Змінити',
    langName_en: 'Англійська',
    langName_uk: 'Українська',
    langName_de: 'Німецька',
    langName_es: 'Іспанська',
    langName_fr: 'Французька',
    langName_it: 'Італійська',
    langName_pl: 'Польська',
    langName_pt: 'Португальська',
    langName_nl: 'Нідерландська',
    langName_cs: 'Чеська',
    langName_sk: 'Словацька',
    langName_ro: 'Румунська',
    langName_hu: 'Угорська',
    langName_el: 'Грецька',
    langName_sv: 'Шведська',
    langName_da: 'Данська',
    langName_no: 'Норвезька',
    langName_fi: 'Фінська',
    langName_tr: 'Турецька',
    langName_ru: 'Російська',
    langName_ja: 'Японська',
    langName_ko: 'Корейська',
    langName_zh: 'Китайська',
    langName_ar: 'Арабська',
    langName_he: 'Іврит',
    langName_hi: 'Гінді',
    langName_th: 'Тайська',
    langName_vi: 'Вʼєтнамська',
    langName_id: 'Індонезійська',
    pfGoalsTitleLang: 'Для чого ти вчиш {lang}?',
    pfGoalsTitleLangName: '{name}, для чого ти вчиш {lang}?',
    obBuildTitle: 'Складаємо твій план…',
    obBuildLang: '{lang} · рівень {cefr}',
    obBuildTopics: 'Теми: {topics}',
    obBuildWod: 'Підбираємо слово дня…',
    obBuildWodDone: 'Слово дня готове',
    obPlanToday: 'Твоє слово на сьогодні',
    obStreakTitle: 'Одне слово на день — і серія росте',
    obStreakText: 'Вчись щодня, і вогник ставатиме більшим. На 7-й день він розгориться по-справжньому.',
    obStreakHint: 'Проведи пальцем по днях',
    obStreakA11y: 'Серія: {n} {n|день|дні|днів}. Гортай, щоб побачити, як росте вогник',
    obPushTitle: 'Коли тобі зручно вчитись?',
    obPushText: 'Одне сповіщення на день — нове слово з перекладом. Так і серія не згасне.',
    obPushMorning: 'Зранку',
    obPushDay: 'Удень',
    obPushEvening: 'Увечері',
    onbWidgetTitle: 'Слова — щоразу, як береш телефон',
    onbWidgetText: 'Додай віджет: слово дня, твої слова й серія — просто на головному екрані.',
    onbWidgetTry: 'Спробуй: торкнись «Показати переклад»',
    onbWidgetAgain: 'Покажи ще раз, як додати',
    obDemoTitle: 'Ось як це працює',
    obDemoBeat1: 'Наведи камеру на будь-що',
    obDemoBeat2: 'LinguaLens вирізає предмет і називає його',
    obDemoBeat3: 'Слово летить у твій словник, а серія спалахує',
    obDemoFinal: 'Тепер ти — це 10 секунд',
    obDemoWords: 'Мої слова',
    obDemoStreak: 'Серія: 1 день',
    obDemoReplay: 'Ще раз',
    obDemoTry: 'Спробувати',
    obDemoUsed: 'Безкоштовний скан на цьому iPhone уже використано — з Pro скануй скільки хочеш.',
    obDemoSkipHint: 'Торкнись, щоб одразу побачити фінал',
    obDemoA11y: 'Демонстрація: камера бачить чашку на столі. LinguaLens вирізає її як наліпку зі словом {word} — {tr}. Слово потрапляє в «Мої слова», і запалюється вогник серії.',
    obCelebrateTitle: 'Перше слово — твоє!',
    obCelebrateStreak: 'Серія почалась: 1 день',
    obCommitGoal: 'Перша ціль — 7 днів поспіль',
    obCommitKeep: 'Ще трохи…',
    obCommitAgain: 'Тримай до кінця кола',
    obCommitDoneSub: 'До завтра — по нове слово',
    opwFirstWordText: 'Твій безкоштовний скан — уже в словнику. З Pro скануй скільки хочеш.',
    replayOnb: 'Пройти знайомство ще раз',
  },

  de: {
    // ── W3 ──
    ob3Hello: 'Hallo! Ich bin Lingo.',
    ob3HookTitle: 'Lerne eine Sprache mit den Dingen um dich herum',
    ob3HookText: 'Richte die Kamera auf irgendetwas und bekomm das Wort mit Übersetzung, Aussprache und Beispiel. Ich helfe dir dranzubleiben.',
    obLangTitle: 'Welche Sprache lernst du?',
    obLangText: 'Du kannst sie jederzeit in den Einstellungen ändern.',
    obLangSearch: 'Sprache suchen',
    obLangSearchClear: 'Suche löschen',
    obLangPopular: 'Beliebt',
    obLangAll: 'Alle Sprachen',
    obLangNone: 'Diese Sprache gibt es noch nicht',
    obLangIsNative: 'deine Übersetzungssprache',
    obLangIsTarget: 'die Sprache, die du lernst',
    obLangCheer: '{lang} — gute Wahl!',
    obNativeLabel: 'Übersetzen in',
    obNativeChange: 'Ändern',
    obNativeTitle: 'In welche Sprache sollen wir übersetzen?',
    obNativeText: 'In dieser Sprache bekommst du Übersetzungen und Beispiele. Die App selbst folgt der Sprache deines Telefons.',
    obNativePhone: 'vom Telefon',
    obNativeA11y: 'Übersetzen in: {lang}. Ändern',
    langName_en: 'Englisch',
    langName_uk: 'Ukrainisch',
    langName_de: 'Deutsch',
    langName_es: 'Spanisch',
    langName_fr: 'Französisch',
    langName_it: 'Italienisch',
    langName_pl: 'Polnisch',
    langName_pt: 'Portugiesisch',
    langName_nl: 'Niederländisch',
    langName_cs: 'Tschechisch',
    langName_sk: 'Slowakisch',
    langName_ro: 'Rumänisch',
    langName_hu: 'Ungarisch',
    langName_el: 'Griechisch',
    langName_sv: 'Schwedisch',
    langName_da: 'Dänisch',
    langName_no: 'Norwegisch',
    langName_fi: 'Finnisch',
    langName_tr: 'Türkisch',
    langName_ru: 'Russisch',
    langName_ja: 'Japanisch',
    langName_ko: 'Koreanisch',
    langName_zh: 'Chinesisch',
    langName_ar: 'Arabisch',
    langName_he: 'Hebräisch',
    langName_hi: 'Hindi',
    langName_th: 'Thailändisch',
    langName_vi: 'Vietnamesisch',
    langName_id: 'Indonesisch',
    pfGoalsTitleLang: 'Warum lernst du {lang}?',
    pfGoalsTitleLangName: '{name}, warum lernst du {lang}?',
    obBuildTitle: 'Wir stellen deinen Plan zusammen…',
    obBuildLang: '{lang} · Niveau {cefr}',
    obBuildTopics: 'Themen: {topics}',
    obBuildWod: 'Wir suchen dein Wort des Tages aus…',
    obBuildWodDone: 'Dein Wort des Tages ist bereit',
    obPlanToday: 'Dein Wort für heute',
    obStreakTitle: 'Ein Wort am Tag — und deine Serie wächst',
    obStreakText: 'Lerne jeden Tag, und deine Flamme wird größer. An Tag 7 lodert sie richtig auf.',
    obStreakHint: 'Wisch über die Tage',
    obStreakA11y: 'Serie: {n} {n|Tag|Tage}. Ändere den Wert, um die Flamme wachsen zu sehen',
    obPushTitle: 'Wann passt es dir am besten?',
    obPushText: 'Eine Mitteilung am Tag — ein neues Wort mit Übersetzung. So bleibt auch deine Serie am Leben.',
    obPushMorning: 'Morgens',
    obPushDay: 'Mittags',
    obPushEvening: 'Abends',
    onbWidgetTitle: 'Ein Wort bei jedem Blick aufs Handy',
    onbWidgetText: 'Füge ein Widget hinzu: das Wort des Tages, deine Wörter und deine Serie — direkt auf dem Home-Bildschirm.',
    onbWidgetTry: 'Probier’s aus: Tippe auf „Übersetzung zeigen“',
    onbWidgetAgain: 'Zeig mir nochmal, wie es geht',
    obDemoTitle: 'So funktioniert’s',
    obDemoBeat1: 'Richte die Kamera auf irgendetwas',
    obDemoBeat2: 'LinguaLens schneidet es aus und benennt es',
    obDemoBeat3: 'Das Wort landet in deiner Liste, und deine Serie leuchtet auf',
    obDemoFinal: 'Jetzt du — es dauert 10 Sekunden',
    obDemoWords: 'Meine Wörter',
    obDemoStreak: 'Serie: 1 Tag',
    obDemoReplay: 'Nochmal',
    obDemoTry: 'Ausprobieren',
    obDemoUsed: 'Der kostenlose Scan auf diesem iPhone ist schon verbraucht — mit Pro scannst du so viel du willst.',
    obDemoSkipHint: 'Tippe, um zum Ende zu springen',
    obDemoA11y: 'Demo: Die Kamera sieht eine Tasse auf dem Tisch. LinguaLens schneidet sie als Sticker mit dem Wort {word} — {tr} aus. Das Wort landet in „Meine Wörter“, und die Flamme deiner Serie leuchtet auf.',
    obCelebrateTitle: 'Dein erstes Wort!',
    obCelebrateStreak: 'Deine Serie hat begonnen: Tag 1',
    obCommitGoal: 'Erstes Ziel: 7 Tage in Folge',
    obCommitKeep: 'Weiter halten…',
    obCommitAgain: 'Halte, bis der Ring voll ist',
    obCommitDoneSub: 'Bis morgen — für ein neues Wort',
    opwFirstWordText: 'Dein kostenloser Scan ist schon in deiner Wortliste. Mit Pro scannst du so viel du willst.',
    replayOnb: 'Einführung noch einmal durchgehen',
  },

  es: {
    // ── W3 ──
    ob3Hello: '¡Hola! Soy Lingo.',
    ob3HookTitle: 'Aprende un idioma con las cosas que te rodean',
    ob3HookText: 'Apunta la cámara a cualquier cosa y obtén la palabra con traducción, pronunciación y un ejemplo. Yo te ayudo a no dejarlo.',
    obLangTitle: '¿Qué idioma estás aprendiendo?',
    obLangText: 'Puedes cambiarlo cuando quieras en Ajustes.',
    obLangSearch: 'Buscar idioma',
    obLangSearchClear: 'Borrar búsqueda',
    obLangPopular: 'Populares',
    obLangAll: 'Todos los idiomas',
    obLangNone: 'Todavía no tenemos este idioma',
    obLangIsNative: 'tu idioma de traducción',
    obLangIsTarget: 'el idioma que aprendes',
    obLangCheer: '{lang}: ¡muy buena elección!',
    obNativeLabel: 'Traducir a',
    obNativeChange: 'Cambiar',
    obNativeTitle: '¿A qué idioma traducimos?',
    obNativeText: 'Las traducciones y los ejemplos estarán en este idioma. La app sigue el idioma de tu teléfono.',
    obNativePhone: 'del teléfono',
    obNativeA11y: 'Traducir a: {lang}. Cambiar',
    langName_en: 'Inglés',
    langName_uk: 'Ucraniano',
    langName_de: 'Alemán',
    langName_es: 'Español',
    langName_fr: 'Francés',
    langName_it: 'Italiano',
    langName_pl: 'Polaco',
    langName_pt: 'Portugués',
    langName_nl: 'Neerlandés',
    langName_cs: 'Checo',
    langName_sk: 'Eslovaco',
    langName_ro: 'Rumano',
    langName_hu: 'Húngaro',
    langName_el: 'Griego',
    langName_sv: 'Sueco',
    langName_da: 'Danés',
    langName_no: 'Noruego',
    langName_fi: 'Finés',
    langName_tr: 'Turco',
    langName_ru: 'Ruso',
    langName_ja: 'Japonés',
    langName_ko: 'Coreano',
    langName_zh: 'Chino',
    langName_ar: 'Árabe',
    langName_he: 'Hebreo',
    langName_hi: 'Hindi',
    langName_th: 'Tailandés',
    langName_vi: 'Vietnamita',
    langName_id: 'Indonesio',
    pfGoalsTitleLang: '¿Para qué aprendes {lang}?',
    pfGoalsTitleLangName: '{name}, ¿para qué aprendes {lang}?',
    obBuildTitle: 'Preparando tu plan…',
    obBuildLang: '{lang} · nivel {cefr}',
    obBuildTopics: 'Temas: {topics}',
    obBuildWod: 'Eligiendo tu palabra del día…',
    obBuildWodDone: 'Tu palabra del día está lista',
    obPlanToday: 'Tu palabra de hoy',
    obStreakTitle: 'Una palabra al día y tu racha crece',
    obStreakText: 'Aprende cada día y tu llama crecerá. El día 7 se enciende de verdad.',
    obStreakHint: 'Desliza por los días',
    obStreakA11y: 'Racha: {n} {n|día|días}. Ajusta para ver crecer la llama',
    obPushTitle: '¿Cuándo te viene mejor?',
    obPushText: 'Una notificación al día: una palabra nueva con su traducción. Así tu racha tampoco se apaga.',
    obPushMorning: 'Mañana',
    obPushDay: 'Tarde',
    obPushEvening: 'Noche',
    onbWidgetTitle: 'Una palabra cada vez que miras el móvil',
    onbWidgetText: 'Añade un widget: la palabra del día, tus palabras y tu racha, directamente en la pantalla de inicio.',
    onbWidgetTry: 'Pruébalo: toca «Ver traducción»',
    onbWidgetAgain: 'Enséñame otra vez cómo añadirlo',
    obDemoTitle: 'Así funciona',
    obDemoBeat1: 'Apunta la cámara a cualquier cosa',
    obDemoBeat2: 'LinguaLens lo recorta y le pone nombre',
    obDemoBeat3: 'La palabra llega a tu lista y tu racha se enciende',
    obDemoFinal: 'Ahora tú: son 10 segundos',
    obDemoWords: 'Mis palabras',
    obDemoStreak: 'Racha: 1 día',
    obDemoReplay: 'Repetir',
    obDemoTry: 'Probar',
    obDemoUsed: 'El escaneo gratis de este iPhone ya se ha usado; con Pro, escanea todo lo que quieras.',
    obDemoSkipHint: 'Toca para saltar al final',
    obDemoA11y: 'Demostración: la cámara ve una taza sobre la mesa. LinguaLens la recorta como pegatina con la palabra {word} — {tr}. La palabra llega a «Mis palabras» y se enciende la llama de la racha.',
    obCelebrateTitle: '¡Tu primera palabra!',
    obCelebrateStreak: 'Tu racha ha empezado: día 1',
    obCommitGoal: 'Primer objetivo: 7 días seguidos',
    obCommitKeep: 'Sigue pulsando…',
    obCommitAgain: 'Mantén hasta completar el círculo',
    obCommitDoneSub: 'Hasta mañana, con una palabra nueva',
    opwFirstWordText: 'Tu escaneo gratis ya está en tu lista de palabras. Con Pro, escanea todo lo que quieras.',
    replayOnb: 'Repetir la introducción',
  },
};
