// Рядки v1.3 потоку W2 (віджети й Pro «кілька слів на день»). Власник — W2; інші потоки
// цей файл лише читають.
//
// Правила тексту — у шапці src/i18n.js: однаковий набір ключів у чотирьох
// мовах, множини {n|…}, «» / “” / „“, ʼ в українській, без емодзі й капсу.
// Ключ, який уже є в іншому фрагменті, не дублюємо. Наявний ключ із
// src/i18n.js перекриваємо, лише назвавши його в OVERRIDES (стереже
// __tests__/i18nFragments.test.js). Кожна мова — окремий блок у цьому ж
// форматі (`  en: {` … `  },`): тест шукає в ньому ключі-дублікати.
export const OVERRIDES = [];

export default {
  en: {
    // ── W2 ──
    // віджети (розширення iOS не має перекладів — тексти йдуть у props)
    widgetReveal: 'Translation',
    widgetRevealLong: 'Show translation',
    widgetSentence: 'In a sentence',
    widgetThisWeek: 'This week',
    widgetToday: 'Today',
    widgetSlot: '{i} of {n}',
    widgetNextAt: 'Next word at {t}',
    widgetWordsTitle: 'My words',
    widgetDue: '{n} to review',
    widgetLearned: '{k} of {n} learned',
    widgetReview: 'Review',
    widgetUpNext: 'Up next',
    widgetWordsEmpty: 'Your words will rotate here',
    widgetWordsEmptyHint: 'Save today’s word to get started',
    widgetStreakTitle: 'Streak',
    // серії немає: «0 days» замість «0 days in a row»
    widgetDays: '{n|day|days}',
    // «як додати віджет» — коротко, під три колонки
    widgetHow1: 'Touch and hold an empty spot',
    widgetHow2: 'Edit → Add Widget',
    widgetHow3: 'Find LinguaLens',
    widgetHowA11y: 'How to add a widget: touch and hold an empty spot on the Home Screen, tap Edit, then Add Widget, and find LinguaLens.',
    widgetPreviewA11y: 'Widget preview',
    // Параметри → «Віджети»
    settingsWidgets: 'Widgets',
    settingsHideTr: 'Hide translation until tapped',
    settingsHideTrHint: 'On the Lock Screen the translation always shows',
    settingsHowWidget: 'How to add a widget',
    widgetFastClock: 'Fast widget time',
    widgetFastClockHint: 'An hour becomes a minute: word rotation, streak phases and Pro words in a few minutes. Development builds only.',
    // Параметри → «Слово дня»: Pro, кілька слів на день
    wodPerDay: 'Words a day',
    wodPerDayHint: 'Each word arrives at its own time, as a notification and in the widget',
    wodPerDayPro: '3 and 5 words a day come with Pro',
    wodSlotN: 'Word {n}',
    wodSlotA11y: 'Word {n} at {t}',
    // картка слова дня в «Навчанні» (Pro)
    wodSlotOf: 'Word {i} of {n}',
    wodNextLocked: 'The next word opens at {t}',
  },

  uk: {
    // ── W2 ──
    widgetReveal: 'Переклад',
    widgetRevealLong: 'Показати переклад',
    widgetSentence: 'У реченні',
    widgetThisWeek: 'Цього тижня',
    widgetToday: 'Сьогодні',
    widgetSlot: '{i} з {n}',
    widgetNextAt: 'Наступне слово о {t}',
    widgetWordsTitle: 'Мої слова',
    widgetDue: '{n} на повторення',
    widgetLearned: 'Вивчено {k} з {n}',
    widgetReview: 'Повторити',
    widgetUpNext: 'Далі',
    widgetWordsEmpty: 'Тут крутитимуться твої слова',
    widgetWordsEmptyHint: 'Збережи слово дня, і почнемо',
    widgetStreakTitle: 'Серія',
    widgetDays: '{n|день|дні|днів}',
    widgetHow1: 'Затисни порожнє місце',
    widgetHow2: '«Редагувати» → «Додати віджет»',
    widgetHow3: 'Знайди LinguaLens',
    widgetHowA11y: 'Як додати віджет: затисни порожнє місце на головному екрані, торкнись «Редагувати», потім «Додати віджет» і знайди LinguaLens.',
    widgetPreviewA11y: 'Попередній перегляд віджетів',
    settingsWidgets: 'Віджети',
    settingsHideTr: 'Ховати переклад до дотику',
    settingsHideTrHint: 'На екрані блокування переклад видно завжди',
    settingsHowWidget: 'Як додати віджет',
    widgetFastClock: 'Прискорений час віджетів',
    widgetFastClockHint: 'Година стає хвилиною: ротація слів, фази серії й слова Pro за кілька хвилин. Лише збірка для розробки.',
    wodPerDay: 'Слів на день',
    wodPerDayHint: 'Кожне слово приходить о своїй годині: сповіщенням і у віджеті',
    wodPerDayPro: '3 і 5 слів на день із Pro',
    wodSlotN: 'Слово {n}',
    wodSlotA11y: 'Слово {n} о {t}',
    wodSlotOf: 'Слово {i} з {n}',
    wodNextLocked: 'Наступне слово відкриється о {t}',
  },

  de: {
    // ── W2 ──
    widgetReveal: 'Übersetzung',
    widgetRevealLong: 'Übersetzung zeigen',
    widgetSentence: 'Im Satz',
    widgetThisWeek: 'Diese Woche',
    widgetToday: 'Heute',
    widgetSlot: '{i} von {n}',
    widgetNextAt: 'Nächstes Wort um {t}',
    widgetWordsTitle: 'Meine Wörter',
    widgetDue: '{n} zum Wiederholen',
    widgetLearned: '{k} von {n} gelernt',
    widgetReview: 'Wiederholen',
    widgetUpNext: 'Als Nächstes',
    widgetWordsEmpty: 'Hier wechseln sich deine Wörter ab',
    widgetWordsEmptyHint: 'Speichere das Wort des Tages, dann geht’s los',
    widgetStreakTitle: 'Serie',
    widgetDays: '{n|Tag|Tage}',
    widgetHow1: 'Leere Stelle gedrückt halten',
    widgetHow2: '„Bearbeiten“ → „Widget hinzufügen“',
    widgetHow3: 'LinguaLens suchen',
    widgetHowA11y: 'So fügst du ein Widget hinzu: Halte eine leere Stelle auf dem Home-Bildschirm gedrückt, tippe auf „Bearbeiten“, dann auf „Widget hinzufügen“ und suche LinguaLens.',
    widgetPreviewA11y: 'Vorschau der Widgets',
    settingsWidgets: 'Widgets',
    settingsHideTr: 'Übersetzung erst nach Tippen zeigen',
    settingsHideTrHint: 'Auf dem Sperrbildschirm ist die Übersetzung immer sichtbar',
    settingsHowWidget: 'So fügst du ein Widget hinzu',
    widgetFastClock: 'Schnelle Widget-Zeit',
    widgetFastClockHint: 'Aus einer Stunde wird eine Minute: Wortwechsel, Serienphasen und Pro-Wörter in wenigen Minuten. Nur in Entwickler-Builds.',
    wodPerDay: 'Wörter pro Tag',
    wodPerDayHint: 'Jedes Wort kommt zu seiner Uhrzeit, als Mitteilung und im Widget',
    wodPerDayPro: '3 und 5 Wörter pro Tag gibt es mit Pro',
    wodSlotN: 'Wort {n}',
    wodSlotA11y: 'Wort {n} um {t}',
    wodSlotOf: 'Wort {i} von {n}',
    wodNextLocked: 'Das nächste Wort öffnet sich um {t}',
  },

  es: {
    // ── W2 ──
    widgetReveal: 'Traducción',
    widgetRevealLong: 'Ver traducción',
    widgetSentence: 'En una frase',
    widgetThisWeek: 'Esta semana',
    widgetToday: 'Hoy',
    widgetSlot: '{i} de {n}',
    widgetNextAt: 'Siguiente palabra a las {t}',
    widgetWordsTitle: 'Mis palabras',
    widgetDue: '{n} por repasar',
    widgetLearned: '{k} de {n} aprendidas',
    widgetReview: 'Repasar',
    widgetUpNext: 'A continuación',
    widgetWordsEmpty: 'Aquí irán rotando tus palabras',
    widgetWordsEmptyHint: 'Guarda la palabra del día y empezamos',
    widgetStreakTitle: 'Racha',
    widgetDays: '{n|día|días}',
    widgetHow1: 'Mantén pulsado un espacio vacío',
    widgetHow2: 'Editar → Añadir widget',
    widgetHow3: 'Busca LinguaLens',
    widgetHowA11y: 'Cómo añadir un widget: mantén pulsado un espacio vacío de la pantalla de inicio, toca Editar, luego Añadir widget, y busca LinguaLens.',
    widgetPreviewA11y: 'Vista previa de los widgets',
    settingsWidgets: 'Widgets',
    settingsHideTr: 'Ocultar la traducción hasta tocar',
    settingsHideTrHint: 'En la pantalla de bloqueo la traducción siempre se ve',
    settingsHowWidget: 'Cómo añadir un widget',
    widgetFastClock: 'Tiempo rápido de widgets',
    widgetFastClockHint: 'Una hora pasa a ser un minuto: rotación de palabras, fases de la racha y palabras Pro en pocos minutos. Solo en compilaciones de desarrollo.',
    wodPerDay: 'Palabras al día',
    wodPerDayHint: 'Cada palabra llega a su hora: como notificación y en el widget',
    wodPerDayPro: '3 y 5 palabras al día vienen con Pro',
    wodSlotN: 'Palabra {n}',
    wodSlotA11y: 'Palabra {n} a las {t}',
    wodSlotOf: 'Palabra {i} de {n}',
    wodNextLocked: 'La siguiente palabra se abre a las {t}',
  },
};
