// Назви й описи віджетів у галереї iOS мовою телефона (розтяжка S1,
// widgets.md §11).
//
// expo-widgets пише displayName і description у Swift рядковими
// літералами: .configurationDisplayName("Word of the Day"). SwiftUI бере
// такий літерал як LocalizedStringKey, тож досить покласти в розширення
// <мова>.lproj/Localizable.strings з перекладами — і галерея заговорить
// мовою телефона. Сам expo-widgets таких файлів не робить, тому цей плагін:
//   • бере переклади з locales/widgets.json (ключ — англійський текст з
//     app.json; мова без перекладу ключа отримує англійський);
//   • кладе ios/ExpoWidgetsTarget/<мова>.lproj/Localizable.strings;
//   • додає в таргет ExpoWidgetsTarget групу Localizable.strings і фазу
//     Resources (у таргета її немає), а мови — в knownRegions проєкту.
//
// Порядок: у app.json плагін стоїть ПЕРЕД "expo-widgets". Моди
// виконуються у зворотному порядку, тож наш мод Xcode-проєкту бачить уже
// створений таргет. Файли пишемо в тому ж моді (після всіх «небезпечних»
// модів), бо expo-widgets перед цим перестворює теку таргета. Не знайшли
// таргет — лише попередження: назви лишаються англійськими, збірка не
// ламається. Запасний варіант — прибрати рядок з app.json.
const fs = require('fs');
const path = require('path');
const { WarningAggregator, withXcodeProject } = require('expo/config-plugins');

const TARGET = 'ExpoWidgetsTarget';
const TABLE = 'Localizable.strings';
const SOURCE = path.join('locales', 'widgets.json');

// Екранування для .strings: зворотна риска, лапки й перенос рядка.
function escapeStrings(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, '\\n');
}

// Англійські displayName і description віджетів з конфігу expo-widgets.
function widgetKeys(config) {
  const entry = (config.plugins || []).find((p) => Array.isArray(p) && p[0] === 'expo-widgets');
  const widgets = (entry && entry[1] && entry[1].widgets) || [];
  const keys = [];
  for (const w of widgets) {
    for (const k of [w.displayName, w.description]) {
      if (typeof k === 'string' && k && !keys.includes(k)) keys.push(k);
    }
  }
  return keys;
}

// → { мова: вміст Localizable.strings }. table — { мова: { ключ: переклад } }.
function stringsFiles(table, keys) {
  const out = {};
  for (const lang of Object.keys(table || {})) {
    if (!/^[a-z]{2,3}(-[A-Za-z0-9]+)?$/.test(lang)) continue;
    const t = table[lang] || {};
    const lines = keys.map((k) => {
      const v = typeof t[k] === 'string' && t[k] ? t[k] : k;
      return `"${escapeStrings(k)}" = "${escapeStrings(v)}";`;
    });
    out[lang] = `/* LinguaLens widgets: ${lang}. Generated by plugins/withWidgetLocalizations.js from locales/widgets.json. */\n\n${lines.join('\n')}\n`;
  }
  return out;
}

const unquote = (s) => String(s == null ? '' : s).replace(/^"(.*)"$/, '$1');
const entries = (section) => Object.keys(section || {}).filter((k) => !k.endsWith('_comment'));

// Додає в таргет групу Localizable.strings (по файлу на мову), фазу
// Resources і мови в knownRegions. Повторний виклик нічого не дублює.
// → false, якщо таргета чи його групи немає.
function addLocalizations(project, langs, target = TARGET) {
  const objects = project.hash.project.objects;
  const natives = objects.PBXNativeTarget || {};
  const targetUuid = entries(natives).find((k) => unquote(natives[k].name) === target);
  const groups = objects.PBXGroup || {};
  const groupUuid = entries(groups).find((k) => unquote(groups[k].name) === target || unquote(groups[k].path) === target);
  if (!targetUuid || !groupUuid) return false;
  const native = natives[targetUuid];
  const group = groups[groupUuid];
  group.children = group.children || [];

  objects.PBXVariantGroup = objects.PBXVariantGroup || {};
  objects.PBXFileReference = objects.PBXFileReference || {};
  objects.PBXBuildFile = objects.PBXBuildFile || {};
  objects.PBXResourcesBuildPhase = objects.PBXResourcesBuildPhase || {};
  const variants = objects.PBXVariantGroup;

  // група Localizable.strings у групі таргета
  let vgUuid = (group.children.find((c) => variants[c.value] && unquote(variants[c.value].name) === TABLE) || {}).value;
  if (!vgUuid) {
    vgUuid = project.generateUuid();
    variants[vgUuid] = { isa: 'PBXVariantGroup', children: [], name: TABLE, sourceTree: '"<group>"' };
    variants[vgUuid + '_comment'] = TABLE;
    group.children.push({ value: vgUuid, comment: TABLE });
  }
  const vg = variants[vgUuid];
  vg.children = vg.children || [];
  for (const lang of langs) {
    const file = `${lang}.lproj/${TABLE}`;
    const has = vg.children.some((c) => {
      const ref = objects.PBXFileReference[c.value];
      return ref && unquote(ref.path) === file;
    });
    if (has) continue;
    const ref = project.generateUuid();
    objects.PBXFileReference[ref] = {
      isa: 'PBXFileReference',
      lastKnownFileType: 'text.plist.strings',
      name: lang,
      path: `"${file}"`,
      sourceTree: '"<group>"',
    };
    objects.PBXFileReference[ref + '_comment'] = lang;
    vg.children.push({ value: ref, comment: lang });
  }

  // фаза Resources таргета (expo-widgets її не створює)
  native.buildPhases = native.buildPhases || [];
  let phaseUuid = (native.buildPhases.find((p) => objects.PBXResourcesBuildPhase[p.value]) || {}).value;
  if (!phaseUuid) {
    phaseUuid = project.generateUuid();
    objects.PBXResourcesBuildPhase[phaseUuid] = {
      isa: 'PBXResourcesBuildPhase',
      buildActionMask: 2147483647,
      files: [],
      runOnlyForDeploymentPostprocessing: 0,
    };
    objects.PBXResourcesBuildPhase[phaseUuid + '_comment'] = 'Resources';
    native.buildPhases.push({ value: phaseUuid, comment: 'Resources' });
  }
  const phase = objects.PBXResourcesBuildPhase[phaseUuid];
  phase.files = phase.files || [];
  const built = phase.files.some((f) => {
    const b = objects.PBXBuildFile[f.value];
    return b && b.fileRef === vgUuid;
  });
  if (!built) {
    const buildUuid = project.generateUuid();
    objects.PBXBuildFile[buildUuid] = { isa: 'PBXBuildFile', fileRef: vgUuid, fileRef_comment: TABLE };
    objects.PBXBuildFile[buildUuid + '_comment'] = `${TABLE} in Resources`;
    phase.files.push({ value: buildUuid, comment: `${TABLE} in Resources` });
  }

  // мови проєкту
  const projects = objects.PBXProject || {};
  for (const k of entries(projects)) {
    const regions = (projects[k].knownRegions = projects[k].knownRegions || []);
    for (const lang of langs) if (!regions.map(unquote).includes(lang)) regions.push(lang);
  }
  return true;
}

function readTable(projectRoot) {
  const file = path.join(projectRoot, SOURCE);
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

const withWidgetLocalizations = (config) =>
  withXcodeProject(config, (config) => {
    const { projectRoot, platformProjectRoot } = config.modRequest;
    let files;
    try {
      files = stringsFiles(readTable(projectRoot), widgetKeys(config));
    } catch (e) {
      WarningAggregator.addWarningIOS('withWidgetLocalizations', `${SOURCE}: ${e.message}. Widget names stay in English.`);
      return config;
    }
    const langs = Object.keys(files);
    if (!langs.length || !addLocalizations(config.modResults, langs)) {
      WarningAggregator.addWarningIOS(
        'withWidgetLocalizations',
        `${TARGET} not found: put "./plugins/withWidgetLocalizations" before "expo-widgets" in app.json. Widget names stay in English.`
      );
      return config;
    }
    for (const [lang, content] of Object.entries(files)) {
      const dir = path.join(platformProjectRoot, TARGET, `${lang}.lproj`);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, TABLE), content);
    }
    return config;
  });

module.exports = withWidgetLocalizations;
module.exports.escapeStrings = escapeStrings;
module.exports.widgetKeys = widgetKeys;
module.exports.stringsFiles = stringsFiles;
module.exports.addLocalizations = addLocalizations;
