module.exports = {
  key: 'academic',
  words: [
    // Університетське життя
    ['university', 1],
    ['college', 1, 'higher education institution'],
    ['campus', 1],
    ['professor', 1],
    ['lecturer', 1, 'university teacher who gives lectures'],
    ['dormitory', 1, 'student residence building'],
    ['semester', 1],
    ['library', 1],
    ['laboratory', 1],
    ['scholarship', 1, "financial award to pay for a student's studies"],
    ['graduation', 1, 'ceremony or act of completing a degree'],
    ['diploma', 1, 'document certifying completion of studies'],
    ['faculty', 2, 'university: teaching staff as a group'],
    ['department', 2, 'university: academic division for one subject'],
    ['dean', 2, 'university: head of a faculty or school'],
    ['tuition', 2, 'fees paid for university instruction'],
    ['admission', 2, 'acceptance into a university'],
    ['undergraduate', 2, "student working toward a bachelor's degree"],
    ['graduate student', 2, "student working toward a master's or PhD"],
    ['transcript', 2, "official record of a student's courses and grades"],
    ['extracurricular', 2, 'activities outside the regular curriculum'],
    ['alumni', 3, 'former students of a university'],

    // Навчальний процес
    ['course', 1, 'series of classes on one subject'],
    ['lecture', 1],
    ['seminar', 1, 'small class for discussion of a subject'],
    ['assignment', 1, 'task given to students'],
    ['degree', 1, 'academic qualification from a university'],
    ["bachelor's degree", 1],
    ["master's degree", 1],
    ['major', 1, 'main subject of a university degree'],
    ['graduate', 1, 'verb: complete a university degree'],
    ['syllabus', 2, 'outline of topics and requirements of a course'],
    ['curriculum', 2],
    ['coursework', 2, 'assignments during a course that count toward the grade'],
    ['minor', 2, 'secondary subject of a university degree'],
    ['elective', 2, 'optional course chosen by the student'],
    ['credit', 2, 'unit measuring completed coursework'],
    ['office hours', 2, 'time a professor is available to meet students'],
    ['PhD', 2, 'Doctor of Philosophy: highest research degree'],
    ['enroll', 2, 'register for a course or university'],
    ['prerequisite', 3, 'course required before taking another'],

    // Іспити та оцінювання
    ['exam', 1],
    ['final exam', 1],
    ['quiz', 1, 'short test in class'],
    ['grade', 1, 'mark given for academic work'],
    ['pass', 1, 'succeed in an exam'],
    ['fail', 1, 'not succeed in an exam'],
    ['deadline', 1],
    ['submit', 1, 'hand in work for evaluation'],
    ['feedback', 1, "comments on the quality of a student's work"],
    ['midterm', 2, 'exam held in the middle of a semester'],
    ['GPA', 2, 'grade point average'],
    ['retake', 2, 'take an exam again after failing'],
    ['assessment', 2, "evaluation of a student's knowledge"],
    ['extension', 2, 'extra time granted to submit work'],
    ['cheating', 2, 'using dishonest methods in an exam or assignment'],
    ['proctor', 3, 'person who supervises an exam'],
    ['rubric', 3, 'scoring guide listing grading criteria'],
    ['honors', 3, 'distinction for excellent academic results'],

    // Дослідження та методологія
    ['research', 1],
    ['research question', 1],
    ['theory', 1],
    ['experiment', 1],
    ['evidence', 1, 'facts or data that support a claim'],
    ['data', 1],
    ['survey', 1, 'research: questionnaire given to many people'],
    ['analysis', 1],
    ['observe', 1, 'research: watch carefully and record'],
    ['findings', 2, 'results of a research study'],
    ['hypothesis', 2],
    ['methodology', 2],
    ['questionnaire', 2],
    ['sample', 2, 'research: subset of a population that is studied'],
    ['variable', 2, 'research: factor that can change or be measured'],
    ['case study', 2],
    ['participant', 2, 'person taking part in a study'],
    ['bias', 2, 'systematic distortion in data or judgment'],
    ['limitation', 2, 'weakness or restriction of a study'],
    ['literature review', 2, 'survey of existing research on a topic'],
    ['primary source', 2, 'original document or first-hand evidence'],
    ['secondary source', 2, 'work that analyzes or discusses primary sources'],
    ['qualitative', 2],
    ['quantitative', 2],
    ['correlation', 3],
    ['causation', 3],
    ['control group', 3],
    ['framework', 3, 'theoretical structure guiding research'],
    ['research gap', 3, 'area not yet covered by existing research'],
    ['fieldwork', 3, 'research done on site rather than in a lab'],
    ['empirical', 3, 'based on observation or experiment'],
    ['reliability', 3, 'research: consistency of a measurement'],
    ['validity', 3, 'research: whether a study measures what it claims'],
    ['pilot study', 3, 'small preliminary study before the main one'],
    ['informed consent', 3, "research: participant's agreement after explanation"],
    ['ethics committee', 3, 'board that approves research involving people'],
    ['replicate', 3, 'repeat a study to confirm its results'],
    ['rigorous', 3, 'thorough and precise in method'],
    ['statistically significant', 3, 'unlikely to be due to chance'],

    // Академічне письмо
    ['essay', 1],
    ['thesis', 1, 'long research paper written for a degree'],
    ['research paper', 1],
    ['draft', 1, 'early version of a text'],
    ['outline', 1, 'plan of the main points of a text'],
    ['introduction', 1, 'opening section of an essay or paper'],
    ['conclusion', 1, 'final section summarizing a text'],
    ['dissertation', 2, 'long research work for a doctoral degree'],
    ['thesis statement', 2, 'sentence stating the main argument of an essay'],
    ['abstract', 2, 'short summary of a research paper'],
    ['summarize', 2],
    ['paraphrase', 2],
    ['proofread', 2],
    ['revise', 2, 'edit and improve a written text'],
    ['concise', 2],
    ['objective', 2, 'adjective: not influenced by personal opinion'],
    ['subjective', 2],
    ['appendix', 3, 'supplementary section at the end of a document'],
    ['topic sentence', 3, 'sentence stating the main idea of a paragraph'],
    ['coherent', 3, 'logically connected and easy to follow'],
    ['counterargument', 3],

    // Джерела та цитування
    ['source', 1, 'text or person providing information'],
    ['quotation', 1, 'exact words copied from a text or speaker'],
    ['reference', 1, 'mention of a source in academic work'],
    ['plagiarism', 1],
    ['journal', 1, 'academic periodical publishing research'],
    ['article', 1, 'academic: paper published in a journal'],
    ['citation', 2, 'reference to the source of an idea or quote'],
    ['cite', 2, 'mention a source as evidence or authority'],
    ['bibliography', 2],
    ['footnote', 2],
    ['academic integrity', 2],
    ['credible', 2, 'trustworthy and believable'],
    ['manuscript', 3, "author's text before publication"],
    ['in-text citation', 3, 'brief source reference inside the text'],
    ['attribute', 3, 'verb: credit an idea or quote to its source'],
    ['acknowledge', 3, "formally credit someone's contribution"],
    ['open access', 3, 'research freely available to read online'],
    ['impact factor', 3, 'measure of how often a journal is cited'],

    // Наукова спільнота та публікації
    ['researcher', 1],
    ['conference', 1],
    ['publish', 1],
    ['scholar', 2, 'expert who studies an academic subject'],
    ['academia', 2, 'the world of universities and research'],
    ['peer review', 2, 'evaluation of research by other experts'],
    ['coauthor', 2],
    ['contribution', 2, 'addition to knowledge in a field'],
    ['submission', 3, 'paper sent to a journal or conference'],
    ['discipline', 3, 'branch of knowledge, field of study'],
    ['interdisciplinary', 3],
    ['proceedings', 3, 'published collection of conference papers'],
    ['poster session', 3, 'conference: research presented on posters'],

    // Аргументація та аналіз
    ['argument', 1, 'reasoning supporting a claim'],
    ['analyze', 1],
    ['argue', 1, 'give reasons supporting an opinion'],
    ['relevant', 1],
    ['critical thinking', 2],
    ['claim', 2, 'statement presented as true'],
    ['assumption', 2],
    ['demonstrate', 2, 'show clearly with evidence'],
    ['interpret', 2, 'explain the meaning of data or a text'],
    ['justify', 2],
    ['contrast', 2, 'verb: show differences between things'],
    ['approach', 2, 'way of dealing with a problem'],
    ['theoretical', 2],
    ['contradict', 2],
    ['infer', 3],
    ['elaborate', 3, 'verb: explain in more detail'],
    ['implication', 3, 'possible consequence or conclusion'],
    ['critique', 3, 'detailed critical evaluation'],
    ['premise', 3, 'statement an argument is based on'],
    ['phenomenon', 3],
    ['criterion', 3],
    ['plausible', 3, 'seemingly reasonable or likely'],
    ['logical fallacy', 3],
    ['synthesize', 3, 'combine ideas from several sources'],
    ['ambiguous', 3],

    // Академічна кар'єра та фінансування
    ['application', 1, 'formal request for admission to a university'],
    ['supervisor', 2, "academic who guides a student's research"],
    ['grant', 2, 'money given to fund research'],
    ['research proposal', 2],
    ['thesis defense', 2, 'oral examination of a thesis'],
    ['exchange program', 2, 'period of study at a partner university abroad'],
    ['recommendation letter', 2],
    ['personal statement', 2, 'admission essay describing goals'],
    ['academic advisor', 2, 'staff member who helps students choose courses'],
    ['fellowship', 3, 'paid position for advanced study or research'],
    ['postdoc', 3, 'postdoctoral researcher: research job after a PhD'],
    ['tenure', 3, 'permanent academic position'],
    ['sabbatical', 3, 'paid leave from teaching for research'],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'university', 'college', 'campus', 'professor', 'lecturer', 'semester', 'laboratory', 'diploma',
    'course', 'lecture', 'seminar', 'credit', 'PhD', 'exam', 'final exam', 'deadline',
    'theory', 'experiment', 'analysis', 'hypothesis', 'methodology', 'correlation', 'control group', 'empirical',
    'ethics committee', 'essay', 'dissertation', 'objective', 'subjective', 'counterargument', 'plagiarism', 'journal',
    'citation', 'bibliography', 'impact factor', 'conference', 'publish', 'discipline', 'interdisciplinary', 'poster session',
    'argument', 'analyze', 'demonstrate', 'interpret', 'contrast', 'theoretical', 'critique', 'phenomenon',
    'criterion', 'synthesize', 'grant',
  ],
};
