module.exports = {
  key: 'design',
  words: [
    // Процес дизайну
    ['sketch', 1, 'quick rough drawing of an idea'],
    ['design brief', 1, 'document describing a design task and its goals'],
    ['mood board', 1, 'collage of images that sets a visual direction'],
    ['redesign', 2],
    ['iterate', 2, 'repeatedly refine a design based on feedback'],
    ['design thinking', 2, 'human-centered problem-solving method'],
    ['constraint', 2, 'design: a limit such as budget, time or platform'],
    ['empathize', 3, 'design thinking: understand the needs and feelings of users'],
    ['problem statement', 3, 'short description of the user problem to solve'],
    ['ideation', 3, 'generating many ideas in the early design stage'],

    // Дослідження користувачів
    ['user research', 1],
    ['persona', 1, 'fictional profile representing a typical user'],
    ['pain point', 1, 'a problem or frustration a user experiences'],
    ['user interview', 2],
    ['usability testing', 2],
    ['validate', 3, 'UX: test whether a design idea works for real users'],
    ['heat map', 3, 'UX: map showing where users click or look most'],
    ['card sorting', 3, 'method where users group topics into categories'],
    ['affinity diagram', 3, 'grouping research notes by theme to find patterns'],
    ['heuristic evaluation', 3, 'expert review of a UI against usability principles'],
    ['mental model', 3, 'how a user believes a system works'],

    // UX і взаємодія
    ['user experience', 1, 'UX: how a person feels when using a product'],
    ['user interface', 1, 'UI: screens and controls a person interacts with'],
    ['usability', 1, 'how easy a product is to use'],
    ['user flow', 1, 'path a user takes through screens to finish a task'],
    ['navigation', 1, 'UI: menus and links for moving through a product'],
    ['intuitive', 1, 'easy to understand without instructions'],
    ['user-friendly', 1],
    ['user journey', 2, 'all the steps a user takes to reach a goal'],
    ['onboarding', 2, 'first-time experience that introduces a product'],
    ['call to action', 2, 'element urging the user to act, e.g. a button'],
    ['seamless', 2, 'UX: smooth, without interruptions or extra effort'],
    ['friction', 3, 'UX: anything that slows the user down or adds effort'],
    ['user-centered', 3, 'focused on the needs of users'],
    ['information architecture', 3, 'organizing and labeling content so it is easy to find'],
    ['empty state', 3, 'screen shown when there is no content yet'],
    ['affordance', 3, 'visual clue showing how an element can be used'],
    ['microcopy', 3, 'short interface text such as button labels and hints'],
    ['progressive disclosure', 3, 'showing advanced options only when needed'],
    ['cognitive load', 3, 'mental effort needed to use an interface'],
    ['dark pattern', 3, 'UI trick that pushes users into choices they did not intend'],

    // Жести та дії користувача
    ['tap', 1, 'touchscreen: touch briefly with a finger'],
    ['scroll', 1, 'move content up or down on a screen'],
    ['swipe', 2, 'slide a finger across a touchscreen'],
    ['hover', 2, 'rest the pointer over an element without clicking'],
    ['drag', 2, 'move an item by holding and sliding the pointer'],
    ['interactive', 2],

    // Елементи інтерфейсу
    ['button', 1, 'UI: element the user clicks or taps to act'],
    ['icon', 1, 'small symbol representing an action or object'],
    ['menu', 1, 'UI: list of options or commands'],
    ['header', 1, 'UI: top section of a page or screen'],
    ['footer', 1, 'UI: bottom section of a page or screen'],
    ['tab', 1, 'UI: clickable label that switches between views'],
    ['input field', 1, 'UI: box where the user types text'],
    ['form', 1, 'UI: set of fields for entering data'],
    ['component', 1, 'reusable UI element, e.g. a button or card'],
    ['checkbox', 2],
    ['dropdown menu', 2, 'UI: list of options that opens on click'],
    ['modal window', 2, 'UI: window over the page that needs a response'],
    ['tooltip', 2, 'small hint shown when hovering over an element'],
    ['toggle', 2, 'UI: switch between two states, e.g. on/off'],
    ['card', 2, 'UI: box grouping related content, e.g. an image and text'],
    ['placeholder', 2, 'UI: hint text shown inside an empty field'],
    ['dark mode', 2, 'UI theme with light text on a dark background'],
    ['design system', 2, 'shared set of components, styles and rules'],
    ['breadcrumb', 3, 'UI: navigation trail showing where the page is'],
    ['design token', 3, 'named value for color, spacing, etc. in a design system'],

    // Прототипування та інструменти
    ['wireframe', 1, 'basic skeleton layout of a page or screen'],
    ['prototype', 1],
    ['mockup', 1, 'realistic static image of a finished design'],
    ['pixel', 1],
    ['layer', 1, 'graphics: one level stacked in an image or file'],
    ['resolution', 1, 'image: number of pixels it contains'],
    ['crop', 2, 'cut off unwanted outer parts of an image'],
    ['resize', 2],
    ['export', 2, 'design tools: save a file in another format'],
    ['asset', 2, 'design: image, icon or file used in a product'],
    ['low-fidelity', 2, 'design: rough and simple, far from the final look'],
    ['high-fidelity', 2, 'design: detailed and close to the final look'],
    ['vector', 2, 'graphics: image made of paths, scalable without quality loss'],
    ['pixelated', 2, 'image: blurry, with visible square pixels'],
    ['raster', 3, 'graphics: image made of pixels'],
    ['sitemap', 3, 'diagram of all pages of a website and their structure'],

    // Типографіка
    ['font', 1],
    ['font size', 1],
    ['typography', 1],
    ['bold', 1, 'text: thick, heavy letters'],
    ['italic', 1, 'text: slanted letters'],
    ['heading', 1, 'title text above a section'],
    ['typeface', 2, 'family of fonts sharing one design'],
    ['serif', 2, 'typography: small stroke at the ends of letters'],
    ['sans serif', 2, 'typeface without serifs'],
    ['font weight', 2, 'thickness of characters, e.g. light or bold'],
    ['line height', 2, 'vertical distance between lines of text'],
    ['readability', 2, 'how easy a text is to read'],
    ['kerning', 3, 'adjusting space between specific pairs of letters'],
    ['tracking', 3, 'typography: overall letter spacing in a block of text'],
    ['legible', 3, 'text: clear enough that each letter is easy to recognize'],
    ['justified', 3, 'text: aligned evenly to both left and right edges'],
    ['font pairing', 3, 'combining two typefaces that work well together'],

    // Колір
    ['palette', 1, 'set of colors used in a design'],
    ['contrast', 1, 'difference between light and dark or between colors'],
    ['gradient', 1, 'smooth transition from one color to another'],
    ['shadow', 2, 'design: dark area under an element that adds depth'],
    ['hue', 2, 'the basic color itself, e.g. red or blue'],
    ['saturation', 2, 'intensity or purity of a color'],
    ['shade', 2, 'color mixed with black; a darker version'],
    ['opacity', 2, 'how solid or see-through an element is'],
    ['accent color', 2, 'bright color used to highlight key elements'],
    ['vibrant', 2, 'color: bright and strong'],
    ['muted', 2, 'color: soft and less saturated'],
    ['monochrome', 2, 'using shades of a single color'],
    ['RGB', 2, 'red, green, blue: color model for screens'],
    ['hex code', 2, 'six-character code defining a color, e.g. #FF0000'],
    ['tint', 3, 'color mixed with white; a lighter version'],
    ['complementary color', 3, 'color opposite another on the color wheel'],
    ['CMYK', 3, 'cyan, magenta, yellow, black: color model for print'],

    // Композиція та макет
    ['layout', 1, 'arrangement of elements on a page or screen'],
    ['grid', 1, 'system of columns and rows used to arrange content'],
    ['white space', 1, 'empty space between and around elements'],
    ['spacing', 1, 'design: amount of space between elements'],
    ['margin', 1, 'design: space around the outside of an element'],
    ['align', 1, 'design: line up elements along an edge or center'],
    ['clean', 1, 'design: simple, tidy and free of clutter'],
    ['consistent', 2, 'design: following the same style everywhere'],
    ['padding', 2, 'space between the content of an element and its border'],
    ['visual hierarchy', 2, 'arranging elements to show order of importance'],
    ['balance', 2, 'design: even distribution of visual weight'],
    ['aspect ratio', 2, 'proportion of width to height, e.g. 16:9'],
    ['responsive', 2, 'adapting the layout to different screen sizes'],
    ['cluttered', 2, 'too full of elements, messy'],
    ['minimalist', 2, 'design: simple, with few elements'],
    ['gutter', 3, 'layout: space between grid columns'],
    ['breakpoint', 3, 'screen width at which the layout changes'],
    ['gestalt principles', 3, 'rules of how people perceive visual groups'],

    // Графічний дизайн і бренд
    ['logo', 1],
    ['branding', 1, 'creating the image and visual identity of a brand'],
    ['graphic design', 1],
    ['illustration', 1],
    ['brand identity', 2, 'visual elements that represent a brand'],
    ['style guide', 2, 'rules for using colors, fonts and styles consistently'],
    ['stroke', 2, 'graphics: line or border of a shape'],
    ['fill', 2, 'graphics: color inside a shape'],
    ['eye-catching', 2],
    ['visualize', 2, 'present data or ideas as images or charts'],
    ['motion design', 3, 'design of animated graphics'],
    ['retouch', 3, 'improve a photo by removing flaws'],
    ['cohesive', 3, 'design: parts fit together as a unified whole'],
    ['wordmark', 3, 'logo made only of the brand name in styled letters'],
    ['bleed', 3, 'print: area extended past the trim edge'],
    ['DPI', 3, 'dots per inch: print resolution'],

    // Доступність
    ['accessibility', 1, 'designing so people with disabilities can use it'],
    ['screen reader', 2, 'software that reads screen content aloud'],
    ['alt text', 2, 'text description of an image for screen readers'],
    ['color blindness', 2],
    ['inclusive design', 3, 'designing for people of all abilities and backgrounds'],
    ['contrast ratio', 3, 'measure of difference between text and background'],
    ['touch target', 3, 'area of a screen element that can be tapped'],
    ['WCAG', 3, 'Web Content Accessibility Guidelines'],
    ['focus state', 3, 'UI: highlight on the element selected via keyboard'],
    ['keyboard navigation', 3, 'using a site with the keyboard instead of a mouse'],

    // Робота з командою та клієнтами
    ['portfolio', 1, 'collection of the best work of a designer'],
    ['critique', 2, 'design: structured feedback session on work'],
    ['case study', 2, 'portfolio: detailed story of a design project'],
    ['revision', 2, 'changed version of a design made after feedback'],
    ['polish', 2, 'verb: refine the final details of a design'],
    ['handoff', 3, 'passing finished designs to developers'],
    ['annotation', 3, 'note explaining a design detail for developers'],
    ['pixel-perfect', 3, 'matching the design exactly, down to the pixel'],
  ],
};
