module.exports = {
  key: 'education',
  words: [
    // Школа та персонал
    ['teacher', 1],
    ['student', 1],
    ['principal', 1, 'school: head of a school'],
    ['kindergarten', 1, 'US: school year before first grade, ages 5 to 6'],
    ['elementary school', 1, 'primary school, ages about 6 to 11'],
    ['middle school', 1, 'school for ages about 11 to 14'],
    ['high school', 1, 'secondary school, ages about 14 to 18'],
    ['vice principal', 2, 'school: deputy head of a school'],
    ['substitute teacher', 2],
    ['teaching assistant', 2, 'school: adult who helps the teacher in class'],
    ['school counselor', 2, 'staff member who gives students guidance'],
    ['homeroom teacher', 2, 'teacher responsible for one class group'],
    ['grade level', 2, 'school year a student is in, e.g. fifth grade'],
    ['school board', 3, 'elected body that governs local schools'],

    // Урок і клас
    ['class', 1, 'group of students taught together'],
    ['classroom', 1],
    ['lesson', 1],
    ['lesson plan', 1],
    ['homework', 1],
    ['assignment', 1, 'school: task or piece of work given to students'],
    ['textbook', 1],
    ['worksheet', 1, 'sheet of exercises for students to complete'],
    ['handout', 1, 'printed sheet given to students in class'],
    ['group work', 1],
    ['pair work', 2],
    ['warm-up', 2, 'short activity at the start of a lesson'],
    ['icebreaker', 2, 'activity that helps a group get to know each other'],
    ['field trip', 2, 'school outing to a museum, farm, etc.'],
    ['recess', 2, 'school: break between lessons for play'],
    ['learning outcome', 3, 'skill or knowledge a student gains from a course'],

    // Навчальна програма
    ['curriculum', 1, 'all subjects and content taught in a school'],
    ['subject', 1, 'school: area of study such as math or history'],
    ['syllabus', 2, 'outline of topics and requirements for one course'],
    ['unit', 2, 'school: block of lessons on one topic'],
    ['core subject', 2, 'compulsory main subject like math or language'],
    ['literacy', 2, 'ability to read and write'],
    ['reading comprehension', 2],
    ['STEM', 2, 'science, technology, engineering and mathematics'],
    ['numeracy', 3, 'basic ability to work with numbers'],
    ['learning standard', 3, 'official statement of what students must know'],
    ['cross-curricular', 3, 'linking several school subjects together'],
    ['phonics', 3, 'method of teaching reading through letter sounds'],

    // Оцінювання
    ['test', 1, 'school: set of questions to check knowledge'],
    ['exam', 1, 'school: formal test of knowledge'],
    ['quiz', 1, 'short informal test'],
    ['grade', 1, "school: letter or number rating a student's work"],
    ['grading', 1, "process of assigning grades to students' work"],
    ['assessment', 1, 'education: evaluation of what students know'],
    ['score', 1, 'number of points achieved on a test'],
    ['feedback', 1, "comments on a student's work to help improve it"],
    ['pass', 1, 'exam: succeed in a test'],
    ['fail', 1, 'exam: not succeed in a test'],
    ['report card', 1, "document showing a student's grades"],
    ['rubric', 2, 'scoring guide with criteria for assessing work'],
    ['portfolio', 2, 'education: collection of student work over time'],
    ['standardized test', 2, 'same test given to all students and scored equally'],
    ['cheat', 2, 'act dishonestly on a test'],
    ['submit', 2, 'hand in work for assessment'],
    ['self-assessment', 3, 'students evaluating their own work'],
    ['peer assessment', 3, "students evaluating each other's work"],
    ['formative assessment', 3, 'ongoing assessment used to guide learning'],
    ['summative assessment', 3, 'assessment at the end of a unit or course'],
    ['learning gap', 3, 'difference between what students know and should know'],

    // Управління класом
    ['classroom management', 1],
    ['discipline', 1, 'school: control of student behavior'],
    ['behavior', 1],
    ['classroom rules', 1],
    ['seating chart', 2, 'plan showing where each student sits'],
    ['detention', 2, 'school: punishment of staying after hours'],
    ['consequence', 2, 'classroom: result of breaking a rule'],
    ['routine', 2, 'classroom: regular procedure students follow'],
    ['bullying', 2],
    ['attention span', 2],
    ['well-behaved', 2],
    ['disruptive', 2, 'causing disorder in class'],
    ['positive reinforcement', 3, 'rewarding good behavior so it happens again'],
    ['suspension', 3, 'school: temporary ban from attending'],
    ['expel', 3, 'school: permanently remove a student'],
    ['redirect', 3, 'classroom: guide a student back to the task'],

    // Методи викладання
    ['teaching method', 1],
    ['distance learning', 2, 'teaching done remotely, often online'],
    ['active learning', 2, 'teaching: students learn by doing and discussing'],
    ['role-play', 2, 'acting out a situation for practice'],
    ['hands-on', 2, 'involving practical activity'],
    ['pedagogy', 3, 'theory and practice of teaching'],
    ['instruction', 3, 'education: the act of teaching, e.g. classroom instruction'],
    ['scaffolding', 3, 'teaching: temporary support gradually removed'],
    ['flipped classroom', 3, 'students study content at home, practice in class'],
    ['blended learning', 3, 'mix of online and in-person teaching'],
    ['project-based learning', 3],
    ['student-centered', 3],
    ['learning management system', 3, 'software platform for online courses (LMS)'],
    ['differentiate', 3, "education: adapt teaching to each learner's needs"],

    // Інклюзія та підтримка учнів
    ['tutor', 1, 'private teacher for one or a few students'],
    ['special education', 2, 'teaching for students with disabilities'],
    ['inclusive education', 2, 'teaching all learners together in one class'],
    ['learning disability', 2],
    ['mentor', 2],
    ['struggle', 2, 'have difficulty learning or keeping up'],
    ['gifted', 3, 'education: having exceptional ability'],
    ['accommodation', 3, 'education: adjustment for a student with needs'],
    ['individualized education program', 3, 'IEP: tailored plan for a student with a disability'],
    ['early intervention', 3, 'support given as soon as a learning problem appears'],
    ['remedial', 3, 'meant to help students who are behind'],
    ['underperform', 3, 'achieve less than expected'],

    // Адміністрація школи
    ['attendance', 1, 'presence of students at school or class'],
    ['absence', 1, 'school: not being present at class'],
    ['term', 1, 'school: one part of the school year'],
    ['semester', 1],
    ['enrollment', 2, 'registering students at a school'],
    ['school district', 2, 'US: area whose public schools share one administration'],
    ['tardy', 3, 'US school: arriving late to class'],
    ['superintendent', 3, 'US: head of a school district'],
    ['accreditation', 3, 'official approval that a school meets standards'],
    ['child protection', 3, 'measures to keep children safe from harm'],

    // Співпраця з батьками
    ['parent-teacher conference', 2, 'meeting between teacher and parents about a child'],
    ['guardian', 2, 'person legally responsible for a child'],
    ['permission slip', 2, 'form parents sign to allow an activity'],
    ['open house', 2, 'school: event when families visit the school'],
    ['parental involvement', 3],
    ['parent-teacher association', 3, 'PTA: group of parents and teachers supporting a school'],

    // Професійний розвиток
    ['workload', 2],
    ['teacher training', 2],
    ['professional development', 2, 'ongoing training during a teaching career'],
    ['teaching license', 2, 'official permission to teach in schools'],
    ['lesson observation', 2, 'watching a lesson to evaluate the teaching'],
    ['burnout', 2],
    ['qualified', 2, 'having the training needed for a job, e.g. teaching'],
    ['reflective practice', 3, "thinking critically about one's own teaching"],

    // Дієслова та прикметники
    ['teach', 1],
    ['encourage', 1],
    ['praise', 1, 'express approval of a student'],
    ['correct', 1, "mark mistakes in a student's work"],
    ['review', 1, 'study material again before a test'],
    ['assess', 1, "evaluate a student's knowledge or skills"],
    ['supervise', 2, 'watch over students to keep order and safety'],
    ['memorize', 2],
    ['monitor', 2, 'watch and check progress over time'],
    ['motivate', 2],
    ['engage', 2, "hold students' attention and involvement"],
    ['collaborate', 2],
    ['brainstorm', 2, 'generate many ideas as a group'],
    ['attentive', 2],
    ['model', 3, 'teaching: demonstrate a skill for students to copy'],
    ['facilitate', 3, 'guide learning rather than lecture'],
    ['reinforce', 3, 'strengthen learning through practice'],
    ['age-appropriate', 3, 'suitable for a particular age group'],
    ['proficient', 3, 'highly skilled in a subject or language'],
    ['disengaged', 3, 'not interested or involved in learning'],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'student', 'class', 'STEM', 'test', 'exam', 'portfolio', 'standardized test', 'discipline',
    'routine', 'bullying', 'pedagogy', 'student-centered', 'differentiate', 'mentor', 'semester', 'accreditation',
    'qualified', 'reflective practice', 'monitor', 'motivate',
  ],
};
