module.exports = {
  key: 'engineering',
  words: [
    // Базові інженерні поняття
    ['engineer', 1],
    ['technician', 1],
    ['specification', 1],
    ['requirement', 1],
    ['maintenance', 1, 'regular work to keep equipment in good condition'],
    ['measure', 1, 'verb: find the size or amount of something'],
    ['design', 1, 'engineering verb: plan how a product will look and work'],
    ['force', 1, 'physics: push or pull acting on an object'],
    ['pressure', 1, 'physics: force applied per unit area'],
    ['efficiency', 2, 'ratio of useful output to the energy or effort put in'],
    ['adjust', 2, 'change slightly so that something works correctly'],
    ['reliability', 2],
    ['optimize', 2],
    ['troubleshoot', 2],
    ['friction', 2, 'physics: resistance between surfaces that rub together'],
    ['preventive maintenance', 2],
    ['compliant', 3, 'meeting the required rules and standards'],
    ['redundancy', 3, 'engineering: backup parts that take over if one fails'],
    ['service life', 3, 'how long a product is expected to work'],
    ['retrofit', 3, 'add new technology or parts to older equipment'],

    // Креслення та проєктування
    ['blueprint', 1, 'detailed technical drawing of a building or machine'],
    ['dimension', 1, 'a measurement such as length, width or height'],
    ['prototype', 1],
    ['scale', 2, 'drawing: ratio between drawing size and real size'],
    ['tolerance', 2, 'engineering: allowed variation from a specified size'],
    ['cross section', 2, 'view of an object as if cut straight through'],
    ['schematic', 2, 'simplified diagram of a system, e.g. an electrical circuit'],
    ['layout', 2, 'arrangement of equipment or parts in a space'],
    ['bill of materials', 3, 'list of all parts and quantities needed for a product'],
    ['clearance', 3, 'engineering: designed gap between two parts'],
    ['finite element analysis', 3],
    ['as-built drawing', 3, 'drawing showing how something was actually built'],

    // Матеріали та їхні властивості
    ['raw material', 1],
    ['steel', 1],
    ['aluminum', 1],
    ['concrete', 1, 'building material made of cement, sand, gravel and water'],
    ['strength', 1, 'ability of a material to resist force without breaking'],
    ['alloy', 2],
    ['corrosion', 2],
    ['durable', 2],
    ['insulation', 2, 'material that blocks heat, sound or electricity'],
    ['sheet metal', 2],
    ['heat-resistant', 2],
    ['waterproof', 2],
    ['brittle', 3],
    ['composite', 3, 'material made by combining two or more different materials'],
    ['ductile', 3],
    ['fatigue', 3, 'materials: weakening caused by repeated loading'],
    ['heat treatment', 3, 'heating and cooling metal to change its properties'],
    ['tensile strength', 3],
    ['stress', 3, 'engineering: internal force per unit area in a material'],

    // Механіка та машини
    ['gear', 1, 'toothed wheel that transfers motion'],
    ['pump', 1],
    ['bolt', 1, 'threaded metal pin used with a nut'],
    ['nut', 1, 'hardware: threaded part screwed onto a bolt'],
    ['spare part', 1],
    ['leak', 1, 'escape of liquid or gas through a hole or crack'],
    ['rotate', 1],
    ['valve', 2, 'device that controls the flow of liquid or gas'],
    ['shaft', 2, 'mechanics: rotating rod that transmits power'],
    ['bearing', 2, 'machine part that reduces friction around a rotating shaft'],
    ['seal', 2, 'mechanics: part that stops leaks between two surfaces'],
    ['torque', 2],
    ['vibration', 2],
    ['hydraulic', 2],
    ['tighten', 2, 'make a bolt or screw firmer by turning it'],
    ['mount', 2, 'verb: fix equipment firmly in position'],
    ['dismantle', 2],
    ['overheat', 2],
    ['wear', 2, 'engineering: gradual damage to parts from friction and use'],
    ['pneumatic', 3],
    ['actuator', 3],
    ['heat exchanger', 3],
    ['lubricate', 3],
    ['misalignment', 3, 'parts, e.g. shafts, not lined up correctly'],

    // Електротехніка
    ['voltage', 1],
    ['current', 1, 'electricity: flow of electric charge'],
    ['circuit', 1, 'closed path through which electricity flows'],
    ['motor', 1],
    ['sensor', 1],
    ['switch', 1, 'device that turns a circuit on or off'],
    ['wiring', 2, 'system of electrical wires in a building or machine'],
    ['resistance', 2, 'electricity: opposition to the flow of current'],
    ['fuse', 2, 'safety device that melts to break an overloaded circuit'],
    ['circuit breaker', 2],
    ['short circuit', 2],
    ['ground', 2, 'electricity: safety connection to the earth'],
    ['transformer', 2, 'device that changes the voltage of alternating current'],
    ['live', 2, 'electricity: carrying current, dangerous to touch'],
    ['conductor', 2, 'material that lets electricity flow through it'],
    ['disconnect', 2, 'cut equipment off from the power supply'],
    ['capacitor', 3],
    ['PLC', 3, 'programmable logic controller for industrial machines'],
    ['relay', 3, 'electrically operated switch'],
    ['three-phase', 3, 'electricity: power system using three alternating currents'],

    // Будівництво
    ['construction site', 1],
    ['foundation', 1, 'building: base that supports the whole structure'],
    ['beam', 1, 'long horizontal structural support'],
    ['load', 1, 'structures: weight or force a part must carry'],
    ['crane', 1, 'machine for lifting heavy loads'],
    ['column', 2, 'construction: vertical structural support'],
    ['load-bearing', 2],
    ['scaffolding', 2],
    ['contractor', 2, 'company or person hired to do construction work'],
    ['subcontractor', 2],
    ['structural', 2, 'relating to the load-bearing parts of a structure'],
    ['pour', 2, 'construction: place liquid concrete into a form'],
    ['excavate', 3, 'dig out earth, e.g. for a foundation'],
    ['building code', 3, 'official rules for safe building construction'],
    ['surveyor', 3, 'person who measures land for construction'],
    ['reinforcement', 3, 'steel bars placed in concrete to strengthen it'],
    ['slab', 3, 'flat concrete floor or roof element'],
    ['deflection', 3, 'amount a beam bends under load'],
    ['HVAC', 3, 'heating, ventilation and air conditioning'],

    // Виробництво
    ['manufacturing', 1],
    ['assembly line', 1],
    ['assemble', 1, 'put parts together to make a product'],
    ['equipment', 1],
    ['install', 1, 'put equipment in place and make it ready to use'],
    ['operator', 1, 'person who runs a machine'],
    ['plant', 2, 'industry: a factory or power station'],
    ['batch', 2, 'manufacturing: group of items produced together'],
    ['conveyor belt', 2],
    ['automation', 2],
    ['downtime', 2, 'time when a machine or line is not working'],
    ['bottleneck', 2, 'stage that slows down the whole process'],
    ['throughput', 3, 'amount processed in a given time'],
    ['yield', 3, 'manufacturing: share of good units produced'],
    ['lean manufacturing', 3, 'production method focused on cutting waste'],

    // Обробка матеріалів
    ['weld', 1, 'join metal parts by melting them together'],
    ['drill', 1, 'verb: make a hole with a rotating tool'],
    ['machining', 2, 'cutting metal to shape with machine tools'],
    ['mold', 2, 'hollow form used to give material its shape'],
    ['lathe', 3],
    ['milling', 3, 'machining with a rotating cutting tool'],
    ['casting', 3, 'pouring molten metal into a mold'],
    ['injection molding', 3],

    // Контроль якості
    ['quality control', 1],
    ['standard', 1, 'technical norm that products must meet, e.g. ISO'],
    ['inspect', 1],
    ['defect', 1, 'fault or flaw in a product'],
    ['failure', 1, 'engineering: when a part or system stops working'],
    ['accurate', 1],
    ['quality assurance', 2],
    ['precision', 2, 'how close repeated measurements are to each other'],
    ['deviation', 2],
    ['calibrate', 2],
    ['verify', 2],
    ['reject', 2, 'quality: refuse a part that fails inspection'],
    ['root cause', 3],
    ['gauge', 3, 'measuring instrument, e.g. a pressure gauge'],
    ['caliper', 3, 'tool for measuring thickness or diameter'],
    ['traceability', 3],
    ['nonconformity', 3, 'quality: failure to meet a specified requirement'],
    ['corrective action', 3],

    // Безпека праці
    ['safety', 1],
    ['hazard', 1],
    ['hard hat', 1],
    ['personal protective equipment', 1, 'PPE: helmets, gloves, goggles etc. worn for safety'],
    ['injury', 1],
    ['risk assessment', 2],
    ['flammable', 2],
    ['toxic', 2],
    ['evacuate', 2],
    ['overload', 2, 'put more load on something than it can safely take'],
    ['shut down', 2, 'turn off a machine or system completely'],
    ['emergency stop', 2],
    ['near miss', 3, 'safety: incident that almost caused harm'],
    ['lockout', 3, 'safety: locking a machine off before maintenance'],
    ['confined space', 3, 'safety: enclosed area with limited entry, e.g. a tank'],
  ],
};
