module.exports = {
  key: 'finance',
  words: [
    // Облік і фінансова звітність
    ['accounting', 1],
    ['accountant', 1],
    ['financial statement', 1],
    ['balance sheet', 1],
    ['income statement', 1, 'report of revenue, expenses and profit for a period'],
    ['fiscal year', 1],
    ['asset', 1, 'finance: something of value owned by a company'],
    ['liability', 1, 'accounting: a debt or financial obligation'],
    ['annual report', 2],
    ['equity', 2, 'finance: ownership value; assets minus liabilities'],
    ['bookkeeping', 2],
    ['cash flow statement', 2],
    ['ledger', 2, 'accounting: book recording all financial accounts'],
    ['journal entry', 2, 'accounting: record of a single transaction'],
    ['debit', 2, 'accounting: entry on the left side of an account'],
    ['accounts payable', 2, 'money a company owes to its suppliers'],
    ['accounts receivable', 2, 'money owed to a company by its customers'],
    ['depreciation', 2, 'accounting: spreading an asset cost over its useful life'],
    ['fixed asset', 2, 'long-term physical asset, e.g. buildings or equipment'],
    ['inventory', 2, 'business: stock of goods held for sale'],
    ['reconcile', 2, 'accounting: check that two sets of records match'],
    ['amortization', 3, 'accounting: gradual write-down of an intangible asset'],
    ['accrual', 3, 'accounting: income or expense recorded before cash moves'],
    ['goodwill', 3, 'accounting: intangible asset from an acquisition premium'],
    ['retained earnings', 3],
    ['write-off', 3, 'accounting: removal of an asset value from the books'],
    ['consolidate', 3, 'accounting: combine the accounts of a parent and subsidiaries'],

    // Доходи, витрати та прибуток
    ['revenue', 1, 'total income from sales before costs are deducted'],
    ['expense', 1],
    ['profit', 1],
    ['loss', 1, 'finance: negative financial result'],
    ['profitable', 1],
    ['net income', 2, 'profit after all expenses and taxes'],
    ['gross profit', 2],
    ['margin', 2, 'finance: profit as a percentage of revenue'],
    ['operating expenses', 2],
    ['overhead', 2, 'business: ongoing indirect operating costs'],
    ['earnings', 2, 'finance: company profit for a period'],
    ['fixed costs', 2],
    ['variable costs', 2],
    ['break-even point', 2],
    ['cost of sales', 3, 'direct cost of producing the goods sold'],
    ['EBITDA', 3, 'earnings before interest, taxes, depreciation, amortization'],

    // Грошові потоки та ліквідність
    ['cash', 1],
    ['cash flow', 1],
    ['liquidity', 2, 'finance: ease of converting assets into cash'],
    ['working capital', 2],
    ['insolvent', 3, 'finance: unable to pay debts'],
    ['burn rate', 3, 'startups: speed at which a company spends its cash'],
    ['free cash flow', 3, 'cash left after operating costs and capital spending'],
    ['recoup', 3, 'get back money that was spent or lost'],

    // Банківська справа
    ['checking account', 1, 'bank account for everyday payments (UK: current account)'],
    ['savings account', 1],
    ['deposit', 1, 'banking: money put into an account'],
    ['withdraw', 1, 'banking: take money out of an account'],
    ['balance', 1, 'banking: amount of money in an account'],
    ['transaction', 1],
    ['transfer', 1, 'banking: move money between accounts'],
    ['interest', 1, 'finance: money paid for the use of borrowed money'],
    ['interest rate', 1],
    ['exchange rate', 1],
    ['currency', 1],
    ['overdraft', 2],
    ['compound interest', 2],

    // Кредити та борги
    ['loan', 1],
    ['debt', 1],
    ['credit', 1, 'finance: money borrowed or available to borrow'],
    ['borrow', 1],
    ['lend', 1],
    ['owe', 1],
    ['mortgage', 2],
    ['collateral', 2, 'finance: asset pledged as security for a loan'],
    ['principal', 2, 'finance: original loan amount, excluding interest'],
    ['installment', 2, 'one of a series of regular payments'],
    ['credit score', 2],
    ['repay', 2],
    ['creditor', 2],
    ['default', 3, 'finance: failure to repay a debt'],
    ['maturity', 3, 'finance: date when a loan or bond is due'],
    ['refinance', 3],
    ['leverage', 3, 'finance: using borrowed money to increase returns'],
    ['line of credit', 3],
    ['creditworthy', 3],

    // Інвестиції та фондовий ринок
    ['investment', 1],
    ['invest', 1],
    ['share', 1, 'finance: unit of ownership in a company'],
    ['shareholder', 1],
    ['stock market', 1],
    ['return', 1, 'finance: gain or loss on an investment'],
    ['inflation', 1],
    ['dividend', 2],
    ['bond', 2, 'finance: debt security paying fixed interest'],
    ['portfolio', 2, 'finance: collection of investments'],
    ['fund', 2, 'finance: pool of money invested on behalf of others'],
    ['return on investment', 2, 'ROI: profit relative to the amount invested'],
    ['broker', 2, 'finance: agent who buys and sells securities'],
    ['volatile', 3, 'finance: prone to sharp price changes'],
    ['diversify', 3, 'finance: spread investments to reduce risk'],
    ['asset allocation', 3],
    ['capital gain', 3],
    ['securities', 3, 'finance: tradable assets such as stocks and bonds'],
    ['commodity', 3, 'finance: raw material traded on markets, e.g. oil'],
    ['derivative', 3, 'finance: contract whose value depends on another asset'],
    ['hedge', 3, 'finance: reduce risk with an offsetting investment'],
    ['appreciate', 3, 'finance: increase in value'],
    ['outperform', 3, 'finance: give better returns than a benchmark'],
    ['publicly traded', 3, 'with shares bought and sold on a stock exchange'],
    ['IPO', 3, 'initial public offering: first sale of shares to public'],
    ['market capitalization', 3],
    ['venture capital', 3],

    // Корпоративні фінанси
    ['capital', 1, 'finance: money or assets used to run a business'],
    ['funding', 1],
    ['raise', 2, 'finance: obtain money from investors or lenders'],
    ['valuation', 2],
    ['merger', 2],
    ['acquisition', 2, 'business: purchase of one company by another'],
    ['CFO', 2, 'chief financial officer'],
    ['bankruptcy', 2],
    ['subsidiary', 3, 'company controlled by a parent company'],
    ['due diligence', 3, 'investigation of a company before a deal'],
    ['net present value', 3, 'NPV: present value of expected future cash flows'],
    ['discount rate', 3, 'finance: rate used to value future cash flows today'],
    ['capital expenditure', 3, 'CapEx: spending on long-term assets like equipment'],
    ['restructure', 3, 'business: reorganize the debt or structure of a company'],
    ['liquidate', 3, 'finance: sell off assets for cash or close a company'],
    ['underwrite', 3, 'finance: guarantee or insure a loan, policy or share issue'],

    // Бюджет і планування
    ['budget', 1],
    ['forecast', 1, 'finance: prediction of future financial results'],
    ['allocate', 2, 'assign money or resources to a purpose'],
    ['overspend', 2],
    ['reserve', 2, 'finance: money set aside for future needs'],
    ['deficit', 2, 'amount by which spending exceeds income'],
    ['surplus', 2, 'amount by which income exceeds spending'],
    ['cost-effective', 2],
    ['variance', 3, 'budgeting: difference between planned and actual'],
    ['cost center', 3, 'department tracked for its costs, not profit'],

    // Податки
    ['tax', 1],
    ['income tax', 1],
    ['taxable', 2],
    ['tax-free', 2],
    ['pre-tax', 2],
    ['value-added tax', 2, 'VAT: tax added to the price at each stage of sale'],
    ['tax return', 2, 'official form reporting income and taxes owed'],
    ['deduction', 2, 'tax: amount subtracted from taxable income'],
    ['payroll', 2, 'company list of employees and wages paid'],
    ['gross', 2, 'finance: total amount before deductions'],
    ['net', 2, 'finance: amount remaining after deductions'],
    ['exemption', 3, 'tax: freedom from paying a tax'],
    ['tax-deductible', 3],
    ['withholding tax', 3, 'tax deducted at source, e.g. from wages or dividends'],
    ['tax bracket', 3],

    // Рахунки та платежі
    ['invoice', 1],
    ['payment', 1],
    ['fee', 1],
    ['charge', 1, 'ask a price for goods or services'],
    ['refund', 1],
    ['due date', 1, 'date by which a payment must be made'],
    ['receipt', 1, 'written proof of payment'],
    ['overdue', 2],
    ['purchase order', 2],
    ['quote', 2, 'business: estimated price offered for work'],
    ['reimburse', 2, 'pay back money someone spent on your behalf'],
    ['vendor', 2, 'supplier selling goods or services to a company'],
    ['outstanding', 2, 'finance: not yet paid'],
    ['settle', 2, 'finance: pay a debt or complete a transaction'],

    // Аудит, ризики та регулювання
    ['audit', 2, 'official review of financial records'],
    ['compliance', 2, 'following laws and regulations'],
    ['fraud', 2],
    ['risk management', 2],
    ['internal control', 3, 'accounting: process to prevent errors and fraud'],
    ['disclose', 3, 'finance: make required information public'],
    ['money laundering', 3],

    // Ключові дієслова та прикметники
    ['quarterly', 1],
    ['recurring', 2, 'finance: repeating regularly, e.g. recurring revenue'],
    ['fluctuate', 2],
    ['year-over-year', 3, 'compared with the same period of the previous year'],
    ['disburse', 3, 'pay out money from a fund'],
    ['lucrative', 3],
  ],
};
