module.exports = {
  key: 'general',
  words: [
    // дім, речі, одяг і матеріали
    ['window', 1],
    ['mirror', 1],
    ['pillow', 1],
    ['blanket', 1],
    ['curtain', 2],
    ['drawer', 2, 'sliding box in a piece of furniture'],
    ['shelf', 2],
    ['ceiling', 2],
    ['staircase', 2],
    ['doorbell', 2],
    ['kettle', 2],
    ['spoon', 1],
    ['napkin', 2],
    ['bucket', 2],
    ['broom', 2],
    ['towel', 1],
    ['candle', 2],
    ['lamp', 1],
    ['carpet', 2],
    ['basket', 1],
    ['wallet', 1],
    ['keychain', 2, 'small ring for holding keys'],
    ['umbrella', 1],
    ['backpack', 1],
    ['suitcase', 1],
    ['ladder', 2],
    ['toolbox', 2],
    ['hammer', 2],
    ['needle', 2, 'sewing needle'],
    ['rope', 2],
    ['clutter', 3, 'untidy mass of things'],
    ['sleeve', 2],
    ['collar', 2, 'part of a shirt around the neck'],
    ['button', 1, 'on clothing'],
    ['zipper', 2],
    ['pocket', 1],
    ['scarf', 1],
    ['glove', 1],
    ['sock', 1],
    ['boot', 1, 'footwear'],
    ['sandal', 2],
    ['jacket', 1],
    ['sweater', 1],
    ['skirt', 1],
    ['belt', 1],
    ['hat', 1],
    ['ribbon', 2],
    ['apron', 2],
    ['uniform', 2, 'noun: special clothes worn by a group'],
    ['costume', 2],
    ['jewelry', 2],
    ['leather', 2],
    ['silk', 2],
    ['wool', 2],
    ['velvet', 3],
    ['marble', 2, 'the stone'],
    ['clay', 2],
    ['copper', 2],
    ['steel', 2],
    ['bronze', 2, 'the metal'],
    ['glass', 1, 'the material'],
    ['plastic', 1, 'the material'],
    ['cardboard', 2],
    ['concrete', 2, 'building material'],
    ['rubber', 2, 'the material'],
    ['ceramics', 2, 'objects or material made of fired clay'],

    // їжа
    ['breakfast', 1],
    ['dessert', 1],
    ['pepper', 1, 'black pepper, the spice'],
    ['garlic', 1],
    ['honey', 1],
    ['flour', 2],
    ['butter', 1],
    ['cucumber', 1],
    ['pumpkin', 2],
    ['cherry', 1],
    ['walnut', 2],
    ['seafood', 2],
    ['noodles', 2],
    ['dough', 2, 'flour mixture for baking'],
    ['vinegar', 2],
    ['pear', 1],
    ['plum', 2],
    ['grape', 1],
    ['lettuce', 2],
    ['yogurt', 1],

    // природа, погода й тварини
    ['thunder', 2],
    ['lightning', 2],
    ['rainbow', 1],
    ['breeze', 2],
    ['puddle', 2],
    ['fog', 1],
    ['frost', 2],
    ['hail', 2, 'weather: balls of ice falling from the sky'],
    ['drizzle', 3],
    ['blizzard', 3],
    ['humidity', 3],
    ['drought', 3],
    ['sunrise', 1],
    ['sunset', 1],
    ['shadow', 1],
    ['wave', 1, 'ocean wave'],
    ['pebble', 3],
    ['branch', 1, 'tree branch'],
    ['root', 2, 'part of a plant'],
    ['seed', 2],
    ['blossom', 2],
    ['meadow', 3],
    ['valley', 2],
    ['cliff', 2],
    ['stream', 2, 'small river'],
    ['desert', 1, 'dry region with little rain'],
    ['glacier', 3],
    ['volcano', 2],
    ['island', 1],
    ['forest', 1],
    ['swamp', 3],
    ['cave', 1],
    ['hill', 1],
    ['shore', 2],
    ['harbor', 2],
    ['horizon', 2],
    ['squirrel', 2],
    ['hedgehog', 2],
    ['owl', 2],
    ['sparrow', 2],
    ['dolphin', 1],
    ['turtle', 2],
    ['butterfly', 1],
    ['ant', 1],
    ['bee', 1],
    ['spider', 1],
    ['fox', 2],
    ['wolf', 2],
    ['deer', 2],
    ['rabbit', 1],
    ['frog', 2],
    ['snail', 2],
    ['whale', 2],
    ['penguin', 2],
    ['eagle', 2],
    ['crab', 2],

    // місто, транспорт і дозвілля
    ['bridge', 1],
    ['tunnel', 2],
    ['sidewalk', 2],
    ['crosswalk', 2],
    ['traffic', 1, 'road traffic'],
    ['subway', 2, 'underground railway, metro'],
    ['ferry', 2],
    ['helicopter', 2],
    ['bicycle', 1],
    ['scooter', 2, 'kick scooter or e-scooter ridden standing'],
    ['parking lot', 1],
    ['fountain', 2],
    ['statue', 2],
    ['market', 1, 'place where goods are sold'],
    ['bakery', 1],
    ['pharmacy', 1],
    ['library', 1],
    ['museum', 1],
    ['stadium', 2],
    ['playground', 1],
    ['lighthouse', 2],
    ['castle', 2],
    ['chimney', 2],
    ['balcony', 2],
    ['fence', 2],
    ['gate', 2, 'door in a fence or wall'],
    ['roof', 1],
    ['wall', 1],
    ['floor', 1, 'surface of a room you walk on'],
    ['corner', 1],
    ['landmark', 3, 'famous building or place'],
    ['itinerary', 3],
    ['referee', 2],
    ['trophy', 2],
    ['goalkeeper', 2],
    ['racket', 2, 'tennis racket'],
    ['helmet', 2],
    ['sail', 2, 'noun: cloth that moves a boat'],
    ['tent', 1],
    ['campfire', 2],
    ['fishing', 1],
    ['puzzle', 1, 'game or problem that tests ingenuity'],

    // люди й тіло
    ['shoulder', 1],
    ['elbow', 2],
    ['wrist', 2],
    ['ankle', 2],
    ['thumb', 1],
    ['eyebrow', 2],
    ['eyelash', 2],
    ['cheek', 2, 'part of the face'],
    ['chin', 2],
    ['forehead', 2],
    ['neighbor', 1],
    ['stranger', 1],
    ['guest', 1],
    ['crowd', 1],
    ['twin', 1],
    ['grandparent', 1],
    ['colleague', 2],
    ['teammate', 2],
    ['audience', 2],
    ['volunteer', 2, 'noun: person who works without pay'],
    ['acquaintance', 3, 'person you know slightly'],
    ['upbringing', 3],

    // емоції й почуття
    ['courage', 2],
    ['patience', 1],
    ['curiosity', 2],
    ['kindness', 1],
    ['loneliness', 2],
    ['surprise', 1],
    ['relief', 2, 'feeling after worry ends'],
    ['pride', 2],
    ['envy', 3],
    ['gratitude', 2],
    ['confidence', 2, 'self-assurance'],
    ['doubt', 2],
    ['hope', 1],
    ['regret', 2],
    ['excitement', 1],
    ['boredom', 2],
    ['calmness', 2],
    ['anger', 1],
    ['joy', 1],
    ['fear', 1],
    ['anxiety', 2],
    ['grief', 3],
    ['nostalgia', 3],
    ['empathy', 3],
    ['compassion', 3],
    ['resentment', 3],
    ['vulnerability', 3, 'emotional openness to being hurt'],
    ['solitude', 3, 'state of being alone, often by choice'],
    ['contentment', 3, 'quiet satisfaction'],
    ['remorse', 3],
    ['melancholy', 3],
    ['overwhelmed', 3, 'emotionally overloaded'],
    ['ambivalent', 3],

    // характер і риси
    ['honest', 1],
    ['polite', 1],
    ['brave', 1],
    ['shy', 1],
    ['lazy', 1],
    ['generous', 2],
    ['stubborn', 2],
    ['reliable', 2],
    ['resilient', 3, 'quick to recover from difficulties'],
    ['meticulous', 3],
    ['diligent', 3],
    ['humble', 3, 'person: modest, not proud'],
    ['candid', 3, 'frank and honest'],
    ['blunt', 3, 'person: speaking very directly'],
    ['eloquent', 3],
    ['witty', 3],
    ['sincere', 3],
    ['persistent', 3],
    ['spontaneous', 3],
    ['versatile', 3, 'person: able to do many different things'],
    ['naive', 3],
    ['arrogant', 3],
    ['cautious', 3],
    ['assertive', 3],
    ['pragmatic', 3],
    ['cynical', 3],
    ['frugal', 3],
    ['trait', 3, 'personality characteristic'],
    ['integrity', 3, 'moral honesty'],
    ['dignity', 3],
    ['conscience', 3],
    ['perseverance', 3],

    // дії
    ['whisper', 2],
    ['shout', 1],
    ['giggle', 2],
    ['sigh', 2],
    ['yawn', 2],
    ['blink', 2],
    ['stretch', 2, 'verb: extend the body or limbs'],
    ['lean', 2, 'verb: rest the body against something'],
    ['crawl', 2],
    ['climb', 1],
    ['squeeze', 2],
    ['stir', 2, 'mix with a spoon'],
    ['pour', 2],
    ['fold', 2],
    ['wrap', 2, 'verb: cover in paper or cloth'],
    ['tie', 2, 'verb: fasten with a knot'],
    ['sweep', 2, 'clean with a broom'],
    ['polish', 2, 'verb: make shiny by rubbing'],
    ['measure', 2, 'verb: find the size or amount of'],
    ['carve', 3],
    ['wander', 2],
    ['chase', 2],
    ['hide', 1, 'verb: conceal'],
    ['search', 1],
    ['gather', 2],
    ['share', 1, 'verb: give part of something to others'],
    ['borrow', 1],
    ['lend', 1],
    ['repair', 1],
    ['build', 1, 'verb: construct something'],
    ['hesitate', 2],
    ['persuade', 2],
    ['exaggerate', 2],
    ['apologize', 2],
    ['forgive', 2],
    ['postpone', 2],
    ['pretend', 2],
    ['acknowledge', 3, 'accept or admit the truth of'],
    ['anticipate', 3, 'expect and prepare for'],
    ['cherish', 3],
    ['contemplate', 3],
    ['convey', 3, 'communicate an idea or feeling'],
    ['embrace', 3, 'accept willingly'],
    ['endure', 3],
    ['enhance', 3],
    ['evoke', 3],
    ['foster', 3, 'encourage the development of'],
    ['linger', 3],
    ['overcome', 2],
    ['perceive', 3],
    ['procrastinate', 3],
    ['reconcile', 3, 'restore friendly relations'],
    ['strive', 3],
    ['thrive', 3],
    ['undermine', 3, 'weaken gradually'],
    ['cultivate', 3, 'develop a skill, quality or habit'],
    ['cope', 2],
    ['savor', 3],
    ['grasp', 3, 'understand fully'],
    ['prioritize', 3],

    // ідеї й мислення
    ['memory', 1, 'ability to remember, a recollection'],
    ['dream', 1],
    ['habit', 1],
    ['promise', 1],
    ['secret', 1],
    ['mistake', 1],
    ['chance', 1, 'opportunity'],
    ['choice', 1],
    ['reason', 1, 'cause or explanation'],
    ['purpose', 2],
    ['silence', 1],
    ['rhythm', 2],
    ['balance', 2, 'state of stability or equilibrium'],
    ['freedom', 1],
    ['journey', 1],
    ['adventure', 1],
    ['tradition', 2],
    ['legend', 2],
    ['mystery', 2],
    ['wisdom', 2],
    ['nuance', 3],
    ['dilemma', 3],
    ['paradox', 3],
    ['perspective', 2, 'point of view'],
    ['insight', 3, 'deep understanding'],
    ['intuition', 3],
    ['coincidence', 2],
    ['legacy', 3, 'something handed down from the past'],
    ['irony', 3],
    ['momentum', 3, 'force or speed gained by progress'],
    ['obsession', 3],
    ['prejudice', 3],
    ['bias', 3, 'unfair preference or prejudice'],
    ['skepticism', 3],
    ['consensus', 3],
    ['controversy', 3],
    ['drawback', 3],
    ['misconception', 3],
    ['milestone', 3, 'important stage in development'],

    // ознаки й властивості
    ['awkward', 2, 'uncomfortable, embarrassing'],
    ['cozy', 2],
    ['ubiquitous', 3],
    ['ambiguous', 3],
    ['inevitable', 3],
    ['subtle', 3],
    ['vivid', 3],
    ['profound', 3],
    ['obscure', 3, 'little known'],
    ['vague', 2],
    ['tedious', 3],
    ['mundane', 3, 'dull and ordinary'],
    ['compelling', 3, 'convincing or captivating'],
    ['plausible', 3],
    ['feasible', 3],
    ['arbitrary', 3],
    ['elusive', 3, 'hard to find, catch or define'],
    ['intricate', 3],
    ['tangible', 3],
    ['abundant', 3],
    ['scarce', 3],
    ['concise', 3],
    ['thorough', 3],
    ['mediocre', 3],
    ['authentic', 3],
    ['relentless', 3],
    ['notorious', 3, 'famous for something bad'],
    ['bizarre', 2],
    ['unprecedented', 3],
    ['obsolete', 3],

    // час, навчання й робота
    ['dawn', 2],
    ['noon', 2],
    ['midnight', 1],
    ['weekend', 1],
    ['holiday', 1, 'day of celebration'],
    ['anniversary', 2],
    ['century', 1],
    ['decade', 2],
    ['moment', 1],
    ['deadline', 2],
    ['schedule', 1],
    ['delay', 2],
    ['pause', 2],
    ['routine', 2],
    ['season', 1, 'one of the four parts of the year'],
    ['spring', 1, 'season'],
    ['summer', 1],
    ['autumn', 1],
    ['winter', 1],
    ['birthday', 1],
    ['notebook', 1, 'paper notebook for writing'],
    ['eraser', 2],
    ['ruler', 2, 'measuring tool'],
    ['chalk', 2],
    ['homework', 1],
    ['lesson', 1],
    ['exam', 1],
    ['diploma', 2],
    ['lecture', 2],
    ['research', 2],
    ['meeting', 1],
    ['salary', 2],
    ['contract', 2],
    ['invoice', 3],
    ['client', 2],
    ['project', 1],
    ['goal', 1, 'aim, objective'],
    ['skill', 1],
    ['effort', 2],
    ['reward', 2],
    ['burnout', 3, 'exhaustion from overwork'],
    ['screen', 1],
    ['keyboard', 1],
    ['charger', 2],
    ['battery', 1],
    ['speaker', 2, 'loudspeaker'],
    ['headphones', 1],
    ['printer', 2],
    ['password', 1],
    ['folder', 2, 'container for files or documents'],
    ['download', 2],

    // кіно, книжки й розмови
    ['subtitles', 1],
    ['advice', 1],
    ['opinion', 1],
    ['novel', 1, 'noun: long fictional book'],
    ['character', 1, 'person in a story or film'],
    ['episode', 1, 'one part of a TV series'],
    ['plot', 2, 'storyline of a film or book'],
    ['sequel', 2],
    ['spoiler', 2, 'information that reveals the plot'],
    ['small talk', 2, 'light casual conversation'],
    ['gossip', 2],
    ['genre', 2],
    ['documentary', 2],
    ['review', 2, 'critical opinion of a film, book or product'],
    ['trailer', 2, 'short preview of a film'],
    ['villain', 2],
    ['compliment', 2],
    ['misunderstanding', 2],
    ['protagonist', 3],
    ['narrator', 3],
    ['memoir', 3],
    ['suspense', 3],
    ['satire', 3],
    ['masterpiece', 3],
    ['metaphor', 3],
    ['anecdote', 3],
    ['cliché', 3],
    ['sarcasm', 3],
    ['adaptation', 3, 'film or series based on a book'],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'lamp', 'sandal', 'sweater', 'uniform', 'bronze', 'plastic', 'ceramics', 'dessert',
    'yogurt', 'volcano', 'horizon', 'dolphin', 'penguin', 'crab', 'tunnel', 'helicopter',
    'fountain', 'statue', 'museum', 'stadium', 'balcony', 'trophy', 'racket', 'colleague',
    'volunteer', 'nostalgia', 'empathy', 'melancholy', 'spontaneous', 'naive', 'pragmatic', 'cynical',
    'prioritize', 'secret', 'chance', 'rhythm', 'balance', 'tradition', 'legend', 'nuance',
    'dilemma', 'paradox', 'intuition', 'irony', 'skepticism', 'consensus', 'authentic', 'weekend',
    'moment', 'deadline', 'pause', 'routine', 'season', 'exam', 'diploma', 'lecture',
    'contract', 'client', 'project', 'battery', 'printer', 'subtitles', 'episode', 'spoiler',
    'genre', 'documentary', 'trailer', 'compliment', 'memoir', 'satire', 'metaphor', 'cliché',
    'sarcasm', 'adaptation',
  ],
};
