module.exports = {
  key: 'hospitality',
  words: [
    // Бронювання та продажі
    ['reservation', 1, 'booking of a room or table in advance'],
    ['book', 1, 'verb: reserve a room, table or tour'],
    ['availability', 1, 'rooms or tables still free to book'],
    ['rate', 1, 'hotel: price charged for a room per night'],
    ['guest', 1],
    ['confirm', 1, 'make a booking definite'],
    ['cancel', 1, 'verb: call off a booking'],
    ['fully booked', 2, 'with no rooms or tables left'],
    ['walk-in', 2, 'guest who arrives without a reservation'],
    ['no-show', 2, 'guest who books but does not arrive'],
    ['deposit', 2, 'money paid in advance to secure a booking'],
    ['cancellation policy', 2],
    ['nonrefundable', 2, 'booking: money is not returned if canceled'],
    ['overbooking', 2, 'selling more rooms or seats than are available'],
    ['occupancy', 2, 'hotel: share of rooms that are filled'],
    ['upsell', 2, 'verb: sell a guest a more expensive option'],
    ['booking engine', 3, 'online system for direct reservations'],
    ['rack rate', 3, 'hotel: standard full price before discounts'],
    ['commission', 3, 'travel: fee paid to an agent or booking site per sale'],
    ['allotment', 3, 'block of rooms a hotel holds for a tour operator'],

    // Стійка реєстрації
    ['front desk', 1, 'hotel reception counter'],
    ['receptionist', 1, 'hotel: employee who works at the front desk'],
    ['lobby', 1, 'entrance hall of a hotel'],
    ['check-in', 1, 'hotel: registering a guest on arrival'],
    ['check-out', 1, 'hotel: settling the bill and leaving'],
    ['bill', 1, 'hotel or restaurant: statement of charges to pay'],
    ['room service', 1, 'meals delivered to a guest\'s room'],
    ['concierge', 2, 'hotel staff member who helps guests with requests'],
    ['upgrade', 2, 'verb: move a guest to a better room or class'],
    ['registration card', 3, 'hotel: form a guest fills in and signs at check-in'],
    ['valet parking', 3, 'service where staff park guests\' cars'],
    ['guest folio', 3, 'hotel: record of all charges of a guest'],
    ['night audit', 3, 'hotel: daily closing of accounts at night'],
    ['incidental charges', 3, 'extra costs like minibar or room service'],

    // Номери та хаускіпінг
    ['housekeeping', 1, 'hotel department that cleans rooms'],
    ['housekeeper', 1, 'hotel: staff member who cleans rooms'],
    ['single room', 1],
    ['double room', 1, 'room with one bed for two people'],
    ['linen', 1, 'hotel: sheets, pillowcases, towels and tablecloths'],
    ['twin room', 2, 'room with two separate beds'],
    ['suite', 2, 'large hotel room with a separate living area'],
    ['amenities', 2, 'extras such as a gym, pool or toiletries'],
    ['toiletries', 2, 'soap, shampoo and similar items for guests'],
    ['vacant', 2, 'hotel room: not occupied'],
    ['occupied', 2, 'hotel room: currently used by a guest'],
    ['inspect', 2, 'check that a cleaned room meets standards'],
    ['maintenance', 2, 'repair and upkeep of the building'],
    ['lost and found', 2, 'place where items guests leave behind are kept'],
    ['out of order', 2, 'hotel room or device: unusable due to a fault'],
    ['restock', 2, 'refill supplies such as minibar items'],
    ['turndown service', 3, 'evening preparation of a room for sleep'],
    ['connecting rooms', 3, 'two hotel rooms joined by an inner door'],

    // Обслуговування в ресторані
    ['menu', 1],
    ['waiter', 1],
    ['bartender', 1],
    ['serve', 1, 'bring food and drinks to guests'],
    ['order', 1, 'restaurant: food or drinks a guest asks for'],
    ['dish', 1, 'a prepared food item on a menu'],
    ['appetizer', 1, 'small dish served before the main course'],
    ['main course', 1],
    ['tip', 1, 'extra money given for good service'],
    ['recommend', 1, 'suggest a dish or option to a guest'],
    ['seat', 2, 'verb: show guests to their table'],
    ['host', 2, 'restaurant: staff member who greets and seats guests'],
    ['daily special', 2, 'restaurant: dish offered only on a particular day'],
    ['silverware', 2, 'knives, forks and spoons used at the table'],
    ['clear', 2, 'restaurant: remove used plates from a table'],
    ['dietary restrictions', 2, 'needs such as vegan, halal or gluten-free'],
    ['allergen', 2],
    ['cover', 3, 'restaurant: one guest served, counted per seat'],
    ['table turnover', 3, 'how often a table is reused during service'],
    ['tasting menu', 3, 'many small courses chosen by the chef'],
    ['corkage fee', 3, 'charge for serving wine that guests bring'],
    ['pair', 3, 'verb: match a wine or drink with a dish'],

    // Кухня
    ['chef', 1, 'professional cook in a restaurant kitchen'],
    ['recipe', 1],
    ['boil', 1, 'cook in hot bubbling water'],
    ['fry', 1, 'cook in hot oil'],
    ['grill', 1, 'verb: cook food over or under direct high heat'],
    ['head chef', 2, 'person in charge of the kitchen'],
    ['dishwasher', 2, 'kitchen worker who washes dishes and pots'],
    ['prep', 2, 'kitchen: preparing ingredients before service'],
    ['expiration date', 2, 'date after which food should not be used'],
    ['garnish', 2, 'verb: decorate a dish with a small edible item'],
    ['season', 2, 'cooking: add salt, pepper or spices'],
    ['well-done', 2, 'meat: cooked all the way through'],
    ['chop', 2, 'cut food into small pieces'],
    ['simmer', 2, 'cook gently just below boiling'],
    ['thaw', 2, 'let frozen food become soft before cooking'],
    ['sous chef', 3, 'second in command in a kitchen'],
    ['line cook', 3, 'cook responsible for one kitchen station'],
    ['cross-contamination', 3, 'spread of bacteria or allergens between foods'],
    ['shelf life', 3, 'how long food stays fit to use'],
    ['perishable', 3, 'food: likely to spoil quickly'],
    ['plating', 3, 'arranging food on a plate for serving'],
    ['food cost', 3, 'cost of ingredients as a share of menu price'],

    // Заходи та банкети
    ['buffet', 1, 'meal where guests serve themselves from a table'],
    ['banquet', 2, 'large formal meal for many guests'],
    ['venue', 2, 'place where an event is held'],
    ['catering', 2, 'providing food and drink for events'],
    ['event planner', 2, 'person who organizes weddings, conferences and parties'],
    ['wedding reception', 2, 'party with a meal after a wedding ceremony'],
    ['headcount', 3, 'final number of people expected at an event'],
    ['room setup', 3, 'how chairs and tables are arranged for an event'],
    ['audiovisual equipment', 3, 'projectors, microphones and screens'],
    ['breakout room', 3, 'small room for group sessions during a conference'],
    ['MICE', 3, 'meetings, incentives, conferences and exhibitions'],

    // Туризм і тури
    ['tour guide', 1],
    ['destination', 1, 'place tourists travel to'],
    ['accommodation', 1, 'place to stay, such as a hotel or apartment'],
    ['resort', 1, 'hotel complex for vacations'],
    ['tour operator', 2, 'company that organizes and sells package tours'],
    ['itinerary', 2, 'planned route and schedule of a trip'],
    ['transfer', 2, 'tourism: transport from airport to hotel'],
    ['peak season', 2, 'busiest time of year for tourism'],
    ['all-inclusive', 2, 'price covers meals, drinks and activities'],
    ['half board', 3, 'hotel rate with breakfast and dinner'],
    ['full board', 3, 'hotel rate with all three meals'],
    ['boutique hotel', 3, 'small stylish hotel with personal service'],

    // Сервіс і робота зі скаргами
    ['complaint', 1],
    ['apologize', 1],
    ['feedback', 1, 'opinions from guests about the service'],
    ['welcome', 1, 'verb: greet a guest warmly'],
    ['special request', 2, 'guest\'s wish such as a quiet room or a crib'],
    ['complimentary', 2, 'given free of charge'],
    ['compensate', 2, 'give something to make up for a problem'],
    ['inconvenience', 2, 'trouble or problem caused to a guest'],
    ['resolve', 2, 'find a solution to a problem'],
    ['courteous', 2, 'polite and respectful toward guests'],
    ['attentive', 2, 'paying close attention to guest needs'],
    ['online review', 2, 'guest\'s rating and comments on a website'],
    ['accommodate', 3, 'meet a guest\'s needs or request'],
    ['escalate', 3, 'pass a problem to a more senior manager'],
    ['discreet', 3, 'careful to respect guests\' privacy'],
    ['anticipate', 3, 'foresee guest needs before they ask'],

    // Управління та показники
    ['hospitality', 1, 'the hotel, restaurant and tourism industry'],
    ['shift', 1, 'work: a period of working time'],
    ['inventory', 2, 'stock of food, drinks and supplies on hand'],
    ['food and beverage', 2, 'hotel department for restaurants, bars and catering'],
    ['star rating', 2, 'hotel classification from one to five stars'],
    ['understaffed', 2, 'having too few workers'],
    ['average daily rate', 3, 'hotel: average room price per night sold'],
    ['RevPAR', 3, 'revenue per available room'],
    ['revenue management', 3, 'adjusting prices to maximize income'],
    ['property management system', 3, 'hotel software for bookings and billing'],
    ['point of sale', 3, 'system where orders are entered and payments taken'],
    ['health inspection', 3, 'official check of food and hygiene standards'],
    ['front of house', 3, 'staff and areas that deal with guests directly'],
    ['back of house', 3, 'staff and areas that guests do not see'],
  ],
};
