module.exports = {
  key: 'it',
  words: [
    // Базові поняття IT
    ['software', 1],
    ['developer', 1, 'software: person who writes code'],
    ['programming language', 1],
    ['source code', 1],
    ['algorithm', 1],
    ['operating system', 1],
    ['network', 1, 'computing: connected computers that exchange data'],
    ['artificial intelligence', 1],
    ['user interface', 1],
    ['tech stack', 2, 'set of technologies used to build a product'],

    // Основи програмування
    ['variable', 1, 'programming: named storage for a value'],
    ['function', 1, 'programming: reusable block of code'],
    ['loop', 1, 'programming: code that repeats'],
    ['array', 1, 'programming: ordered list of values'],
    ['string', 1, 'programming: sequence of characters'],
    ['library', 1, 'software: reusable code package'],
    ['framework', 1, 'software: foundation for building applications'],
    ['debug', 1, 'software: find and fix defects in code'],
    ['object', 2, 'programming: instance holding data and behavior'],
    ['class', 2, 'programming: blueprint for creating objects'],
    ['parameter', 2, 'programming: input a function accepts'],
    ['syntax', 2, 'programming: rules for how code must be written'],
    ['data structure', 2],
    ['exception', 2, 'programming: error raised while code runs'],
    ['dependency', 2, 'software: package a project relies on'],
    ['compile', 2, 'software: translate source code into a program'],
    ['execute', 2, 'software: run a program or command'],
    ['implement', 2, 'software: build a feature or logic in code'],
    ['script', 2, 'programming: short program that automates a task'],
    ['runtime', 3, 'software: environment in which code executes'],
    ['recursion', 3],
    ['inheritance', 3, 'object-oriented programming: reusing a parent class'],
    ['asynchronous', 3, 'programming: not blocking while waiting'],
    ['parse', 3, 'programming: analyze text into structured data'],
    ['initialize', 3, 'programming: set an initial value or state'],
    ['override', 3, 'programming: replace inherited behavior'],

    // Архітектура та системи
    ['architecture', 1, 'software: overall structure of a system'],
    ['backend', 1, 'server-side part of an application'],
    ['frontend', 1, 'user-facing part of an application'],
    ['server', 1, 'computer that provides services over a network'],
    ['database', 1],
    ['API', 1, 'application programming interface'],
    ['request', 1, 'network: message sent to a server'],
    ['response', 1, 'network: message returned by a server'],
    ['cloud', 1, 'computing: remote servers accessed over the internet'],
    ['client', 2, 'software: program that requests data from a server'],
    ['endpoint', 2, 'API: address that handles a specific request'],
    ['microservice', 2],
    ['cache', 2, 'fast temporary storage for frequently used data'],
    ['scalability', 3, 'ability of a system to handle growing load'],
    ['integrate', 2, 'software: connect systems so they work together'],
    ['monolith', 3, 'software: application built as one single unit'],
    ['load balancer', 3],
    ['message queue', 3],
    ['design pattern', 3, 'software: reusable solution to a common code problem'],
    ['abstraction', 3, 'software: hiding implementation details'],
    ['coupling', 3, 'software: degree of dependency between modules'],
    ['payload', 3, 'data carried in a request or message'],

    // Код і контроль версій
    ['repository', 1, 'version control: storage of project code'],
    ['version control', 1],
    ['branch', 1, 'version control: separate line of development'],
    ['commit', 1, 'version control: saved set of code changes'],
    ['merge', 1, 'version control: combine branches'],
    ['pull request', 1, 'proposal to merge code changes after review'],
    ['code review', 1],
    ['documentation', 1, 'software: written guide to code or product'],
    ['merge conflict', 2],
    ['refactor', 2, 'restructure code without changing its behavior'],
    ['technical debt', 3],
    ['legacy code', 2],
    ['readable', 2, 'code: easy to understand'],
    ['open source', 2],
    ['hotfix', 2],
    ['revert', 2, 'version control: undo a change'],
    ['reusable', 2, 'code: can be used again in other places'],
    ['fork', 3, 'version control: independent copy of a repository'],
    ['boilerplate', 3, 'code: repetitive standard code'],
    ['changelog', 3],
    ['deprecated', 3, 'software: discouraged and planned for removal'],
    ['backward compatible', 3, 'software: works with older versions'],

    // Тестування та якість
    ['bug', 1, 'software defect'],
    ['unit test', 1],
    ['crash', 1, 'software: sudden program failure'],
    ['error message', 1],
    ['integration test', 2],
    ['test coverage', 2],
    ['regression', 2, 'software: previously working feature broken'],
    ['quality assurance', 2],
    ['edge case', 2, 'unusual input or situation at the limits'],
    ['reproduce', 2, 'testing: make a bug happen again'],
    ['workaround', 2, 'temporary way to bypass a problem'],
    ['troubleshoot', 2, 'find and solve a technical problem'],
    ['end-to-end test', 3],
    ['stack trace', 3],
    ['mock', 3, 'testing: fake object that imitates a real one'],
    ['flaky test', 3, 'test that passes or fails inconsistently'],
    ['assertion', 3, 'testing: check that a condition is true'],

    // DevOps та інфраструктура
    ['deploy', 1, 'software: release code to servers'],
    ['release', 1, 'software: published version of a product'],
    ['production', 1, 'software: live environment used by customers'],
    ['environment', 1, 'software: setup where code runs, e.g. testing'],
    ['build', 1, 'software: compiled, runnable version of code'],
    ['infrastructure', 1, 'IT: servers, networks, and tools behind a system'],
    ['backup', 1, 'copy of data kept for recovery'],
    ['automate', 1],
    ['staging', 2, 'software: pre-production test environment'],
    ['pipeline', 2, 'automated sequence of build and deploy steps'],
    ['continuous integration', 2],
    ['container', 2, 'software: isolated package of an app and its needs'],
    ['configure', 2, 'IT: set up settings of a system'],
    ['monitoring', 2, 'IT: tracking system health in real time'],
    ['log', 2, 'software: record of system events'],
    ['downtime', 2, 'period when a system is unavailable'],
    ['incident', 2, 'IT: unplanned service disruption'],
    ['rollback', 2, 'software: return to a previous working version'],
    ['patch', 2, 'software: small update that fixes a problem'],
    ['orchestration', 3, 'automated management of many containers'],
    ['provision', 3, 'IT: set up servers or resources for use'],
    ['virtual machine', 3],
    ['bandwidth', 3, 'network: maximum data transfer rate'],
    ['on-call', 3, 'available to respond to incidents outside hours'],
    ['migrate', 3, 'IT: move data or systems to a new platform'],

    // Дані та бази даних
    ['query', 1, 'database: request for data'],
    ['dashboard', 1, 'software: screen showing key metrics at a glance'],
    ['metric', 2, 'measurable value tracked over time'],
    ['dataset', 2],
    ['machine learning', 2],
    ['validate', 2, 'check that data or input is correct'],
    ['synchronize', 2, 'data: make identical across systems or devices'],
    ['real-time', 2, 'happening instantly as events occur'],
    ['schema', 3, 'database: definition of the data structure'],
    ['index', 3, 'database: structure that speeds up lookups'],
    ['primary key', 3, 'database: unique identifier of a row'],
    ['large language model', 3],

    // Безпека
    ['security', 1, 'IT: protection of systems and data'],
    ['permission', 1, 'IT: right to perform an action'],
    ['authentication', 2, 'IT: verifying who a user is'],
    ['authorization', 2, 'IT: checking what a user is allowed to do'],
    ['encryption', 2],
    ['vulnerability', 2, 'security weakness that can be exploited'],
    ['firewall', 2, 'security: filter that blocks unwanted network traffic'],
    ['malware', 2],
    ['data breach', 2],
    ['phishing', 2],
    ['credentials', 2, 'login details such as username and password'],
    ['token', 3, 'security: digital credential granting access'],
    ['penetration testing', 3, 'security: simulated attack to find weaknesses'],
    ['certificate', 3, 'security: digital proof of identity for a site'],
    ['hash', 3, 'security: fixed-length value derived from data'],

    // Продукт і дизайн
    ['feature', 1, 'software: piece of product functionality'],
    ['requirement', 1, 'what a product or system must do'],
    ['user experience', 1],
    ['roadmap', 2, 'product: plan of upcoming work over time'],
    ['mockup', 2, 'design: visual draft of a screen'],
    ['specification', 2, 'detailed technical description'],
    ['user story', 2, 'agile: feature described from the user view'],
    ['usability', 2],
    ['intuitive', 2, 'UX: easy to use without instructions'],
    ['responsive', 2, 'web design: adapts to screen size'],
    ['minimum viable product', 3],
    ['A/B testing', 3],
    ['accessibility', 3, 'design usable by people with disabilities'],
    ['cross-platform', 3, 'works on several operating systems'],

    // Agile-процеси та командна робота
    ['sprint', 1, 'agile: short fixed period of work'],
    ['backlog', 1, 'agile: prioritized list of pending work'],
    ['ticket', 1, 'issue tracker: work item or bug entry'],
    ['agile', 1, 'flexible, iterative approach to development'],
    ['stand-up', 2, 'agile: short daily team meeting'],
    ['retrospective', 2, 'agile: meeting to review how work went'],
    ['product owner', 2, 'agile: person who manages the backlog'],
    ['blocker', 2, 'issue that prevents progress on a task'],
    ['iterate', 2, 'improve something through repeated cycles'],
    ['story point', 3, 'agile: unit for estimating effort'],
    ['velocity', 3, 'agile: amount of work completed per sprint'],
    ['scrum master', 3, 'agile: facilitator of the scrum process'],
    ['definition of done', 3, 'agile: criteria for a task to be complete'],
    ['acceptance criteria', 3, 'agile: conditions a feature must meet to be accepted'],

    // Продуктивність і надійність
    ['performance', 1, 'software: speed and efficiency'],
    ['memory', 1, 'computing: RAM used by running programs'],
    ['latency', 2, 'delay before data transfer or a response'],
    ['optimize', 2, 'make faster or more efficient'],
    ['timeout', 2, 'limit after which an operation is stopped'],
    ['stable', 2, 'software: reliable, without crashes'],
    ['memory leak', 3],
    ['throughput', 3],
    ['availability', 3, 'IT: share of time a system is operational'],
    ['fault tolerance', 3],
    ['robust', 3, 'software: handles errors and unusual input well'],
    ['redundancy', 3, 'IT: duplicate components as a safeguard'],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'algorithm', 'operating system', 'function', 'framework', 'object', 'class', 'parameter', 'syntax',
    'compile', 'script', 'recursion', 'asynchronous', 'initialize', 'architecture', 'backend', 'frontend',
    'server', 'API', 'client', 'microservice', 'cache', 'integrate', 'monolith', 'abstraction',
    'repository', 'version control', 'documentation', 'refactor', 'bug', 'integration test', 'regression', 'release',
    'infrastructure', 'backup', 'automate', 'container', 'configure', 'monitoring', 'incident', 'patch',
    'orchestration', 'virtual machine', 'migrate', 'dashboard', 'metric', 'synchronize', 'schema', 'index',
    'authentication', 'authorization', 'phishing', 'token', 'certificate', 'hash', 'specification', 'intuitive',
    'A/B testing', 'cross-platform', 'sprint', 'retrospective', 'iterate', 'optimize', 'timeout', 'stable',
  ],
};
