module.exports = {
  key: 'law',
  words: [
    // Основи права
    ['law', 1, 'system of rules enforced by a state'],
    ['legal', 1, 'relating to the law or permitted by law'],
    ['right', 1, 'law: legal entitlement to have or do something'],
    ['obligation', 1, 'legal duty to do something'],
    ['liability', 1, 'law: legal responsibility for harm or loss, not a debt'],
    ['regulation', 1, 'official rule issued by a government authority'],
    ['criminal law', 2],
    ['civil law', 2, 'law of private disputes between people or companies'],
    ['legislation', 2],
    ['statute', 2, 'written law passed by a legislature'],
    ['jurisdiction', 2, 'authority of a court or state over a matter'],
    ['precedent', 2, 'earlier court decision used as a guide for later cases'],
    ['liable', 2, 'legally responsible for something'],
    ['mandatory', 2],
    ['prohibit', 2],
    ['enforce', 2],
    ['negligence', 2, 'law: failure to take proper care, causing harm'],
    ['statutory', 3],
    ['due process', 3, 'fair legal procedures guaranteed by law'],
    ['statute of limitations', 3, 'time limit for bringing a legal claim'],
    ['tort', 3, 'civil wrong causing harm, e.g. negligence'],

    // Юридичні професії та учасники
    ['lawyer', 1],
    ['attorney', 1, 'lawyer licensed to act for clients in court'],
    ['judge', 1, 'court official who decides cases'],
    ['law firm', 1],
    ['party', 1, 'law: a person or company in a contract or case'],
    ['plaintiff', 1, 'party who brings a civil lawsuit'],
    ['defendant', 1, 'party being sued or accused in court'],
    ['witness', 1, 'person who testifies about facts'],
    ['prosecutor', 2],
    ['notary', 2, 'official who certifies signatures and documents'],
    ['counterparty', 2, 'the other party to a contract or deal'],
    ['represent', 2, 'law: to act for a client in court or in a deal'],
    ['partner', 2, 'law firm: senior lawyer who co-owns the firm'],
    ['in-house counsel', 3, "lawyer employed by a company's own legal team"],
    ['mediator', 3],

    // Договори та угоди
    ['contract', 1],
    ['agreement', 1, 'legal: binding arrangement between parties'],
    ['clause', 1, 'contract: a separate section or provision'],
    ['terms and conditions', 1],
    ['draft', 1, 'verb: to write the first version of a document'],
    ['negotiate', 1],
    ['breach', 1, 'law: violation of a contract or legal duty'],
    ['confidential', 1],
    ['non-disclosure agreement', 1, 'contract to keep information secret (NDA)'],
    ['terminate', 2, 'to end a contract officially'],
    ['amendment', 2, 'formal change to a law or document'],
    ['warranty', 2, 'contract: promise that facts or quality are as stated'],
    ['penalty', 2, 'sum to be paid for breaking a rule or contract'],
    ['valid', 2, 'legally effective'],
    ['contractual', 2],
    ['legally binding', 2],
    ['power of attorney', 2, 'document authorizing someone to act for another'],
    ['provision', 2, 'specific rule or condition in a law or contract'],
    ['exclusive', 2, 'contract: granted to only one party, e.g. a license'],
    ['indemnify', 3, "contract: to compensate the other party's losses"],
    ['force majeure', 3, 'events beyond control that excuse non-performance'],
    ['governing law', 3, 'clause naming which law applies to a contract'],
    ['void', 3, 'legally invalid, having no effect'],
    ['enforceable', 3, 'able to be imposed by a court'],
    ['waive', 3, 'to give up a legal right or claim voluntarily'],
    ['assign', 3, 'law: to transfer rights to another party'],
    ['execute', 3, 'contract: to sign formally so it takes legal effect'],
    ['remedy', 3, 'law: way to enforce a right or compensate a loss'],

    // Суд і судовий процес
    ['court', 1, 'law: place or body where legal cases are decided'],
    ['lawsuit', 1],
    ['case', 1, 'law: a matter decided in court'],
    ['trial', 1, 'law: formal examination of a case in court'],
    ['hearing', 1, 'law: court session to hear evidence or arguments'],
    ['claim', 1, 'law: demand for money, property or a right'],
    ['sue', 1],
    ['evidence', 1],
    ['guilty', 1, 'law: responsible for a crime or offense'],
    ['dispute', 1, 'disagreement, especially a legal one'],
    ['litigation', 1, 'process of taking legal action in court'],
    ['appeal', 1, 'law: request to a higher court to change a decision'],
    ['verdict', 2, 'decision of a jury or court on guilt'],
    ['judgment', 2, 'formal decision of a court'],
    ['ruling', 2, 'official decision by a judge'],
    ['jury', 2],
    ['settlement', 2, 'law: agreement that ends a dispute without trial'],
    ['settle', 2, 'law: to resolve a dispute by agreement'],
    ['damages', 2, 'law: money awarded as compensation for loss'],
    ['testify', 2, 'to give evidence as a witness in court'],
    ['arbitration', 2, 'settling a dispute by an arbitrator instead of a court'],
    ['complaint', 2, 'law: document that starts a civil lawsuit'],
    ['file', 2, 'law: to officially submit a document to a court'],
    ['sentence', 2, 'law: punishment given by a court'],
    ['defense', 2, 'law: the side defending the accused or sued party'],
    ['allegation', 3, 'claim that someone did wrong, not yet proven'],
    ['injunction', 3, 'court order to do or stop doing something'],
    ['overturn', 3, "law: to cancel a lower court's decision"],
    ['adjourn', 3, 'law: to postpone a court session to a later time'],
    ['subpoena', 3, 'order requiring someone to appear in court'],
    ['burden of proof', 3, 'duty to prove a disputed claim'],
    ['admissible', 3, 'law: allowed to be used as evidence in court'],
    ['motion', 3, 'law: formal request asking a judge for a ruling'],
    ['class action', 3, 'lawsuit brought by a group with the same claim'],
    ['affidavit', 3, 'written statement confirmed by oath'],

    // Корпоративне право
    ['corporation', 1],
    ['shareholder', 1],
    ['board of directors', 1],
    ['legal entity', 2, 'organization recognized by law as having rights'],
    ['limited liability company', 2, 'company whose owners risk only what they invested (LLC)'],
    ['merger', 2],
    ['acquisition', 2, 'purchase of one company by another'],
    ['due diligence', 2, 'investigation of a company or deal before signing'],
    ['subsidiary', 2],
    ['joint venture', 2],
    ['resolution', 2, 'formal decision voted by a board or shareholders'],
    ['corporate governance', 2],
    ['bankruptcy', 2],
    ['incorporate', 3, 'to legally form a company'],
    ['articles of incorporation', 3, 'document that legally creates a corporation'],
    ['fiduciary duty', 3, "legal duty to act in another person's best interest"],

    // Комплаєнс і регулювання
    ['compliance', 1, 'following laws, rules and standards'],
    ['violation', 1],
    ['fraud', 1],
    ['data protection', 1],
    ['consent', 1, 'permission, e.g. to use personal data'],
    ['fine', 1, 'money paid as a punishment for breaking a rule'],
    ['comply', 2],
    ['regulator', 2, 'official body that supervises an industry'],
    ['regulatory', 2],
    ['audit', 2, 'official inspection of records or processes'],
    ['conflict of interest', 2],
    ['sanctions', 2, 'penalties imposed by states, e.g. trade bans'],
    ['data breach', 2, 'incident where data is stolen or exposed'],
    ['GDPR', 2, 'General Data Protection Regulation (EU law)'],
    ['bribery', 2],
    ['money laundering', 2],
    ['disclose', 2],
    ['whistleblower', 3],
    ['KYC', 3, 'know your customer: verifying the identity of clients'],
    ['antitrust', 3, 'law against monopolies and unfair competition'],

    // Інтелектуальна власність
    ['intellectual property', 1],
    ['copyright', 1],
    ['trademark', 1],
    ['patent', 1],
    ['license', 1, 'official permission to do or use something'],
    ['infringement', 2, 'violation of a legal right, e.g. copyright'],
    ['royalty', 2, 'payment for using a patent, book or music'],
    ['trade secret', 2],
    ['infringe', 3, 'to violate a right such as a patent or copyright'],
    ['public domain', 3, 'works free of copyright, usable by anyone'],
    ['fair use', 3, 'limited use of copyrighted material without permission'],

    // Трудове право та власність
    ['employment contract', 1],
    ['property', 1, 'law: something owned, e.g. land or goods'],
    ['lease', 2, 'contract to rent property for a set period'],
    ['tenant', 2],
    ['will', 2, 'law: document saying who gets property after death'],
    ['discrimination', 2],
    ['dismissal', 2, "employment: ending a worker's job by the employer"],
    ['non-compete clause', 2, 'clause banning work for competitors after leaving'],
    ['severance pay', 3],
    ['wrongful termination', 3, 'firing an employee in breach of law or contract'],
    ['deed', 3, 'law: signed document that transfers property'],

    // Юридичне письмо та документи
    ['legal advice', 1],
    ['shall', 2, 'legal writing: expresses an obligation'],
    ['interpret', 2, 'law: to decide the meaning of a text or rule'],
    ['authorize', 2],
    ['legal opinion', 3, "lawyer's formal written advice on a legal issue"],
    ['brief', 3, 'law: written legal argument submitted to a court'],
    ['defined term', 3, 'contract: word given a specific meaning in the text'],
    ['hereby', 3, 'formal: by means of this document'],
    ['notwithstanding', 3, 'legal writing: despite, in spite of'],
    ['pursuant to', 3, 'legal writing: in accordance with'],
    ['stipulate', 3, 'to state clearly as a requirement in a contract'],
    ['notarize', 3, 'to have a document certified by a notary'],
    ['revoke', 3, 'to officially cancel a right, license or law'],
  ],
};
