module.exports = {
  key: 'management',
  words: [
    // Стратегія та планування
    ['strategy', 1],
    ['goal', 1, 'aim or desired result, not sports'],
    ['priority', 1],
    ['competitor', 1],
    ['business plan', 1],
    ['long-term', 1],
    ['quarter', 1, 'business: three-month period of the financial year'],
    ['vision', 2, 'business: long-term picture of what a company wants to become'],
    ['mission', 2, 'business: core purpose of an organization'],
    ['objective', 2, 'noun: specific, measurable business aim'],
    ['roadmap', 2, 'plan showing goals and steps over time'],
    ['business model', 2],
    ['competitive advantage', 2],
    ['sustainable', 2, 'business: able to continue successfully over the long term'],
    ['initiative', 2, 'business: new plan or project to reach a goal'],
    ['align', 2, 'bring goals, teams or plans into agreement'],
    ['trade-off', 2, 'giving up one thing to gain another'],
    ['forecast', 2, 'business: projection of future sales or results'],
    ['contingency plan', 3, 'backup plan in case something goes wrong'],

    // Лідерство та команда
    ['leadership', 1],
    ['team', 1],
    ['manage', 1, 'be in charge of people, work or a business'],
    ['lead', 1, 'verb: be in charge of a team or project'],
    ['motivate', 1],
    ['hire', 1, 'employ a new person'],
    ['conflict', 1, 'disagreement between people at work'],
    ['delegate', 2, 'verb: give a task or authority to someone else'],
    ['coordinate', 2, 'verb: organize people or tasks to work together'],
    ['empower', 2, 'give people authority and confidence to act'],
    ['accountability', 2, 'being answerable for results'],
    ['one-on-one', 2, 'regular private meeting between manager and employee'],
    ['company culture', 2, 'shared values and behavior in an organization'],
    ['headcount', 2, 'number of employees in a company or team'],
    ['recruit', 2, 'verb: find and hire new employees'],
    ['morale', 2, 'confidence and enthusiasm of a team'],
    ['transparent', 2, 'open and honest about decisions and information'],
    ['direct report', 3, 'employee who reports directly to a manager'],
    ['micromanage', 3, "control every detail of employees' work"],
    ['employee retention', 3, 'keeping employees from leaving the company'],
    ['succession planning', 3, 'preparing people to replace key leaders'],
    ['buy-in', 3, 'agreement and support for a plan from people involved'],
    ['cross-functional', 3, 'involving people from different departments'],
    ['top-down', 3, 'decided by leaders and passed down to staff'],

    // Операційна діяльність
    ['process', 1, 'series of steps to get work done'],
    ['operations', 1, 'day-to-day running of a business'],
    ['resource', 1, 'money, people or materials available for use'],
    ['supplier', 1],
    ['productivity', 1],
    ['efficient', 2],
    ['best practice', 2, 'method accepted as the most effective'],
    ['supply chain', 2],
    ['capacity', 2, 'maximum amount that can be produced or handled'],
    ['bottleneck', 2, 'point that slows down a whole process'],
    ['automate', 2],
    ['outsource', 2],
    ['optimize', 2],
    ['procurement', 3, 'buying goods and services for a company'],
    ['in-house', 3, 'done within the company, not outsourced'],
    ['streamline', 3, 'make a process simpler and more efficient'],
    ['overhaul', 3, 'verb: thoroughly change and improve a system'],
    ['lean', 3, 'management: focused on cutting waste and maximizing value'],
    ['overhead', 3, 'business: ongoing indirect operating costs'],

    // Управління проєктами
    ['project', 1],
    ['deadline', 1],
    ['budget', 1],
    ['timeline', 1, 'planned sequence of events with dates'],
    ['risk', 1],
    ['project manager', 1],
    ['prioritize', 1],
    ['approve', 1, 'officially accept a plan, budget or request'],
    ['milestone', 2, 'important point or stage in a project'],
    ['stakeholder', 2, 'person or group with an interest in a project'],
    ['scope', 2, 'project: range of work included'],
    ['deliverable', 2, 'project: result or product to be handed over'],
    ['kickoff meeting', 2, 'first meeting that officially starts a project'],
    ['allocate', 2, 'assign resources or money for a purpose'],
    ['agile', 2, 'flexible, iterative way of managing projects'],
    ['sprint', 2, 'agile: short fixed period of focused work'],
    ['dependency', 3, 'project: task that relies on another being done'],
    ['critical path', 3, 'longest chain of tasks that sets project duration'],
    ['scope creep', 3, 'uncontrolled growth of project requirements'],
    ['sign-off', 3, 'formal approval to proceed'],
    ['escalate', 3, 'pass an issue to a higher level of management'],
    ['mitigate', 3, 'reduce the impact of a risk or problem'],

    // Рішення та аналітика
    ['decision', 1],
    ['analysis', 1],
    ['KPI', 1, 'key performance indicator'],
    ['decision-making', 2],
    ['metric', 2, 'measurable value used to track performance'],
    ['assess', 2],
    ['dashboard', 2, 'screen showing key business data at a glance'],
    ['insight', 2, 'valuable understanding drawn from data'],
    ['data-driven', 2],
    ['feasible', 3, 'possible and practical to achieve'],
    ['root cause', 3, 'fundamental reason a problem happens'],
    ['benchmark', 3, 'standard or point of reference for comparison'],

    // Переговори та угоди
    ['negotiation', 1],
    ['negotiate', 1],
    ['deal', 1, 'business agreement'],
    ['contract', 1, 'noun: legal agreement'],
    ['proposal', 1, 'formal plan or offer put forward for approval'],
    ['partner', 1, 'business partner'],
    ['compromise', 2],
    ['terms', 2, 'conditions of an agreement'],
    ['close', 2, 'verb: successfully complete a deal or sale'],
    ['concession', 3, 'something given up to reach an agreement'],
    ['bargaining power', 3],
    ['counteroffer', 3],
    ['deadlock', 3, 'situation where neither side will agree'],
    ['legally binding', 3],

    // Стартапи та підприємництво
    ['startup', 1],
    ['founder', 1],
    ['entrepreneur', 1],
    ['small business', 1],
    ['launch', 1, 'introduce a new product or company'],
    ['pitch', 2, 'short talk to persuade investors or clients'],
    ['pitch deck', 2, 'slide presentation for investors'],
    ['MVP', 2, 'minimum viable product'],
    ['validate', 2, 'confirm that an idea works or is wanted'],
    ['iterate', 2, 'improve something through repeated cycles'],
    ['product-market fit', 3, 'product strongly satisfies real market demand'],
    ['pivot', 3, 'startup: fundamentally change business direction'],
    ['bootstrap', 3, 'startup: build a company without outside funding'],
    ['traction', 3, 'startup: evidence of growing customer demand'],
    ['disrupt', 3, 'business: radically change an industry or market'],
    ['runway', 3, 'startup: how long money lasts at current spending'],
    ['burn rate', 3, 'startup: how fast a company spends its cash'],

    // Інвестори та фінансування
    ['investor', 1],
    ['funding', 1, 'money provided to a business'],
    ['revenue', 1, 'income from sales'],
    ['profit', 1],
    ['equity', 2, 'ownership share in a company'],
    ['stake', 2, 'share of ownership in a business'],
    ['valuation', 2, 'estimated value of a company'],
    ['funding round', 2, 'stage of raising money from investors'],
    ['venture capital', 2],
    ['angel investor', 2, 'wealthy individual investing in early startups'],
    ['seed round', 3, 'first official funding round of a startup'],
    ['due diligence', 3, 'detailed check of a company before a deal'],
    ['term sheet', 3, 'document outlining key terms of an investment'],
    ['dilution', 3, "reduction of owners' share when new shares are issued"],
    ['cap table', 3, 'table showing who owns what share of a company'],
    ['exit', 3, "business: sale of a company or an investor's stake"],
    ['break even', 3, 'reach the point where income equals costs'],

    // Структура компанії
    ['department', 1],
    ['CEO', 1, 'chief executive officer'],
    ['headquarters', 1],
    ['executive', 2, 'senior manager in a company'],
    ['board of directors', 2],
    ['merger', 2],
    ['acquisition', 2, 'business: buying another company'],
    ['restructure', 2, 'reorganize a company in a major way'],
    ['oversee', 3, 'supervise work or people'],
    ['subsidiary', 3, 'company controlled by a parent company'],
    ['joint venture', 3, 'business project run jointly by two companies'],
    ['corporate governance', 3, 'system for directing and controlling a company'],

    // Зростання та масштабування
    ['growth', 1],
    ['expand', 1],
    ['target', 1, 'goal to reach, e.g. a sales target'],
    ['performance', 1, 'how well a person or company does'],
    ['scale', 2, 'verb: grow a business quickly and efficiently'],
    ['implement', 2, 'put a plan or decision into action'],
    ['execute', 2, 'carry out a plan or strategy'],
    ['scalable', 3, 'able to grow without a matching rise in costs'],
    ['economies of scale', 3, 'lower costs per unit as production grows'],
    ['downsize', 3, 'reduce the number of employees in a company'],
  ],
};
