module.exports = {
  key: 'marketing',
  words: [
    // Основи та стратегія
    ['strategy', 1],
    ['competitor', 1],
    ['marketer', 1],
    ['launch', 1, 'introduce a new product or campaign to the public'],
    ['promote', 1, 'advertise or publicize a product'],
    ['channel', 1, 'marketing: a way to reach customers, e.g. email'],
    ['competitive', 2, 'able to compete well with rivals, e.g. a price'],
    ['market share', 2],
    ['niche', 2, 'small specialized segment of a market'],
    ['value proposition', 2, 'why a customer should choose your product'],
    ['pitch', 2, 'present an idea to persuade someone'],
    ['cost-effective', 2],
    ['pricing', 2],
    ['differentiate', 3, 'make a product stand out from competitors'],
    ['unique selling proposition', 3, 'key benefit that sets a product apart (USP)'],
    ['marketing mix', 3, 'the 4 Ps: product, price, place, promotion'],
    ['go-to-market strategy', 3, 'plan for bringing a product to customers'],
    ['customer-centric', 3],
    ['saturated', 3, 'of a market: having too many similar products'],

    // Аудиторія та дослідження ринку
    ['target audience', 1],
    ['consumer', 1],
    ['market research', 1],
    ['survey', 1, 'research: questionnaire to collect opinions'],
    ['feedback', 1, 'opinions from customers about a product'],
    ['segment', 2, 'market: group of customers with shared traits'],
    ['buyer persona', 2, 'fictional profile of a typical ideal customer'],
    ['demographics', 2, 'data about the age, income, etc. of a group'],
    ['insight', 2, 'deep understanding of customer behavior'],
    ['pain point', 2, "a customer's specific problem to solve"],
    ['focus group', 2],
    ['SWOT analysis', 2, 'Strengths, Weaknesses, Opportunities, Threats'],
    ['qualitative', 3],
    ['quantitative', 3],
    ['psychographics', 3, 'data on values, interests and lifestyle of a group'],

    // Бренд і позиціонування
    ['brand', 1],
    ['logo', 1],
    ['slogan', 1],
    ['brand awareness', 1, 'how well people know a brand'],
    ['loyal', 1, 'of customers: regularly buying the same brand'],
    ['brand identity', 2, 'visual and verbal elements that represent a brand'],
    ['positioning', 2, "how a brand is placed in customers' minds"],
    ['packaging', 2],
    ['rebrand', 2, "change a company's name, logo or image"],
    ['mass-market', 2, 'made for and sold to a very large number of people'],
    ['premium', 2, 'high-end and higher-priced, e.g. a brand'],
    ['recognizable', 2],
    ['tone of voice', 3, 'consistent style in which a brand communicates'],
    ['brand guidelines', 3, "rules for using a brand's logo, colors and fonts"],
    ['brand equity', 3, 'value a brand adds beyond the product itself'],
    ['brand ambassador', 3, 'person paid to represent and promote a brand'],

    // Реклама та кампанії
    ['advertising', 1],
    ['campaign', 1, 'marketing: series of planned promotional activities'],
    ['promotion', 1, 'activity to boost sales, e.g. a special offer'],
    ['agency', 1, 'firm that runs marketing or ads for clients'],
    ['attract', 1, 'draw interest, e.g. of customers'],
    ['call to action', 2, 'prompt telling the user what to do next'],
    ['brief', 2, 'document describing a task for an agency or team'],
    ['commercial', 2, 'TV or radio advertisement'],
    ['sponsor', 2, 'fund an event or person in exchange for publicity'],
    ['ad spend', 2, 'money spent on advertising'],
    ['target', 2, 'verb: aim ads at a specific group of people'],
    ['cost per click', 2, 'price paid each time someone clicks an ad'],
    ['eye-catching', 2],
    ['creative', 3, 'advertising: the visual or text of an ad'],
    ['media plan', 3, 'schedule of where and when ads will run'],
    ['retargeting', 3, 'showing ads to people who visited a site before'],
    ['programmatic advertising', 3, 'automated buying of digital ad space'],
    ['cannibalize', 3, 'of a new product: take sales from your own older one'],

    // Цифровий маркетинг і SEO
    ['digital marketing', 1],
    ['landing page', 1, 'web page built for one specific campaign goal'],
    ['keyword', 1, 'word people type into a search engine'],
    ['SEO', 1, 'search engine optimization'],
    ['email marketing', 1],
    ['newsletter', 1],
    ['traffic', 1, 'web: number of visitors to a site'],
    ['subscriber', 2, 'person signed up for emails or updates'],
    ['organic', 2, 'marketing: unpaid, e.g. search results or reach'],
    ['optimize', 2],
    ['personalize', 2],
    ['paid media', 3, 'advertising a brand pays for'],
    ['earned media', 3, 'free publicity from press, shares and reviews'],
    ['owned media', 3, 'channels a brand controls, e.g. its website'],
    ['backlink', 3, 'link from another website to yours'],
    ['affiliate marketing', 3, 'paying partners a commission for referred sales'],
    ['omnichannel', 3, 'consistent experience across all channels'],
    ['cookie', 3, "web: small file that tracks a user's browsing"],

    // Соціальні мережі
    ['social media', 1],
    ['platform', 1, 'online service, e.g. a social network'],
    ['post', 1, 'social media: content published on a feed'],
    ['hashtag', 1],
    ['follower', 1, 'social media: person who subscribes to an account'],
    ['influencer', 1],
    ['engagement', 1, 'social media: likes, comments, shares, etc.'],
    ['share', 1, 'social media: repost content to others'],
    ['viral', 2, 'spreading very quickly online'],
    ['algorithm', 2, 'rules a platform uses to rank and show content'],
    ['caption', 2, 'text accompanying an image or video post'],
    ['trending', 2, 'currently very popular on social media'],
    ['content creator', 2],
    ['user-generated content', 3, 'content created by customers, not the brand'],
    ['social listening', 3, 'monitoring online talk about a brand'],

    // Контент і копірайтинг
    ['content', 1, 'texts, images and videos a brand publishes'],
    ['headline', 1],
    ['blog', 1],
    ['publish', 1],
    ['copy', 2, 'advertising: the written text of an ad'],
    ['copywriting', 2, 'writing text for ads and marketing'],
    ['content marketing', 2],
    ['storytelling', 2],
    ['content calendar', 2, 'schedule of planned content'],
    ['case study', 2, 'marketing: detailed story of a client success'],
    ['testimonial', 2, 'customer statement praising a product'],
    ['persuasive', 2],
    ['catchy', 2, 'easy to remember, e.g. a slogan or tune'],
    ['white paper', 3, 'in-depth report on an issue or solution'],
    ['evergreen', 3, 'content: staying relevant for a long time'],
    ['repurpose', 3, 'reuse content in a new format'],
    ['thought leadership', 3, 'content showing expertise in a field'],

    // Аналітика та метрики
    ['analytics', 1],
    ['metric', 1, 'measurable value used to track performance'],
    ['KPI', 1, 'key performance indicator'],
    ['conversion', 1, 'when a user completes a desired action, e.g. buys'],
    ['reach', 1, 'number of unique people who see content'],
    ['track', 1, 'monitor and record, e.g. results or clicks'],
    ['conversion rate', 2],
    ['click-through rate', 2, 'share of people who click after seeing a link'],
    ['impression', 2, 'ads: one display of an ad to a user'],
    ['ROI', 2, 'return on investment'],
    ['A/B test', 2, 'comparing two versions to see which performs better'],
    ['dashboard', 2, 'analytics: screen showing key data at a glance'],
    ['data-driven', 2],
    ['measurable', 2],
    ['bounce rate', 3, 'share of visitors who leave after one page'],
    ['open rate', 3, 'email: share of recipients who open a message'],
    ['attribution', 3, 'assigning credit for a sale to marketing channels'],
    ['customer lifetime value', 3, 'total revenue expected from one customer'],
    ['cost per acquisition', 3, 'average cost to gain one new customer'],

    // Продажі та воронка
    ['lead', 1, 'sales: a potential customer'],
    ['discount', 1],
    ['review', 1, 'customer opinion about a product online'],
    ['funnel', 2, 'marketing: stages from awareness to purchase'],
    ['customer journey', 2, 'all steps a customer goes through with a brand'],
    ['lead generation', 2, 'attracting potential customers'],
    ['B2B', 2, 'business-to-business'],
    ['B2C', 2, 'business-to-consumer'],
    ['word of mouth', 2, 'people telling each other about a product'],
    ['convert', 2, 'turn a visitor into a customer'],
    ['retain', 2, 'keep existing customers'],
    ['loyalty program', 2],
    ['touchpoint', 3, 'any point where a customer interacts with a brand'],
    ['upsell', 3, 'sell a more expensive version to a customer'],
    ['cross-sell', 3, 'sell related extra products to a customer'],
    ['nurture', 3, 'marketing: build relationships with leads over time'],
    ['abandoned cart', 3, 'items left in an online cart without buying'],
    ['monetize', 3, 'earn money from, e.g. an audience or content'],

    // PR і комунікації
    ['public relations', 1, "managing a company's public image"],
    ['press release', 1],
    ['media', 1, 'press, TV, radio and online news'],
    ['announce', 1],
    ['press conference', 2],
    ['spokesperson', 2],
    ['publicity', 2, 'public attention from media coverage'],
    ['coverage', 2, 'media: amount of reporting on a topic'],
    ['trade show', 2, 'exhibition where companies show products'],
    ['crisis management', 3],
    ['press kit', 3, 'package of info and images for journalists'],
    ['outreach', 3, 'contacting people or media to build ties'],
    ['backlash', 3, 'strong negative public reaction'],
    ['endorse', 3, 'publicly support or recommend a product'],
  ],
};
