module.exports = {
  key: 'medicine',
  words: [
    // Лікарня та медичний персонал
    ['hospital', 1],
    ['clinic', 1, 'medical facility, mainly for outpatients'],
    ['patient', 1, 'noun: person receiving medical care'],
    ['nurse', 1],
    ['physician', 1, 'medical doctor'],
    ['surgeon', 1],
    ['pharmacist', 1],
    ['ward', 2, 'hospital: room or unit where inpatients stay'],
    ['emergency room', 1],
    ['specialist', 2, 'medicine: doctor trained in one specific field'],
    ['general practitioner', 2, 'family doctor providing primary care'],
    ['paramedic', 2],
    ['outpatient', 2, 'patient treated without staying overnight'],
    ['inpatient', 2, 'patient admitted to stay in hospital'],
    ['intensive care unit', 2],
    ['on call', 2, 'available to work outside regular hours if needed'],
    ['triage', 3, 'sorting patients by urgency of treatment'],

    // Прийом пацієнта та спілкування
    ['appointment', 1, 'scheduled visit to a doctor'],
    ['medical history', 1],
    ['medical record', 1],
    ['examine', 1, 'medicine: check a patient physically'],
    ['checkup', 1, 'routine medical examination'],
    ['admit', 2, 'hospital: accept a patient for inpatient care'],
    ['discharge', 2, 'hospital: officially release a patient'],
    ['referral', 2, 'sending a patient to a specialist'],
    ['follow-up', 2, 'later visit to check progress'],
    ['confidentiality', 3, 'medicine: keeping patient information private'],
    ['informed consent', 3],
    ['chief complaint', 3, 'main reason a patient seeks care'],
    ['adherence', 3, 'medicine: patient following the prescribed treatment'],

    // Симптоми та скарги
    ['symptom', 1],
    ['pain', 1],
    ['fever', 1],
    ['cough', 1],
    ['headache', 1],
    ['nausea', 2],
    ['dizzy', 1],
    ['rash', 1, 'skin: area of red spots or patches'],
    ['bleed', 1],
    ['shortness of breath', 2],
    ['mild', 1, 'medicine: not serious or strong'],
    ['severe', 1, 'medicine: very serious or intense'],
    ['fatigue', 2, 'medicine: extreme tiredness'],
    ['inflammation', 2],
    ['numbness', 2],
    ['swollen', 2],
    ['vomit', 2],
    ['faint', 2, 'verb: lose consciousness briefly'],
    ['acute', 2, 'medicine: sudden and short-term'],
    ['chronic', 2, 'medicine: lasting a long time or recurring'],
    ['onset', 3, 'medicine: start of a symptom or disease'],
    ['tenderness', 3, 'medicine: pain when an area is touched'],
    ['palpitations', 3],
    ['asymptomatic', 3],

    // Обстеження та діагностика
    ['diagnosis', 1],
    ['diagnose', 1],
    ['blood test', 1],
    ['blood pressure', 1],
    ['pulse', 1, 'heartbeat felt at the wrist or neck'],
    ['X-ray', 1],
    ['sample', 2, 'medicine: small amount of blood, urine etc. for testing'],
    ['ultrasound', 2],
    ['MRI', 2, 'magnetic resonance imaging'],
    ['CT scan', 2, 'computed tomography scan'],
    ['vital signs', 2],
    ['screening', 2, 'medicine: testing people for early signs of disease'],
    ['positive', 2, 'test result: condition or substance is present'],
    ['negative', 2, 'test result: condition or substance is absent'],
    ['abnormal', 2],
    ['biopsy', 3],
    ['differential diagnosis', 3, 'list of possible conditions explaining symptoms'],
    ['prognosis', 3, 'likely course and outcome of a disease'],
    ['benign', 3, 'medicine: not cancerous'],
    ['malignant', 3, 'medicine: cancerous, able to spread'],
    ['palpate', 3, 'examine the body by touching with the hands'],
    ['clinical trial', 3, 'research study testing a treatment on people'],

    // Лікування та процедури
    ['treatment', 1],
    ['treat', 1, 'medicine: give medical care to'],
    ['surgery', 1, 'medical operation on the body'],
    ['injection', 1],
    ['vaccine', 1],
    ['bandage', 1],
    ['recover', 1, 'get well again after illness or injury'],
    ['therapy', 2, 'treatment of a disease or condition'],
    ['procedure', 2, 'medicine: a medical operation or treatment'],
    ['operate', 2, 'medicine: perform surgery'],
    ['physical therapy', 2],
    ['rehabilitation', 2, 'medicine: restoring health and function after illness'],
    ['anesthesia', 2],
    ['infusion', 3, 'medicine: fluid or drug given slowly into a vein'],
    ['cure', 2, 'noun: treatment that fully ends a disease'],
    ['monitor', 2, "verb, medicine: observe a patient's condition over time"],
    ['complication', 2, 'medicine: new problem arising during illness or care'],
    ['cast', 2, 'medicine: hard shell that holds a broken bone still'],
    ['suture', 3, 'noun: stitch used to close a wound'],
    ['incision', 3],
    ['invasive', 3, 'medicine: involving entry into the body'],
    ['transfusion', 3],
    ['transplant', 3, 'medicine: transfer of an organ from a donor'],
    ['ventilator', 3, 'machine that helps a patient breathe'],
    ['palliative care', 3],

    // Ліки та фармакологія
    ['medication', 1],
    ['prescription', 1],
    ['prescribe', 1],
    ['dose', 1, 'amount of medicine taken at one time'],
    ['tablet', 1, 'medicine: small solid pill'],
    ['painkiller', 1],
    ['antibiotic', 1],
    ['side effect', 1],
    ['pharmacy', 1],
    ['dosage', 2, 'amount and schedule of a medicine to take'],
    ['over-the-counter', 2, 'medicine: sold without a prescription'],
    ['oral', 2, 'medicine: taken by mouth'],
    ['overdose', 2],
    ['contraindication', 3],
    ['drug interaction', 3],
    ['administer', 3, 'medicine: give a drug to a patient'],
    ['intravenous', 3],
    ['topical', 3, 'medicine: applied to the skin'],
    ['sedative', 3],
    ['active ingredient', 3],

    // Хвороби та стани
    ['disease', 1],
    ['condition', 1, 'medicine: illness or health problem'],
    ['allergy', 1],
    ['heart attack', 1],
    ['cancer', 1],
    ['flu', 1],
    ['diabetes', 2],
    ['hypertension', 2],
    ['stroke', 2, 'medicine: brain damage from a blocked or burst vessel'],
    ['tumor', 2],
    ['pneumonia', 2],
    ['dehydration', 2],
    ['disorder', 2, 'medicine: condition that disrupts normal function'],
    ['mental health', 2],
    ['sepsis', 3],
    ['edema', 3],
    ['anaphylaxis', 3],
    ['hereditary', 3],
    ['comorbidity', 3, 'another disease present alongside the main one'],
    ['remission', 3, 'medicine: period when signs of a disease decrease'],
    ['relapse', 3, 'medicine: return of a disease after improvement'],

    // Організм та анатомія
    ['organ', 1, 'body part such as the heart or liver'],
    ['joint', 2, 'anatomy: place where two bones meet'],
    ['artery', 2],
    ['vein', 2, 'anatomy: vessel carrying blood back to the heart'],
    ['tissue', 2, 'biology: material made of similar cells'],
    ['immune system', 2],
    ['ligament', 3],
    ['circulation', 3, 'medicine: movement of blood through the body'],

    // Травми та невідкладна допомога
    ['first aid', 1],
    ['ambulance', 1],
    ['injury', 1],
    ['wound', 1, 'noun: injury where the skin is cut or torn'],
    ['fracture', 2, 'broken bone'],
    ['sprain', 2],
    ['unconscious', 2],
    ['CPR', 2, 'cardiopulmonary resuscitation'],
    ['stable', 2, "medicine: patient's condition not getting worse"],
    ['critical condition', 2],
    ['life-threatening', 2],
    ['shock', 2, 'medicine: dangerous drop in blood flow to organs'],
    ['concussion', 3],
    ['hemorrhage', 3],
    ['cardiac arrest', 3, 'sudden stop of the heart'],
    ['defibrillator', 3],
    ['seizure', 3, 'medicine: sudden uncontrolled electrical brain activity'],
    ['airway', 3, 'medicine: passage that air takes to the lungs'],
    ['trauma', 3, 'medicine: serious physical injury'],

    // Інфекції, гігієна та профілактика
    ['infection', 1],
    ['virus', 1, 'medicine: microbe that causes infection'],
    ['prevention', 1],
    ['hygiene', 2],
    ['sterile', 2, 'free from germs'],
    ['disinfect', 2],
    ['contagious', 2],
    ['quarantine', 2],
    ['transmit', 3, 'medicine: pass a disease to another person'],
    ['isolation', 3, 'medicine: separating infectious patients from others'],
    ['pathogen', 3],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'hospital', 'clinic', 'patient', 'pharmacist', 'specialist', 'paramedic', 'medical history', 'confidentiality',
    'symptom', 'chronic', 'asymptomatic', 'diagnosis', 'diagnose', 'pulse', 'screening', 'positive',
    'negative', 'biopsy', 'differential diagnosis', 'prognosis', 'palpate', 'injection', 'vaccine', 'therapy',
    'procedure', 'operate', 'physical therapy', 'rehabilitation', 'anesthesia', 'infusion', 'monitor', 'invasive',
    'transplant', 'medication', 'dose', 'tablet', 'antibiotic', 'dosage', 'sedative', 'active ingredient',
    'allergy', 'diabetes', 'hypertension', 'pneumonia', 'sepsis', 'anaphylaxis', 'remission', 'organ',
    'artery', 'vein', 'immune system', 'circulation', 'stable', 'shock', 'defibrillator', 'trauma',
    'infection', 'virus', 'hygiene', 'sterile', 'disinfect', 'quarantine', 'isolation', 'pathogen',
  ],
};
