module.exports = {
  key: 'relocation',
  words: [
    // Пошук житла
    ['apartment', 1],
    ['rent', 1, 'money paid regularly to live in a home'],
    ['landlord', 1],
    ['tenant', 1],
    ['roommate', 1, 'person you share an apartment with'],
    ['neighborhood', 1],
    ['furnished', 2, 'rented with furniture included'],
    ['listing', 2, 'online ad for a property to rent or buy'],
    ['viewing', 2, 'visit to see a property before renting it'],
    ['real estate agent', 2],
    ['studio apartment', 2, 'one-room apartment with a kitchen area'],
    ['affordable', 2],
    ['residential', 3, 'area: used mainly for housing'],
    ['vacant', 3, 'property: empty and available to rent'],
    ['sublet', 3, 'rent out your rented home to someone else'],

    // Оренда та переїзд
    ['lease', 1, 'rental contract for a home'],
    ['contract', 1],
    ['deposit', 1, 'rental: security money paid to the landlord'],
    ['sign', 1, 'put your signature on a document'],
    ['move in', 1, 'start living in a new home'],
    ['move out', 1, 'leave the home you lived in'],
    ['cancel', 1, 'end a contract, subscription or appointment'],
    ['notice period', 3, 'rental: time between canceling a lease and its end'],
    ['renew', 2, 'extend a contract or permit for another period'],
    ['additional costs', 2, 'costs on top of base rent: heating, water, trash'],
    ['proof of income', 2, 'documents showing your salary'],
    ['moving company', 2],
    ['change of address', 2, 'official notice that you moved'],
    ['relocate', 2, 'move to live or work in another place'],
    ['settle in', 2, 'become comfortable in a new home or place'],
    ['terminate', 3, 'officially end a contract'],
    ['guarantor', 3, 'person who promises to pay if the tenant cannot'],
    ['wear and tear', 3, 'normal damage from everyday use'],
    ['evict', 3, 'legally force a tenant to leave a home'],
    ['move-in inspection', 3, "check of a home's condition when a lease starts"],

    // Документи та статус
    ['passport', 1],
    ['visa', 1],
    ['residence permit', 1],
    ['ID card', 1, 'identity card: official card proving who you are'],
    ['valid', 1, 'officially acceptable, not expired'],
    ['temporary', 1],
    ['birth certificate', 2],
    ['marriage certificate', 2],
    ['passport photo', 2],
    ['work permit', 2],
    ['citizenship', 2],
    ['expire', 2, 'stop being valid after a certain date'],
    ['extend', 2, 'make a permit or visa valid for longer'],
    ['eligible', 3, 'meeting the conditions to get something'],
    ['issue', 3, 'officially give out a document, e.g. a visa'],
    ['permanent residence', 3, 'right to live in a country indefinitely'],
    ['certified copy', 3, 'copy officially confirmed as true'],
    ['sworn translation', 3, 'official translation by a court-certified translator'],
    ['apostille', 3, 'international certificate legalizing a document'],
    ['naturalization', 3, 'process of becoming a citizen'],
    ['temporary protection', 3, 'legal status for people fleeing war'],
    ['family reunification', 3, 'bringing family members to live with you abroad'],

    // Установи та процедури
    ['form', 1, 'paper or online document with blanks to fill in'],
    ['fill out', 1, 'complete a form'],
    ['application', 1, 'formal request, e.g. for a visa or permit'],
    ['apply', 1, 'formally request a permit, visa, etc.'],
    ['appointment', 1, 'fixed time to visit an office or doctor'],
    ['book', 1, 'reserve an appointment or service'],
    ['fee', 1],
    ['register', 2, 'officially record your address with the city'],
    ['submit', 2, 'officially hand in documents or an application'],
    ['approve', 2, 'officially accept an application'],
    ['reject', 2, 'officially refuse an application'],
    ['embassy', 2],
    ['immigration office', 2],
    ['city hall', 2, 'main local government office'],
    ['proof of address', 2, 'document confirming where you live'],
    ['pending', 3, 'application: waiting for a decision'],
    ['authorities', 3, 'government bodies with official power'],
    ['notarize', 3, 'have a notary certify a document or signature'],
    ['deregister', 3, 'officially cancel your address registration'],
    ['appeal', 3, 'legal: ask to change an official decision'],
    ['caseworker', 3, 'official who handles your case at an agency'],
    ['power of attorney', 3, 'document letting someone act legally for you'],

    // Банк, гроші та податки
    ['bank account', 1],
    ['debit card', 1],
    ['ATM', 1, 'automated teller machine: cash machine'],
    ['income', 1],
    ['tax', 1],
    ['transfer', 2, 'banking: send money to another account'],
    ['cost of living', 2],
    ['balance', 2, 'banking: money currently in an account'],
    ['IBAN', 2, 'International Bank Account Number'],
    ['exchange rate', 2],
    ['withdraw', 2, 'take money out of an account'],
    ['tax return', 2, 'yearly form declaring income to the tax office'],
    ['tax ID', 2, 'tax identification number given by the tax office'],
    ['social security number', 2, 'personal number for social insurance and pension'],
    ['self-employed', 2, 'working for yourself, not for an employer'],
    ['direct debit', 3, 'payment a company takes from your account automatically'],
    ['overdue', 3, 'bill or rent: not paid by the due date'],
    ['declare', 3, 'officially report income or goods'],
    ['credit history', 3, 'record of how you repaid past debts'],
    ['proof of funds', 3, 'evidence of enough money, e.g. for a visa'],
    ['tax residency', 3, 'status of the country where you pay income tax'],
    ['double taxation', 3, 'being taxed on the same income in two countries'],

    // Комунальні послуги, зв'язок і ремонт
    ['utilities', 1, 'water, electricity, gas and heating for a home'],
    ['utility bill', 2],
    ['electricity', 1],
    ['heating', 1],
    ['SIM card', 1, 'subscriber identity module: chip linking a phone to a network'],
    ['trash', 1, 'household waste'],
    ['repair', 1, 'fix something broken, e.g. in an apartment'],
    ['meter', 2, 'device that measures electricity, gas or water use'],
    ['provider', 2, 'company supplying a service, e.g. internet'],
    ['waste sorting', 2, 'separating trash into recycling categories'],
    ['mold', 2, 'fungus that grows on damp walls'],
    ['leak', 2, 'water escaping from a pipe or roof'],
    ['quiet hours', 3, 'set times when residents must keep noise down'],

    // Медицина та страхування
    ['family doctor', 1, 'general practitioner you see first'],
    ['pharmacy', 1],
    ['emergency room', 1, 'hospital department for urgent care'],
    ['ambulance', 1],
    ['prescription', 1],
    ['health insurance', 1],
    ['emergency number', 2, 'phone number for police, fire and ambulance'],
    ['specialist', 2, 'doctor trained in one area of medicine'],
    ['referral', 2, "doctor's note sending you to a specialist"],
    ['sick leave', 2],
    ["doctor's note", 2, 'paper confirming illness for work or school'],
    ['insurance policy', 2, 'contract describing your insurance'],
    ['cover', 2, 'insurance: pay for a cost or risk'],
    ['claim', 2, 'insurance: request for payment after damage or loss'],
    ['mandatory', 2, 'required by law, e.g. insurance'],
    ['renters insurance', 3, "covers a tenant's belongings against theft or damage"],
    ['co-payment', 3, 'part of a medical cost the patient pays'],
    ['premium', 3, 'insurance: regular price you pay for coverage'],
    ['deductible', 3, 'insurance: amount you pay before the insurer pays'],
    ['liability insurance', 3, 'covers damage you cause to other people'],
    ['reimburse', 3, 'pay back money someone spent'],

    // Діти та навчання
    ['kindergarten', 1, 'preschool for young children before primary school'],
    ['daycare', 1, 'care center for babies and toddlers while parents work'],
    ['elementary school', 1],
    ['language course', 1],
    ['high school', 2, 'secondary school, ages about 14 to 18'],
    ['enrollment', 2, 'officially registering a child at a school'],
    ['public school', 2, 'free state-funded school (US sense)'],
    ['tuition', 2, 'fees paid for school or university'],
    ['pediatrician', 2],
    ['integration course', 3, 'official language and culture course for migrants'],
    ['degree recognition', 3, 'official acceptance of a foreign diploma'],
    ['child benefit', 3, 'regular state payment for families with children'],

    // Транспорт і побут
    ['public transportation', 1],
    ['ticket', 1, 'transport: pass for a ride on a bus or train'],
    ["driver's license", 1],
    ['post office', 1],
    ['package', 1, 'parcel sent by mail'],
    ['opening hours', 2],
    ['monthly pass', 2, 'ticket for unlimited travel for one month'],
    ['fine', 2, 'money paid as a penalty, e.g. for parking'],
    ['public holiday', 2, 'official day off when offices and shops close'],
    ['parking permit', 3, 'official permission to park in a residential area'],
    ['car registration', 3, 'official recording of a vehicle with authorities'],

    // Адаптація та нове життя
    ['abroad', 1],
    ['home country', 1],
    ['local', 2, 'person who lives in the area'],
    ['expat', 2, 'person living outside their native country'],
    ['immigrant', 2],
    ['culture shock', 2],
    ['homesick', 2],
    ['adapt', 2],
    ['integrate', 3, 'become part of a new society'],
    ['host country', 3, 'country where a foreigner lives'],
    ['emigrate', 3, 'leave your country to live in another'],
    ['relocation package', 3, 'employer support for moving: costs, housing, etc.'],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'contract', 'deposit', 'guarantor', 'passport', 'visa', 'ID card', 'passport photo', 'certified copy',
    'apostille', 'naturalization', 'form', 'register', 'immigration office', 'notarize', 'appeal', 'debit card',
    'balance', 'IBAN', 'declare', 'credit history', 'electricity', 'SIM card', 'provider', 'specialist',
    'pediatrician', 'integration course', 'immigrant', 'culture shock', 'adapt', 'integrate', 'emigrate',
  ],
};
