module.exports = {
  key: 'sales',
  words: [
    // Основи продажів
    ['sale', 1, 'the act of selling something'],
    ['sell', 1],
    ['customer', 1],
    ['client', 1, 'a customer of a business or professional service'],
    ['buyer', 1],
    ['salesperson', 1],
    ['competitor', 1],
    ['offer', 1, 'a proposal to sell something at a given price'],
    ['purchase', 1, 'something bought, or the act of buying'],
    ['retail', 2, 'selling directly to the public in small amounts'],
    ['wholesale', 2, 'selling in large amounts to other businesses'],
    ['B2B', 2, 'business-to-business: selling to companies'],
    ['account executive', 2, 'sales: a salesperson who manages and closes deals'],
    ['inside sales', 3, 'selling remotely by phone, email or video'],
    ['field sales', 3, 'selling in person by visiting customers'],
    ['reseller', 3, 'company that buys products to sell them on to customers'],

    // Пошук клієнтів
    ['lead', 1, 'sales: a potential customer'],
    ['prospect', 1, 'sales: a potential customer who may buy'],
    ['cold call', 2, 'unsolicited phone call to a potential customer'],
    ['cold email', 2, 'unsolicited email to a potential customer'],
    ['prospecting', 2, 'searching for new potential customers'],
    ['lead generation', 2, 'attracting and collecting potential customers'],
    ['referral', 2, 'a customer recommended by an existing client'],
    ['outreach', 2, 'proactively contacting potential customers'],
    ['qualify', 2, 'sales: check whether a lead is a good fit to buy'],
    ['decision-maker', 2, 'person with authority to approve a purchase'],
    ['trade show', 2, 'industry exhibition where companies show products'],
    ['warm lead', 3, 'potential customer who has already shown interest'],
    ['stakeholder', 3, 'person who influences or is affected by a purchase'],
    ['nurture', 3, 'sales: develop a lead over time until ready to buy'],
    ['gatekeeper', 3, 'sales: person who controls access to a decision-maker'],
    ['ideal customer profile', 3, 'description of the best-fit customer company'],
    ['champion', 3, 'sales: a person at the client who backs your deal'],

    // Воронка та угоди
    ['deal', 1, 'sales: an agreement or a potential sale'],
    ['pipeline', 1, 'sales: all deals in progress at various stages'],
    ['close', 1, 'sales: finalize a deal'],
    ['proposal', 1, 'formal written offer to a client'],
    ['demo', 1, 'product demonstration for a customer'],
    ['follow-up', 1, 'a later contact to continue a conversation'],
    ['opportunity', 2, 'sales: a qualified deal that may close'],
    ['sales funnel', 2, 'stages a buyer goes through before purchasing'],
    ['sales cycle', 2, 'time from first contact to a closed deal'],
    ['forecast', 2, 'a prediction of future sales'],
    ['pain point', 2, 'specific problem a customer wants to solve'],
    ['convert', 2, 'sales: turn a lead into a paying customer'],
    ['value proposition', 2, 'why a customer should choose your product'],
    ['tailor', 3, 'verb: adapt an offer to a customer\'s needs'],
    ['discovery call', 3, 'first call to learn about a customer\'s needs'],
    ['buying signal', 3, 'a sign that a customer is ready to buy'],
    ['deal size', 3, 'the monetary value of a single sale'],
    ['stalled', 3, 'sales: stopped progressing, e.g. a stalled deal'],

    // Переговори та заперечення
    ['negotiate', 1],
    ['negotiation', 1],
    ['objection', 1, 'sales: a reason a customer gives for not buying'],
    ['convince', 1],
    ['benefit', 1, 'an advantage a product gives the customer'],
    ['feature', 1, 'a product characteristic or function'],
    ['value', 1, 'worth or usefulness to the customer'],
    ['counteroffer', 2],
    ['compromise', 2],
    ['bargain', 2, 'verb: negotiate the price of something'],
    ['negotiable', 2, 'open to discussion and change, e.g. a price'],
    ['win-win', 2, 'beneficial for both sides'],
    ['reassure', 2],
    ['rapport', 3, 'friendly relationship of trust with a client'],
    ['concession', 3, 'something given up during a negotiation'],
    ['leverage', 3, 'negotiation: an advantage that gives you power'],
    ['urgency', 3, 'sales: a reason to buy now rather than later'],
    ['objection handling', 3, 'responding to a customer\'s reasons not to buy'],
    ['walk-away point', 3, 'least favorable terms you will still accept'],

    // Ціни, знижки та оплата
    ['price', 1],
    ['discount', 1],
    ['quote', 1, 'sales: a written price offer'],
    ['invoice', 1],
    ['budget', 1],
    ['affordable', 1],
    ['pricing', 2],
    ['competitive', 2, 'of prices or offers: as good as or better than rivals'],
    ['margin', 2, 'profit: difference between price and cost'],
    ['subscription', 2],
    ['free trial', 2],
    ['promotion', 2, 'sales: a temporary special offer'],
    ['deposit', 2, 'money paid in advance to secure a purchase'],
    ['overdue', 2, 'not paid by the due date'],
    ['upfront', 3, 'paid in advance, before delivery'],
    ['installment', 3, 'one of several partial payments'],
    ['markup', 3, 'amount added to cost to set the selling price'],
    ['volume discount', 3, 'lower price for buying larger quantities'],
    ['tiered pricing', 3, 'different price levels for different plans'],

    // Контракти та закриття угоди
    ['contract', 1],
    ['order', 1, 'sales: a request to buy goods or services'],
    ['sign', 1, 'write your signature on a document'],
    ['deadline', 1],
    ['deliver', 1, 'provide goods or a service to a customer'],
    ['terms and conditions', 2],
    ['payment terms', 2],
    ['renewal', 2, 'extending a contract for another period'],
    ['expire', 2, 'stop being valid'],
    ['onboarding', 2, 'helping a new customer start using a product'],
    ['clause', 3, 'a specific section of a contract'],
    ['purchase order', 3, 'official document a buyer sends to order goods'],
    ['procurement', 3, 'the process of buying goods for a company'],
    ['legally binding', 3],

    // Обслуговування клієнтів
    ['customer service', 1],
    ['support', 1, 'help given to customers'],
    ['complaint', 1, 'a customer\'s statement that something is wrong'],
    ['feedback', 1],
    ['apologize', 1],
    ['recommend', 1],
    ['inquiry', 2, 'a question from a customer asking for information'],
    ['resolve', 2, 'find a solution to a problem'],
    ['ticket', 2, 'support: a recorded customer request or issue'],
    ['escalate', 2, 'pass an issue to a higher level of support'],
    ['frustrated', 2],
    ['call center', 2],
    ['response time', 2, 'how quickly support replies to a customer'],
    ['empathy', 3],
    ['troubleshoot', 3, 'find and fix the cause of a problem'],
    ['courteous', 3, 'polite and respectful'],
    ['service level agreement', 3, 'contract defining guaranteed service quality'],

    // Повернення, скасування та гарантія
    ['refund', 1],
    ['receipt', 1, 'proof of payment given to a customer'],
    ['cancel', 1, 'end an order, subscription or contract'],
    ['exchange', 2, 'swap a purchased item for a different one'],
    ['return policy', 2],
    ['warranty', 2],
    ['defective', 2],

    // Управління акаунтами та утримання клієнтів
    ['account', 1, 'sales: a client company you manage'],
    ['upsell', 1, 'sell a more expensive version to a customer'],
    ['account manager', 2, 'person responsible for a client relationship'],
    ['loyalty', 2, 'a customer\'s tendency to keep buying from you'],
    ['retention', 2, 'keeping existing customers'],
    ['upgrade', 2, 'move a customer to a better or pricier plan'],
    ['repeat customer', 2],
    ['check-in', 2, 'a short call to see how a client is doing'],
    ['dissatisfied', 2],
    ['customer satisfaction', 2],
    ['cross-sell', 3, 'sell additional related products to a customer'],
    ['churn', 3, 'business: loss of customers who stop buying or cancel'],
    ['key account', 3, 'one of the most important clients'],
    ['customer success', 3, 'team helping clients get value from a product'],
    ['testimonial', 3, 'a statement of praise from a customer'],
    ['case study', 3, 'story showing how a customer used a product'],

    // Показники та цілі
    ['target', 1, 'a goal, e.g. a sales amount to reach'],
    ['quota', 1, 'sales target set for a specific period'],
    ['commission', 1, 'pay based on a percentage of sales'],
    ['revenue', 1],
    ['quarter', 2, 'a three-month period of the business year'],
    ['conversion rate', 2, 'percentage of leads that become customers'],
    ['KPI', 2, 'key performance indicator'],
    ['metric', 2, 'a measurable value used to track performance'],
    ['exceed', 2, 'go beyond a target'],
    ['territory', 3, 'geographic area assigned to a salesperson'],
    ['outperform', 3, 'do better than others or than expected'],
    ['win rate', 3, 'percentage of deals that are won'],
    ['average order value', 3],
    ['customer lifetime value', 3, 'total revenue expected from one customer'],
    ['customer acquisition cost', 3, 'cost of winning one new customer'],
    ['recurring revenue', 3, 'regular income from subscriptions or contracts'],

    // Інструменти та комунікація
    ['appointment', 1, 'an arranged meeting at a set time'],
    ['schedule', 1, 'verb: arrange a time for something'],
    ['CRM', 1, 'customer relationship management software'],
    ['catalog', 2, 'a list of products for sale'],
    ['sales pitch', 2, 'short persuasive talk to sell something'],
    ['script', 2, 'sales: prepared text for calls'],
    ['persistent', 2, 'continuing firmly despite difficulties'],
    ['dashboard', 2, 'software: screen showing key data at a glance'],
    ['pushy', 3, 'too aggressive when trying to sell'],
    ['elevator pitch', 3, 'very short summary of what you offer'],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'client', 'retail', 'B2B', 'lead', 'lead generation', 'referral', 'qualify', 'demo',
    'convert', 'compromise', 'budget', 'margin', 'deposit', 'contract', 'deadline', 'recommend',
    'escalate', 'call center', 'empathy', 'defective', 'account manager', 'loyalty', 'upgrade', 'quota',
    'commission', 'KPI', 'metric', 'territory', 'CRM', 'catalog', 'script', 'dashboard',
  ],
};
