module.exports = {
  key: 'travel',
  words: [
    // Планування та бронювання
    ['trip', 1, 'noun: a journey to a place and back'],
    ['vacation', 1, 'time off spent traveling or resting'],
    ['travel', 1, 'verb: go on a journey'],
    ['book', 1, 'verb: reserve a ticket, room or table'],
    ['reservation', 1, 'a booked room, seat or table'],
    ['ticket', 1, 'pass for a trip by plane, train or bus'],
    ['destination', 1],
    ['cancel', 1],
    ['itinerary', 2, 'detailed plan of a trip'],
    ['round trip', 2, 'ticket or journey to a place and back again'],
    ['one-way', 2, 'of a ticket: to a place but not back'],
    ['travel insurance', 2],
    ['peak season', 2, 'busiest, most expensive time to travel'],
    ['confirm', 2, 'make a booking definite'],
    ['fully booked', 2, 'with no rooms or seats left'],
    ['refund', 2, 'noun: money returned, e.g. for a canceled booking'],
    ['reschedule', 2, 'change the date or time of a booking'],
    ['off-season', 3, 'quiet, cheaper time of year for travel'],
    ['package tour', 3, 'trip with transport and hotel sold together'],
    ['cancellation policy', 3, 'rules on refunds if you cancel a booking'],
    ['nonrefundable', 3, 'money will not be returned if you cancel'],
    ['last-minute', 3, 'booked or done shortly before departure'],

    // Аеропорт і переліт
    ['airport', 1],
    ['airline', 1],
    ['flight', 1, 'a journey by airplane'],
    ['passenger', 1],
    ['boarding pass', 1],
    ['check-in', 1, 'registering for a flight or at a hotel'],
    ['gate', 1, 'airport: door where passengers board a plane'],
    ['departure', 1],
    ['arrival', 1],
    ['delayed', 1, 'of a flight or train: later than planned'],
    ['miss', 1, 'fail to catch a flight, train or bus'],
    ['board', 2, 'verb: get on a plane, train or ship'],
    ['land', 2, 'verb: of an airplane, arrive on the ground'],
    ['terminal', 2, 'airport building for passengers'],
    ['security check', 2, 'airport screening of passengers and bags'],
    ['layover', 2, 'stop between connecting flights'],
    ['connecting flight', 2],
    ['direct flight', 2, 'flight with no stops'],
    ['economy class', 2, 'airline: cheapest standard seating class'],
    ['flight attendant', 2],
    ['jet lag', 2],
    ['duty-free', 2, 'of goods: sold at airports without import tax'],
    ['overhead bin', 3, 'storage compartment above airplane seats'],
    ['turbulence', 3],
    ['overbooked', 3, 'more tickets sold than seats available'],
    ['legroom', 3, 'space for your legs in front of a seat'],
    ['compensation', 3, 'money paid to passengers for a delay or cancellation'],
    ['disembark', 3, 'leave a plane or ship'],
    ['stranded', 3, 'unable to leave a place, e.g. after a canceled flight'],

    // Багаж і речі в дорогу
    ['luggage', 1],
    ['suitcase', 1],
    ['pack', 1, 'verb: put things into a bag for a trip'],
    ['carry-on', 2, 'small bag you take into the airplane cabin'],
    ['checked baggage', 2, 'bags handed in to travel in the plane hold'],
    ['baggage claim', 2, 'airport area where you collect your bags'],
    ['plug adapter', 2, 'device letting a plug fit foreign sockets'],
    ['baggage allowance', 3, 'amount of luggage you may take for free'],
    ['excess baggage', 3, 'luggage over the weight allowance'],
    ['toiletries', 3, 'soap, toothpaste and similar personal items'],
    ['roaming', 3, 'using your mobile network abroad'],

    // Транспорт на місці
    ['bus stop', 1],
    ['train station', 1],
    ['subway', 1, 'underground city railway'],
    ['platform', 1, 'train station area where you board trains'],
    ['map', 1],
    ['directions', 1, 'instructions on how to get somewhere'],
    ['lost', 1, 'unable to find your way'],
    ['fare', 2, 'price of a journey on public transport'],
    ['timetable', 2, 'list of departure and arrival times'],
    ['transit pass', 2, 'ticket for unlimited local public transport'],
    ['rent', 2, 'verb: pay to use a car or apartment for a time'],
    ['ferry', 2, 'boat carrying people and cars across water'],
    ['walking distance', 2, 'close enough to reach on foot'],
    ['cruise', 2, 'noun: vacation trip on a large ship'],
    ['ride-hailing', 3, 'booking a car ride through a mobile app'],
    ['validate', 3, 'transport: stamp a ticket in a machine before a ride'],
    ['detour', 3, 'longer route taken to avoid something'],

    // Проживання
    ['double room', 1, 'hotel room for two people'],
    ['reception', 1, 'hotel front desk'],
    ['check-out', 1, 'leaving a hotel and paying the bill'],
    ['hostel', 2, 'cheap shared accommodation for travelers'],
    ['accommodation', 2, 'place to stay while traveling'],
    ['deposit', 2, 'money paid in advance as security'],
    ['safe', 2, 'noun: locked box in a hotel room for valuables'],
    ['all-inclusive', 2, 'price includes meals, drinks and services'],
    ['spacious', 2, 'of a room: large, with plenty of space'],
    ['amenities', 3, 'hotel facilities such as a pool, gym or Wi-Fi'],
    ['vacancy', 3, 'free room available at a hotel'],
    ['concierge', 3, 'hotel staff who help guests with services'],
    ['housekeeping', 3, 'hotel: staff who clean the rooms'],
    ['complimentary', 3, 'given free of charge, e.g. hotel breakfast'],
    ['vacation rental', 3, 'private apartment or house rented short-term'],

    // Огляд пам'яток
    ['sightseeing', 1],
    ['souvenir', 1],
    ['tour guide', 1, 'person who shows tourists around'],
    ['opening hours', 2],
    ['guided tour', 2],
    ['landmark', 2, 'famous building or place that is easy to recognize'],
    ['attraction', 2, 'interesting place that tourists visit'],
    ['old town', 2, 'historic center of a city'],
    ['admission fee', 2, 'price to enter a museum or attraction'],
    ['explore', 2],
    ['crowded', 2],
    ['scenic', 3, 'having beautiful natural views'],
    ['breathtaking', 3, 'extremely beautiful or impressive'],
    ['heritage site', 3, 'place protected for its historic value'],
    ['tourist trap', 3, 'overpriced place aimed at tourists'],
    ['wander', 3, 'walk around slowly without a fixed route'],

    // Їжа в подорожі
    ['menu', 1, 'restaurant: list of dishes and prices'],
    ['waiter', 1],
    ['order', 1, 'verb: ask for food or drink in a restaurant'],
    ['check', 1, 'restaurant: the bill for the meal'],
    ['tip', 1, 'extra money given to a waiter'],
    ['delicious', 1],
    ['dish', 2, 'food prepared as part of a meal'],
    ['local cuisine', 2, 'typical food of a region'],
    ['street food', 2],
    ['tap water', 2],
    ['specialty', 3, 'typical dish a place is known for'],
    ['authentic', 3, 'of food or culture: genuine, traditional'],
    ['service charge', 3, 'extra fee added to a restaurant bill'],
    ['dietary restrictions', 3, 'foods a person cannot or will not eat'],

    // Гроші за кордоном
    ['currency', 1],
    ['cash', 1],
    ['ATM', 1, 'automated teller machine for withdrawing cash'],
    ['receipt', 1, 'paper proof of payment'],
    ['exchange rate', 2],
    ['currency exchange', 2, 'office where you change money'],
    ['change', 2, 'money: coins returned after paying'],
    ['withdraw', 2, 'take money out of an ATM or bank account'],
    ['commission', 3, 'fee charged for changing money'],
    ['surcharge', 3, 'extra fee added to the basic price'],
    ['foreign transaction fee', 3, 'bank fee for card payments abroad'],
    ['tax refund', 3, 'tax returned to tourists on purchases'],
    ['tourist tax', 3, 'local fee charged per night to hotel guests'],
    ['bargain', 3, 'verb: negotiate a lower price at a market'],
    ['overcharge', 3, 'charge someone too much money'],

    // Документи та кордон
    ['passport', 1],
    ['visa', 1, 'permission to enter a foreign country'],
    ['border', 1],
    ['abroad', 1, 'in or to a foreign country'],
    ['passport control', 2],
    ['customs', 2, 'border control of goods you bring in'],
    ['ID card', 2, 'identity card'],
    ['valid', 2, 'of a document: officially acceptable, not expired'],
    ['expire', 2, 'stop being valid, e.g. a passport'],
    ['embassy', 2],
    ['declare', 3, 'customs: officially state goods you carry'],
    ['consulate', 3],
    ['visa-free', 3, 'not requiring a visa to enter a country'],
    ['entry requirements', 3, 'rules you must meet to enter a country'],
    ['overstay', 3, 'stay longer than your visa allows'],

    // Надзвичайні ситуації та здоров'я
    ['emergency', 1],
    ['pharmacy', 1],
    ['police station', 1],
    ['lost and found', 2, 'office for items people have lost'],
    ['stolen', 2],
    ['report', 2, 'verb: officially tell the police about a crime'],
    ['pickpocket', 2, 'thief who steals from pockets or bags'],
    ['scam', 2, 'trick to cheat someone out of money'],
    ['food poisoning', 2],
    ['prescription', 2, "doctor's written order for medicine"],
    ['travel advisory', 3, 'official government travel warning'],
    ['insurance claim', 3, 'request for payment from an insurer'],
    ['motion sickness', 3, 'nausea caused by travel in a car, ship or plane'],
    ['evacuate', 3],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'peak season', 'package tour', 'airport', 'passenger', 'terminal', 'economy class', 'duty-free', 'turbulence',
    'compensation', 'roaming', 'platform', 'map', 'cruise', 'reception', 'hostel', 'deposit',
    'safe', 'concierge', 'souvenir', 'tour guide', 'menu', 'authentic', 'commission', 'passport',
    'visa', 'passport control', 'ID card', 'declare', 'consulate', 'police station', 'evacuate',
  ],
};
