module.exports = {
  key: 'workplace',
  words: [
    // Зустрічі та презентації
    ['meeting', 1],
    ['agenda', 1, 'list of topics to discuss at a meeting'],
    ['presentation', 1],
    ['video call', 1],
    ['slide', 1, 'one page of a presentation'],
    ['report', 1, 'document describing results or the status of work'],
    ['feedback', 1, "comments on someone's work or performance"],
    ['attend', 2, 'be present at a meeting or event'],
    ['minutes', 2, 'written record of a meeting'],
    ['brainstorm', 2, 'verb: generate ideas as a group'],
    ['action item', 2, 'task assigned to someone during a meeting'],
    ['one-on-one', 2, 'private meeting between a manager and an employee'],
    ['proposal', 2, 'business document suggesting a plan or offer'],
    ['stakeholder', 3, 'person or group affected by a project'],
    ['consensus', 3],
    ['facilitate', 3, 'guide a meeting or discussion'],

    // Листування та комунікація
    ['email', 1],
    ['inbox', 1],
    ['attachment', 1, 'file attached to an email'],
    ['reply', 1],
    ['confirm', 2],
    ['forward', 2, 'verb: send a received email on to someone else'],
    ['subject line', 2, 'title line of an email'],
    ['draft', 2, 'unfinished version of an email or document'],
    ['follow-up', 2, 'message or action that continues an earlier contact'],
    ['clarify', 2],
    ['inquiry', 3, 'formal request for information'],
    ['acknowledge', 3, 'confirm that you have received something'],

    // Планування та час
    ['deadline', 1],
    ['schedule', 1, 'noun: plan of when tasks or meetings happen'],
    ['calendar', 1],
    ['appointment', 1, 'arranged time to meet someone'],
    ['urgent', 1],
    ['available', 1, 'free to meet, talk or take on work'],
    ['reschedule', 2],
    ['time zone', 2],
    ['timeline', 2, 'planned sequence of dates for a project'],
    ['overdue', 2],
    ['estimate', 2, 'approximate calculation of time or cost'],
    ['workload', 2],
    ['prioritize', 2],
    ['delegate', 3, 'verb: give a task to someone else'],
    ['milestone', 3, 'key checkpoint in a project'],
    ['tentative', 3, 'not yet final, e.g. a tentative date'],
    ['backlog', 3, 'accumulated work that is still waiting to be done'],

    // Командна робота та проєкти
    ['team', 1],
    ['colleague', 1],
    ['project', 1],
    ['task', 1],
    ['progress', 1],
    ['update', 1, 'report on the latest status of work'],
    ['approve', 2],
    ['responsibility', 2],
    ['teamwork', 2],
    ['collaborate', 2],
    ['assign', 2],
    ['workflow', 2],
    ['implement', 3, 'verb: put a plan or decision into action'],
    ['deliverable', 3, 'concrete result to be handed over in a project'],
    ['scope', 3, 'boundaries of what a project includes'],
    ['bottleneck', 3, 'point that slows down a whole process'],
    ['accountable', 3],
    ['cross-functional', 3, 'involving people from several departments'],
    ['initiative', 3, 'new plan or project to reach a goal'],

    // Структура компанії та посади
    ['boss', 1],
    ['manager', 1],
    ['employee', 1],
    ['employer', 1],
    ['department', 1],
    ['client', 1],
    ['role', 2, 'function or job a person has in a team'],
    ['staff', 2, 'all the people who work for an organization'],
    ['supervisor', 2],
    ['CEO', 2, 'chief executive officer'],
    ['contractor', 2, 'person hired for a specific job, not on staff'],
    ['freelancer', 2],
    ['executive', 3, 'noun: senior manager of a company'],
    ['direct report', 3, 'employee who reports directly to a manager'],
    ['oversee', 3],

    // HR та умови праці
    ['job', 1],
    ['contract', 1],
    ['full-time', 1],
    ['part-time', 1],
    ['working hours', 1],
    ['day off', 1],
    ['vacation', 1, 'paid time off work'],
    ['hire', 1, 'employ a new person'],
    ['HR', 2, 'human resources (department)'],
    ['shift', 2, 'set period of work, e.g. a night shift'],
    ['sick leave', 2],
    ['policy', 2, 'official company rules on a topic'],
    ['resign', 2],
    ['fire', 2, 'dismiss someone from their job'],
    ['work-life balance', 2],
    ['confidential', 3],
    ['onboarding', 3, 'process of introducing a new employee'],
    ['probation period', 3, 'trial period at the start of a new job'],
    ['notice period', 3, 'time between resigning and leaving a job'],
    ['layoff', 3, 'job loss due to cost cuts, not performance'],
    ['turnover', 3, 'HR: rate at which employees leave and are replaced'],
    ['NDA', 3, 'non-disclosure agreement: contract to keep information secret'],

    // Зарплата та пільги
    ['salary', 1],
    ['bonus', 2],
    ['raise', 2, 'increase in salary'],
    ['overtime', 2, 'extra hours worked beyond normal hours'],
    ['benefit', 2, 'job perk such as health insurance'],
    ['payroll', 3, 'list of employees and the wages they are paid'],
    ['compensation', 3, 'total pay and benefits for a job'],
    ['severance pay', 3, 'money paid to an employee whose job is cut'],
    ['reimburse', 3, 'pay back money an employee spent on work costs'],

    // Пошук роботи та співбесіда
    ['interview', 1, 'meeting to assess a job candidate'],
    ['résumé', 1, 'document summarizing work experience; CV'],
    ['job offer', 1],
    ['candidate', 1, 'person applying for a job'],
    ['apply', 1, 'formally request a job or position'],
    ['experience', 1, 'knowledge and skill gained from past work'],
    ['skill', 1],
    ['cover letter', 2],
    ['application', 2, 'formal request for a job, not an app'],
    ['vacancy', 2, 'unfilled job position'],
    ['job description', 2, 'document listing the duties of a position'],
    ['qualified', 2, 'having the skills or diploma needed for a job'],
    ['degree', 2, 'academic qualification from a university'],
    ['reference', 2, 'person who can recommend you to an employer'],
    ['negotiate', 2],
    ['internship', 2],
    ['recruiter', 2],
    ['networking', 2, 'building professional contacts'],
    ['hiring manager', 3],
    ['shortlist', 3, 'final list of candidates chosen from applicants'],
    ['headhunter', 3, 'recruiter who searches for senior candidates'],
    ['counteroffer', 3, 'better offer made to keep or win an employee'],

    // Кар'єра та розвиток
    ['career', 1],
    ['promotion', 1, 'move to a higher job position'],
    ['training', 1, 'courses that teach job skills'],
    ['mentor', 2],
    ['workshop', 2, 'practical training session'],
    ['soft skills', 2, 'people skills such as communication and teamwork'],
    ['leadership', 2],
    ['time management', 2],
    ['junior', 2, 'lower in rank or with less work experience'],
    ['senior', 2, 'higher in rank or with more work experience'],
    ['expertise', 3],
    ['professional development', 3],

    // Продуктивність та оцінювання
    ['performance review', 2, "formal evaluation of an employee's work"],
    ['productive', 2],
    ['efficient', 2],
    ['target', 2, 'result you are expected to reach'],
    ['reliable', 2],
    ['flexible', 2, 'able to adapt to changing tasks or hours'],
    ['evaluate', 3],
    ['KPI', 3, 'key performance indicator'],
    ['proactive', 3],
    ['detail-oriented', 3],
    ['burnout', 3, 'exhaustion caused by long-term work stress'],
    ['recognition', 3, 'appreciation for good work'],
    ['constructive criticism', 3],
    ['streamline', 3, 'make a process simpler and more efficient'],
    ['escalate', 3, 'pass an issue to a higher level of authority'],

    // Офіс та віддалена робота
    ['office', 1, 'room or building where people work'],
    ['meeting room', 1],
    ['remote work', 1],
    ['break', 1, 'short rest from work'],
    ['spreadsheet', 2],
    ['business trip', 2],
    ['hybrid work', 2, 'mix of working in the office and from home'],
    ['commute', 2, 'travel regularly between home and work'],
    ['dress code', 2],
    ['mute', 2, 'turn off your microphone in a call'],
  ],
  // Інтернаціоналізми: зрозумілі українцю без перекладу — не показуємо як слово дня з рівня 4/10
  intl: [
    'presentation', 'slide', 'consensus', 'email', 'deadline', 'calendar', 'prioritize', 'delegate',
    'colleague', 'project', 'progress', 'cross-functional', 'initiative', 'boss', 'manager', 'department',
    'client', 'role', 'CEO', 'freelancer', 'contract', 'HR', 'confidential', 'bonus',
    'compensation', 'interview', 'résumé', 'candidate', 'vacancy', 'qualified', 'recruiter', 'career',
    'training', 'mentor', 'leadership', 'time management', 'productive', 'KPI', 'proactive', 'detail-oriented',
    'constructive criticism', 'escalate', 'office', 'dress code',
  ],
};
